android/fastlane/Fastfile
ios/fastlane/Fastfile

This should populate the `Release notes` section for Android:
and `Test details` section for iOS:

Added changelogs from commits between tags

---

lib/pages/chat/chat.dart

- Check if the elements are attached to scroll view before scrolling (preventing bugs)
Chat without message
Chat with messages

fix: check if scroll is attached before scrolling on sending

---

lib/config/routes.dart
lib/di/send_image/send_image_di.dart
lib/domain/usecase/send_image_interactor.dart
lib/pages/chat/chat.dart
lib/pages/chat/chat_input_row.dart
lib/pages/chat/events/message_content.dart
lib/pages/chat/events/sending_image_widget.dart
lib/presentation/extensions/asset_entity_extension.dart
lib/presentation/extensions/room_extension.dart
lib/utils/matrix_sdk_extensions/event_extension.dart
pubspec.lock
pubspec.yaml

https://github.com/linagora/twake-on-matrix/assets/43041967/687a656b-96bd-48ee-b2d1-ccac7c5cda19
https://github.com/linagora/twake-on-matrix/assets/43041967/6119bb60-4734-4c1a-af17-cec4e3da7528

TW-131: send one image without caption

---

lib/di/send_image/send_image_di.dart
lib/domain/usecase/send_images_interactor.dart
lib/pages/chat/chat.dart
lib/pages/chat/chat_input_row.dart
lib/presentation/extensions/room_extension.dart
pubspec.lock
pubspec.yaml

https://github.com/linagora/twake-on-matrix/assets/43041967/2eec030a-380d-4260-a198-bc87c148b241
https://github.com/linagora/twake-on-matrix/assets/43041967/c97608f6-73f4-4ed2-b273-12b3969d7ac4

TW-132: sending multiples image in composer

---

lib/pages/chat/chat_view.dart
lib/pages/chat/events/image_bubble.dart
lib/pages/chat/events/message.dart
lib/pages/chat/events/message_content.dart
lib/pages/chat/events/sending_image_widget.dart
lib/pages/chat/events/sticker.dart
lib/pages/forward/forward_item.dart
lib/pages/image_viewer/image_viewer.dart
lib/pages/image_viewer/image_viewer_view.dart
lib/utils/matrix_sdk_extensions/matrix_file_extension.dart
lib/widgets/mxc_image.dart

- Issue: #180 
- Resolved:
https://github.com/linagora/twake-on-matrix/assets/99852347/79e7ca58-2409-4102-97f4-8a826625bfd3
https://github.com/linagora/twake-on-matrix/assets/99852347/6ba10a12-a6b0-47f2-a979-db577e90eebd
- Support toggle tap on an image to show appbar 
https://github.com/linagora/twake-on-matrix/assets/99852347/acd6acb3-20a5-4024-a954-da449853bbd6

TW-180: Display preview received image

---

lib/config/routes.dart

- System back button has now the same behavior as in-app back button
This Closes #184

fix: add system pop in router

---

assets/l10n/intl_en.arb
lib/domain/usecase/send_image_interactor.dart
lib/pages/chat/chat.dart
lib/pages/chat/chat_input_row.dart
lib/pages/chat/dialog_permission_camera_widget.dart
lib/presentation/extensions/room_extension.dart
lib/utils/voip/permission_service.dart
pubspec.lock
pubspec.yaml

- Issue: #160 
- Resolved:
`IOS`
https://github.com/linagora/twake-on-matrix/assets/99852347/da214156-e54a-4b0f-9df9-56ff2f6c78fc
https://github.com/linagora/twake-on-matrix/assets/99852347/21812cf2-060b-44f1-bfe5-872cbc0825c4
`Android`
https://github.com/linagora/twake-on-matrix/assets/99852347/4b89819d-ae36-40b5-9851-98688cd5eddb
https://github.com/linagora/twake-on-matrix/assets/99852347/b156909e-64dd-476f-b296-9162b095e3ee

TW-160: Handle permission for Camera

---

ios/FluffyChat Share/Info.plist
ios/Runner/Info.plist
lib/utils/background_push.dart

- Notification for Android
- move to Twake in some components

Fix small bug

---

assets/l10n/intl_en.arb
lib/pages/chat/chat_emoji_picker.dart
lib/pages/chat/chat_input_row.dart
lib/pages/chat/chat_view.dart
lib/widgets/twake_components/twake_icon_button.dart

feat: enable emoji buttons in chat input

---

assets/l10n/intl_en.arb
lib/pages/new_group/new_group.dart
lib/pages/new_group/new_group_chat_info.dart
lib/pages/new_group/new_group_info_controller.dart
lib/pages/new_group/widget/expansion_participants_list.dart
lib/pages/new_private_chat/widget/loading_contact_widget.dart

feat: remove encryption and public/private

---

lib/pages/chat/chat_event_list.dart
lib/pages/chat/events/message.dart
lib/pages/chat/events/message/message_style.dart

feat: avatar bubble size and change behavior

---

assets/l10n/intl_en.arb

Kept "Room" if it's used for both Direct Message and Group Chat
This closes #274

TW-274: Rename room to group chat

---

lib/config/routes.dart
lib/di/create_direct_chat/create_direct_chat_di.dart
lib/domain/app_state/direct_chat/create_direct_chat_failed.dart
lib/domain/app_state/direct_chat/create_direct_chat_loading.dart
lib/domain/app_state/direct_chat/create_direct_chat_success.dart
lib/domain/usecase/create_direct_chat_interactor.dart
lib/pages/chat/chat.dart
lib/pages/chat/chat_input_row.dart
lib/pages/chat/chat_view.dart
lib/pages/chat/empty_chat.dart
lib/pages/chat/empty_chat_view.dart
lib/pages/chat/input_bar.dart
lib/pages/contacts_tab/contacts_tab.dart
lib/pages/contacts_tab/contacts_tab_body_view.dart
lib/pages/new_private_chat/new_private_chat.dart
lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
lib/pages/new_private_chat/widget/expansion_list.dart
lib/presentation/mixin/go_to_direct_chat_mixin.dart
lib/presentation/mixin/image_picker_mixin.dart
lib/presentation/mixin/send_files_mixin.dart
lib/presentation/model/presentation_contact_constant.dart
lib/widgets/twake_components/twake_header.dart
lib/widgets/vwidget_with_dependencies.dart

https://github.com/linagora/twake-on-matrix/assets/43041967/33408672-3acd-4abd-99ca-a8b82cdad011

TW-230: change ux when create room

---

lib/pages/chat_list/chat_list_header.dart

feat: change delete icon to archive

---

lib/pages/chat/events/message_content.dart
lib/utils/string_extension.dart
test/string_extension_test.dart

TW-221: Fix remove url markdown on messages

---

lib/pages/chat_details/participant_list_item.dart

fix: put ellipsis when display name is too long in members list

---

lib/mixin/comparable_presentation_contact_mixin.dart
lib/pages/new_private_chat/search_contacts_controller.dart

#367 
- Because the load more API return contacts sorted by uid, but the app client is sorted as displayName, so the order is not correct when loadMore is called
- Sort the contacts in client app by uuid not by displayName.
https://github.com/linagora/twake-on-matrix/assets/43041967/f8e745fa-ab0e-4272-92f4-0f8048381cdd
- When the user search contacts, the user clicks X button, and the contact list is not reloaded.
- 
https://github.com/linagora/twake-on-matrix/assets/43041967/7f4a99f6-2fa3-4856-9d2e-f5e521d815a8

TW-367: hot-fix/load-more-is-not-correct-behavior

---

lib/utils/matrix_sdk_extensions/matrix_file_extension.dart
lib/utils/resize_image.dart
pubspec.lock
pubspec.yaml

https://github.com/linagora/matrix-dart-sdk/pull/6/
https://github.com/linagora/twake-on-matrix/assets/43041967/75651e36-61c1-43bf-ba70-90d13d430b5d
https://github.com/linagora/twake-on-matrix/assets/43041967/f6512c3a-5fc8-4bf4-9ea2-e7cdfdc631e8
https://github.com/linagora/twake-on-matrix/assets/43041967/b77975e4-e66a-40a1-9057-54308b9b7378

hot-fix/missing ecrypt/decrypt function in web

---

lib/pages/chat/events/message.dart
lib/pages/chat/sticky_timstamp_widget.dart

- Issue : #334 
- Resolved:
Older than a year
https://github.com/linagora/twake-on-matrix/assets/99852347/de710a55-62f2-4318-9407-150afd7415a8
- Note:
Currently, we can't support UI when the user is scrolling message list. We will update it next sprint

TW-334: Update UI for timestamp inside chat

---

lib/pages/chat/events/message.dart

TW-473 Fix error bubble is not showing in direct chat

---

lib/pages/chat/chat.dart

fix: unselect messages after pin event

---

lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
lib/presentation/extensions/search/presentation_search_extensions.dart
lib/widgets/avatar/avatar_with_bottom_icon_widget.dart

The non-activated contact doesn't have profiles, so it will not be stored in the cache, and the default cache mode is to store only contacts in rooms.
- Don't call getProfile API on non-activated contact, because it doesn't contain any information in server
- Change cache mode from room cache to server Cache
https://github.com/linagora/twake-on-matrix/assets/43041967/e8a4435b-ff0a-433d-8496-b295e92456c5

TW-494: profile is called everytime when rebuild

---

.github/CODEOWNERS
.github/workflows/tests.yaml

These owners will be the default owners for everything in
the repo. Unless a later match takes precedence,
@global-owner1 and @global-owner2 will be requested for
review when someone opens a pull request.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file

chore: add CODEOWNERS

---

lib/pages/chat/events/message.dart
lib/pages/chat/events/message/message_style.dart

Design : 
web version (620px)
mobile (272px)
Direct message : 
Group : 
Web :
This Closes #411

fix: reduce width of bubble messages

---

lib/config/go_routes/go_router.dart
lib/pages/chat/chat.dart
lib/pages/forward/forward.dart
lib/presentation/model/forward/forward_argument.dart
lib/widgets/fluffy_chat_app.dart

- Issue: #492 
https://github.com/linagora/twake-on-matrix/assets/99852347/9b6b60e6-7ad4-42d2-9de4-384608d5682d
- Resolved: 
https://github.com/linagora/twake-on-matrix/assets/99852347/4540b4f2-f08d-4f67-9215-9e7c0f0763fa
https://github.com/linagora/twake-on-matrix/assets/99852347/c586ea7b-43bc-4c48-b7f0-ce014a11f7cf

TW-492: Forward still ins tack after forward

---

lib/pages/chat_draft/draft_chat_view.dart
lib/pages/chat_draft/draft_chat_view_style.dart

Mobile version (unchanged) : 
Web version : 
This Closes #493

TW-493: reduce draft chat width on web version

---

.github/workflows/release.yaml

This now points to the correct repo.

Correct changelog location in release description

---

lib/data/hive/hive_collection_tom_database.dart
lib/widgets/matrix.dart

TW-99: Clean ToM DB on logout

---

lib/data/network/upload_file/file_info_extension.dart
lib/domain/usecase/send_file_on_web_interactor.dart
lib/pages/chat/events/image_bubble.dart
lib/pages/chat/events/message_content.dart
lib/pages/chat/events/message_content_style.dart
lib/pages/chat/events/sending_image_info_widget.dart
lib/pages/chat/events/sending_video_widget.dart
lib/pages/chat/events/video_player.dart
lib/presentation/extensions/send_file_extension.dart
lib/presentation/extensions/send_file_web_extension.dart
lib/presentation/model/file/display_image_info.dart
lib/utils/extension/image_size_extension.dart
lib/utils/matrix_sdk_extensions/event_extension.dart
pubspec.lock

https://github.com/linagora/matrix-dart-sdk/pull/14
Ready to review
- In mobile, the image resolution can be easily get from `photo_manager` package, using the image resolution, we can determine the display resolution of image in chat. The details of how to determine in `image_size_extension.file`
- In Web, because we pick files from devices, we can't get the resolution of the image at the time we picked the image, we have to decode the image first to determine its size, it is relatively fast in even MB images. The next step is the same with mobile
- In order to store width and height of image in server, set it in `thumbnail_info` field of event
https://github.com/linagora/twake-on-matrix/assets/43041967/e74fde66-8d68-4c14-a928-8276e281a79f …

Tw 540/set different size for image

---

lib/utils/matrix_sdk_extensions/filtered_timeline_extension.dart
pubspec.lock

https://github.com/linagora/matrix-dart-sdk/pull/12
- As you can see, when you first create the group chat, a lot of events which is not necessary for users. So, I have to remove that when first create the group chat and direct chat
- "Bạn đã tham gia cuộc trò chuyện", we can remove this event simply by checking the `senderId` and the `state_key` (receiverId). If senderId equals state_key, remove the event.
- "Bạn đã kích hoạt mã hoá đầu cuối", we can remove this event by checking type of event is `Encryption` type.
- "Bạn đã thay đổi tên của nhóm" we can remove this event by checking the previous content of event (prev_content) contains old name of room or not
- "Bạn đã thay đổi avatar của nhóm" the same
- "Bạn mời ai đó vào phòng", because the event content when first create the chat …

Tw 499/only show accepted event defined user story

---

lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_body.dart
lib/pages/chat_list/client_chooser_button.dart
lib/pages/settings/settings.dart

When changing avatar, it stores in the server cache inside the client class, but when using avatar in chat list, it uses the avatar cache from room, so now we need only change to using cache from server. Then when back from setting, it will auto update the avatar.
https://github.com/linagora/twake-on-matrix/assets/43041967/7df61f22-e3fd-43e0-a546-0cfda397fe9c
https://github.com/linagora/twake-on-matrix/assets/43041967/c59a9cf7-631b-453f-b864-40cf933f7591
https://github.com/linagora/twake-on-matrix/assets/43041967/6b7b5305-3d9a-4823-a81c-1aa2ff8a72af

TW-181: avatar not change after update

---

lib/pages/chat/chat.dart
lib/pages/chat/chat_room_search_mixin.dart
lib/pages/chat/chat_view.dart

- Remove duplicate action menu
- Add close select mode button on web
- Close search when select mode active
https://github.com/linagora/twake-on-matrix/assets/12546908/86514776-5aaf-428f-8c59-b9135ed48dcb
https://github.com/linagora/twake-on-matrix/assets/12546908/9e20dc4c-4c80-48c6-8cd3-c64864fb779e
https://github.com/linagora/twake-on-matrix/assets/12546908/f626b425-7cdb-4906-8f4c-5b4e31a0bc1a
https://github.com/linagora/twake-on-matrix/assets/12546908/d1eb0d7c-8428-4642-8ec5-6e8230ba1a90

fix: Chat room duplicate action menu

---

lib/data/network/dio_cache_option.dart
lib/di/global/get_it_initializer.dart
lib/main.dart

- The hive database is initialized 2 times, first inside `setUpDioHiveCache` method, then later initialized inside FlutterHiveCollectionsDatabase class. So, the Hive will not be initialized the second time, making some boxes not created.
- Boxes are not created is the second initialization will not be closed.
- We just need to initialize the Hive database at different folder, and the problem will be resolved. So i changed the path of dio hive cache
https://github.com/linagora/twake-on-matrix/assets/43041967/afa927f9-41d3-4cc1-89dd-9e901c161fe9

hot-fix: change folder of dio interceptor cache

---

ios/Podfile
ios/Runner.xcodeproj/project.pbxproj
macos/.gitignore
pubspec.lock
pubspec.yaml
web/index.html

```
flutter clean
flutter pub get
cd ios && rm podfile.lock && pod install --repo-update
```

fix: Build iOS 17

---

ios/Runner/AppDelegate.swift
lib/utils/background_push.dart
lib/widgets/matrix.dart

- #726 
- Only fix sound for iOS
- Clear all notification when enter foreground
- Add badge
https://github.com/linagora/twake-on-matrix/assets/12546908/8bc81964-f05b-4994-8469-dee98e380e94

TW-726 Notification no sound in iOS

---

lib/utils/background_push.dart

- #726 
- https://pub.dev/packages/flutter_local_notifications#requesting-permissions-on-android-13-or-higher
https://github.com/linagora/twake-on-matrix/assets/12546908/5fdc902d-1307-4397-8a0d-c747fe171745
https://github.com/linagora/twake-on-matrix/assets/12546908/058b53e7-5df3-4527-a7f0-ce0bb8b5bafb
https://github.com/linagora/twake-on-matrix/assets/12546908/f8c15bde-bec4-49d0-84a5-c5351ed1c93d

TW-726 Notification android

---

lib/utils/matrix_sdk_extensions/filtered_timeline_extension.dart

Because user can delete their avatar, but the condition `isSomeoneChangeAvatar` check previous avatar != null, so it still show the event.
Update condition for `isSomeoneChangeAvatar`
https://github.com/linagora/twake-on-matrix/assets/43041967/13e44b25-4309-4484-914b-626b869ee728

TW-740: remove change avatar event when user first set his avatar

---

lib/pages/chat/events/reply_content.dart
lib/pages/chat/events/reply_content_style.dart

Still left : add preview image thumbnail
#741 
Design : 
Demo :

TW-741 : redesign quoted message

---

lib/pages/chat/events/message_content_style.dart
lib/presentation/mixins/play_video_action_mixin.dart
lib/widgets/video_player.dart

- missing eventId in when passing to mobile video player
- when swipe video in mobile it have black background
https://github.com/linagora/twake-on-matrix/assets/43041967/206fab32-48d8-4463-95b7-c41f01f53ab1
https://github.com/linagora/twake-on-matrix/assets/43041967/a32c2c85-fef9-461b-863e-0e33db342030

hot-fix/remove black background when swipe video

---

.github/workflows/release.yaml
appimage/AppImageBuilder.yml
scripts/build-linux-debug.sh
scripts/build-linux.sh
scripts/package-linux-debug.sh
scripts/package-linux.sh

Need some more testing with different distros: Fedora, Debian, Ubuntu, Centos, Arch, ...
Closes: #674

Fix appimage build on Linux

---

lib/pages/chat/chat.dart
lib/pages/chat/chat_event_list.dart
lib/pages/new_private_chat/new_private_chat_view.dart

- #725 
```
enum ScrollViewKeyboardDismissBehavior {
/// `manual` means there is no automatic dismissal of the on-screen keyboard.
/// It is up to the client to dismiss the keyboard.
manual,
/// `onDrag` means that the [ScrollView] will dismiss an on-screen keyboard
/// when a drag begins.
onDrag,
}
```
```
if (keyboardDismissBehavior == ScrollViewKeyboardDismissBehavior.onDrag) {
return NotificationListener<ScrollUpdateNotification>(
child: scrollableResult,
onNotification: (ScrollUpdateNotification notification) {
final FocusScopeNode focusScope = FocusScope.of(context);
if (notification.dragDetails != null && focusScope.hasFocus) {
focusScope.unfocus();
}
return false;
},
);
} else {
return scrollableResult;
}
```
If on mobile use `ScrollViewKeyboardDismissBehavior.onDrag,` it will be …

TW-725: Fix auto hide keyboard when scrolling and send msg

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
assets/l10n/intl_en.arb
lib/pages/chat/chat.dart
lib/pages/chat/chat_view.dart
lib/pages/chat/input_bar.dart
lib/pages/chat/send_file_dialog.dart
lib/presentation/enum/chat/popup_menu_item_web_enum.dart
lib/presentation/extensions/text_editting_controller_extension.dart
lib/presentation/mixins/paste_image_mixin.dart
lib/presentation/model/clipboard/clipboard_image_info.dart
lib/utils/clipboard.dart
lib/utils/platform_infos.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

Need to move fast, and priority for share file error
demo in IOS
https://photos.app.goo.gl/udnSWVpztayrQp6Y9
https://github.com/linagora/twake-on-matrix/assets/43041967/3c8e9ecf-dfad-41be-aa89-ac2ddecb55b1

TW-731: copy/paste image

---

lib/pages/chat_list/chat_list_item_subtitle.dart
lib/presentation/mixins/chat_list_item_mixin.dart
lib/utils/background_push.dart

- #796 
- Reason
```
1. When we click on a message to play the video we create a new `HeroPageRoute` different from `GoRoter`.
2. When we receive a new notification while playing a video and click on the notification.
3. Can't close `HeroPageRoute`.
```
- Close all other routes, dialog, and bottom sheet before going to new Route of `GoRouter`.
https://github.com/linagora/twake-on-matrix/assets/99852347/ebe2bb8f-ac8c-4604-ab1b-0e375a454116

TW-796: Can't jump to other room during play video

---

lib/pages/chat_list/chat_list.dart
lib/presentation/enum/chat_list/chat_list_enum.dart

- #825 
- Hide actions (Pin/unpin and read/unread) for conversation is invited. Because if you can try to use actions (Pin/unpin and read/unread) homeserver will reject actions and maybe wrongly logic and behaviour 
https://github.com/linagora/twake-on-matrix/assets/99852347/51b5c373-de8d-48d5-88b8-79676e6a1909

TW-825: Update context menu actions for chat list in web

---

lib/pages/chat/events/message_content.dart
pubspec.lock
pubspec.yaml

Links in web do now display as in mobile version (no more inkwell)
related to https://github.com/linagora/matrix_link_text/pull/1
https://github.com/linagora/twake-on-matrix/assets/48354990/b5704d7d-f610-4cb8-8334-bec5d6ce85af

TW-795: fixed link styles and center

---

lib/domain/model/preview_file/supported_preview_file_types.dart
lib/pages/chat/chat.dart
lib/utils/permission_service.dart

- #789 
https://github.com/linagora/twake-on-matrix/assets/12546908/e9d772b3-2525-4214-b1d1-044a74038f9c
https://github.com/linagora/twake-on-matrix/assets/12546908/dad851cf-6893-48e8-93fb-f7271c856d19

TW-789 Can't open files for preview in android 13

---

lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_item.dart
lib/pages/chat_list/chat_list_item_style.dart
lib/pages/chat_list/chat_list_item_subtitle.dart
lib/presentation/mixins/chat_list_item_mixin.dart

- Fix size for item in chat list
- Fix error when typing status
- Fix logic when use select mode actions in chat list

Fix size for chat list and logic

---

ios/Twake Share/Info.plist
ios/Twake Share/ShareViewController.swift
lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_item.dart
lib/pages/chat_list/chat_list_item_style.dart
lib/pages/chat_list/chat_list_item_subtitle.dart
lib/presentation/mixins/chat_list_item_mixin.dart
pubspec.yaml

- fix share extension 
- fix widget rebuild for chat list

Rel v2.3.5

---

pubspec.lock

Test PR to see my change https://github.com/linagora/flutter_matrix_html/pull/8
old : 
new:

TW-818: prevent inlineSpanEnd from getting main span styles

---

lib/config/go_routes/go_router.dart
lib/pages/chat/chat.dart
lib/pages/chat/chat_view.dart
lib/pages/chat/chat_view_style.dart
lib/pages/chat_adaptive_scaffold/chat_adaptive_scaffold.dart
lib/pages/chat_list/chat_list_header.dart
lib/pages/chat_list/chat_list_header_style.dart
lib/pages/chat_search/chat_search.dart
lib/pages/chat_search/chat_search_style.dart
lib/pages/chat_search/chat_search_view.dart
lib/utils/matrix_sdk_extensions/event_extension.dart
lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold.dart
lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body.dart
lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body_view.dart

feat(newSearch) Part 1 Responsive
https://github.com/linagora/twake-on-matrix/assets/12546908/b06e0207-ba89-4212-b9f6-ddadd56441f0
https://github.com/linagora/twake-on-matrix/assets/12546908/ccf06918-654b-4014-9786-5a26cedc9629

feat(newSearch) Part 1 Responsive

---

assets/l10n/intl_en.arb
lib/pages/new_group/contacts_selection_view.dart
lib/pages/new_group/new_group.dart
lib/pages/new_group/new_group_chat_info.dart
lib/pages/new_group/new_group_chat_info_style.dart
lib/pages/new_group/selected_contacts_map_change_notifier.dart
lib/pages/new_group/widget/selected_participants_list.dart
lib/pages/new_group/widget/selected_participants_list_style.dart

https://github.com/linagora/twake-on-matrix/assets/43041967/64fc648d-df07-4793-8f3b-e98babd1442b

TW-816: [Mobile] change the UI for create new group chat

---

lib/pages/chat_adaptive_scaffold/chat_adaptive_scaffold.dart

- GoRouter cannot get right context when inside Nested Navigator
https://github.com/linagora/twake-on-matrix/assets/12546908/b1ab86b2-2285-4f1e-a22f-2796cad442d7
https://github.com/linagora/twake-on-matrix/assets/12546908/b8ecb7c7-6f75-424d-8388-d4a97cae9c87

hotfix: Chat room cannot load more

---

scripts/package-macos-debug.sh
scripts/package-macos.sh

Python 3.12 removed `distutils`, so we have to reinstall it through `setuptools`

Fixed macOS packaging

---

lib/pages/chat/chat.dart
lib/pages/chat_list/chat_list.dart
lib/pages/settings_dashboard/settings_profile/settings_profile.dart
lib/widgets/mixins/popup_menu_widget_mixin.dart

https://github.com/linagora/twake-on-matrix/assets/99852347/1832461e-fddd-45d8-8ac1-06b0c257744f
- Click on any action → nothing happen
- Try to click many times, if it is ok → action can not be close
- In chat list screen use `context` of `Navigator`.
- When context item is opening and click on  context item, We will use the `context` of that screen to trigger closing the context menu. However, in chat list screen that trigger is using the context of `Gouter`. So the two contexts here are wrong.
- Create popup items specific to different routes
https://github.com/linagora/twake-on-matrix/assets/99852347/38d3516f-ffb4-4464-a8ad-2db213c5cdc2

Hotfix cant use context menu in chat list

---

lib/pages/chat/chat_view.dart

- Selected a message => click on pin message action in appbar action => No happened.
https://github.com/linagora/twake-on-matrix/assets/99852347/a408f19b-464a-44bf-83e1-90c51699aebc
https://github.com/linagora/twake-on-matrix/assets/99852347/0dad4b97-1b71-4a7c-8f3d-7d6ce42646d1
https://github.com/linagora/twake-on-matrix/assets/99852347/59f3d369-6327-45e5-81a3-9432406ca5f4

Hotfix: Can't pin a message in appbar action

---

lib/pages/chat/events/sending_image_info_widget.dart
lib/widgets/mxc_image.dart
pubspec.lock

https://github.com/linagora/linagora-design-flutter/pull/32

hot-fix: improve quality of thumbnail in chat and image picker

---

lib/data/network/media/cancel_exception.dart
lib/data/network/media/media_api.dart
lib/pages/chat/events/download_video_widget.dart
lib/pages/chat/events/event_video_player.dart
lib/pages/chat/events/sending_video_widget.dart
lib/pages/chat_details/chat_details.dart
lib/presentation/mixins/handle_video_download_mixin.dart
lib/presentation/mixins/play_video_action_mixin.dart
lib/utils/matrix_sdk_extensions/download_file_extension.dart
lib/widgets/video_viewer_mobile_theme.dart
lib/widgets/video_viewer_style.dart

https://github.com/linagora/twake-on-matrix/assets/43041967/471d4ea2-bcdf-48ca-92ae-0072a4ca50ea
https://github.com/linagora/twake-on-matrix/assets/43041967/e4574406-d851-4658-b466-d1b472b3fbec
https://github.com/linagora/twake-on-matrix/assets/43041967/9ec2d0f9-3748-4adc-963a-f0266bc359ca

Tw 784/improve play video

---

lib/widgets/mxc_image.dart

- mxcImage is failed to load in some cases, but it try to reload forever
- now it only try to reload only 1 times
https://github.com/linagora/twake-on-matrix/assets/43041967/b039b37a-268c-477a-adc1-d47db10a7feb

hot-fix: remove try load when load image failed

---

lib/pages/chat/events/reply_content.dart
lib/pages/chat/events/reply_content_style.dart
pubspec.lock

html list in reply shows only one item now
https://github.com/linagora/flutter_matrix_html/pull/10
#977 
old : 
new:

TW-977: quote indicator expand

---

lib/pages/chat/events/message/message.dart
lib/pages/chat/events/reply_content.dart
lib/pages/chat/events/reply_content_style.dart

https://github.com/linagora/twake-on-matrix/assets/48354990/57850ebd-020f-413a-89dd-8d3198e8c9ab
#762

TW-762: quoted image message

---

assets/l10n/intl_en.arb
assets/l10n/intl_fr.arb
assets/l10n/intl_ru.arb
assets/l10n/intl_vi.arb
lib/pages/chat_draft/draft_chat.dart
lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_view.dart
lib/pages/new_private_chat/new_private_chat.dart
lib/pages/new_private_chat/new_private_chat_view.dart
lib/pages/new_private_chat/widget/expansion_list.dart
lib/presentation/mixins/go_to_group_chat_mixin.dart

#991
- Disable Encryption by default
- Hide new group chat on web only
- Fix new group chat redirection with mixin
https://github.com/linagora/twake-on-matrix/assets/48354990/f5797c43-7fd6-47ba-bc80-ad447776bd23
https://github.com/linagora/twake-on-matrix/assets/48354990/9c859293-f076-4845-b72a-c3d470e54628

TW-991: creating DM with no encryption by default, hiding create chat on web

---

lib/pages/chat/chat.dart
lib/pages/chat/chat_event_list.dart
lib/pages/chat/chat_pinned_events/pinned_events_view.dart
lib/pages/chat/chat_view.dart

- The new logic is not correct, because `index--` can be run multiple times if widget is rebuild multiple times
- 
https://github.com/linagora/twake-on-matrix/assets/43041967/73b89f7a-2a28-4e12-a681-2ee89054f5b3
https://github.com/linagora/twake-on-matrix/assets/43041967/41fb0d42-93b6-4d76-a6ae-266eecf4ae12

hot-fix: Wrong index when rebuild events in chat

---

scripts/prepare-ios.sh

Some macOS runners does not install it by default.

Make sure xcbeautify is installed

---

.github/workflows/release.yaml
scripts/release-playstore-beta.sh

Since upgrading to flutter 3.16.5, prepare scripts need to run in project root, not in `ios` or `android` folders.

Fix working directory for prepare scripts

---

lib/utils/date_time_extension.dart

Format is: MM/dd/yyyy
Format is: MM/dd/yy

TW-1314: Change date format in chat list

---

lib/pages/chat/chat.dart
lib/pages/chat/dialog_reject_invite_widget.dart
lib/pages/chat_search/chat_search_view.dart

- 2 consecutive call to `pop()` in Web will throw an exception
- Don't use `Platform.isAndroid` use `PlatformInfo.isAndroid` instead because the first one need to use `dart:io` or `dart:html` to import, but dart.io only support non-web platform, `dart:html` is for web only
https://github.com/linagora/twake-on-matrix/assets/43041967/bf21ef79-8ed4-4754-988d-ccdd5c7a4763

Tw 1308: twake chat crashed when reject an invitation

---

pubspec.lock

https://github.com/linagora/flutter_matrix_html/pull/12
https://github.com/linagora/matrix-dart-sdk/pull/42
https://github.com/linagora/twake-on-matrix/assets/48354990/7f840ef7-91ce-40ad-a17f-fb191f0035b3
#1135

TW-1135: preserve users linebreaks in message content

---

assets/l10n/intl_en.arb
lib/domain/enums/pinned_messages_action_enum.dart
lib/domain/usecase/room/chat_get_pinned_events_interactor.dart
lib/domain/usecase/room/update_pinned_messages_interactor.dart
lib/pages/chat/chat_pinned_events/pinned_events_view.dart
lib/pages/chat/chat_pinned_events/pinned_messages.dart
lib/pages/chat/chat_pinned_events/pinned_messages_screen.dart
lib/pages/chat/chat_pinned_events/pinned_messages_style.dart

#1255 
https://github.com/linagora/twake-on-matrix/assets/48354990/0c62f1af-d0d9-4b38-a361-b71ef71d2932
[Screencast from 08-01-2024 10:45:48.webm](https://github.com/linagora/twake-on-matrix/assets/48354990/1ef87df3-9ab0-4476-9414-17369539f582)

TW-1255: Support selectable pinned events

---

lib/pages/chat_adaptive_scaffold/chat_adaptive_scaffold_builder.dart
lib/pages/chat_details/chat_details.dart
lib/pages/chat_details/chat_details_navigator.dart
lib/pages/chat_profile_info/chat_profile_info.dart
lib/pages/chat_profile_info/chat_profile_info_navigator.dart
lib/pages/chat_search/chat_search_view.dart
lib/widgets/app_bars/searchable_app_bar.dart

In mobile: if using multiple Navigator, when the user swipes to close a page, multiple navigators will receive the swipe and react to that, result in it pop 2 times, so in mobile use only 1 navigator with Go_router is enough
https://github.com/linagora/twake-on-matrix/assets/43041967/3fcf6256-efc9-4054-a77c-235ac7ad17ed
https://github.com/linagora/twake-on-matrix/assets/43041967/882c76f8-b10f-47af-acfd-b1bf84a9e6d8
https://github.com/linagora/twake-on-matrix/assets/43041967/661c73f5-5a70-464b-ac6c-4817d9758ff7
https://github.com/linagora/twake-on-matrix/assets/43041967/d3476c7f-b663-49c8-af6c-8972486e607e

Hot fix/detail chat screen

---

pubspec.lock
pubspec.yaml

The build error:
```
[        ] 	CompileSwift normal x86_64 /Users/runner/hostedtoolcache/flutter/stable-3.16.5-x64/.pub-cache/hosted/pub.dev/desktop_drop-0.4.1/macos/Classes/DesktopDropPlugin.swift (in target 'desktop_drop' from project 'Pods')
[        ] 	SwiftCompile normal x86_64 Compiling\ DesktopDropPlugin.swift /Users/runner/hostedtoolcache/flutter/stable-3.16.5-x64/.pub-cache/hosted/pub.dev/desktop_drop-0.4.1/macos/Classes/DesktopDropPlugin.swift (in target 'desktop_drop' from project 'Pods')
[        ] 	CompileSwift normal arm64 /Users/runner/hostedtoolcache/flutter/stable-3.16.5-x64/.pub-cache/hosted/pub.dev/desktop_drop-0.4.1/macos/Classes/DesktopDropPlugin.swift (in target 'desktop_drop' from project 'Pods')
[        ] 	SwiftCompile normal arm64 Compiling\ …
```

Bumped `desktop_drop` version to fix macOS builds

---

lib/pages/image_viewer/image_viewer_view.dart

- When downloading image in the image viewer in mobile, the snackbar have shown, but it's under the `ImageViewer` widget. It's because snackbar will be shown on the nearest `Scaffold`. The solution is simple, wrap ImageViewer inside Scaffold
https://github.com/linagora/twake-on-matrix/assets/43041967/4e1cfacd-49b3-454a-9c3d-3e9c35d5350e

TW-1140: fix show image downloaded in image viewer

---

lib/di/global/get_it_initializer.dart
lib/domain/app_state/room/chat_get_pinned_events_state.dart
lib/domain/usecase/room/chat_get_pinned_events_interactor.dart
lib/pages/chat/chat.dart
lib/pages/chat/chat_pinned_events/pinned_events_controller.dart
lib/pages/chat/chat_pinned_events/pinned_events_view.dart
lib/pages/chat/chat_pinned_events/pinned_messages.dart
lib/pages/chat/chat_pinned_events/pinned_messages_screen.dart

- #1283 
- Improvement pinned events in chat: 
- Remove `getPinnedMessageAction()` in `initState` because It is not certain that at that time the states in the room were set. It only works well for the first time going to room and wrong when reloading page
- Fix rebuild pinned events in chat when pin/unpin
- iOS
https://github.com/linagora/twake-on-matrix/assets/99852347/aac15352-46ab-492c-b8d5-2f0aef4a893a
- Safari
https://github.com/linagora/twake-on-matrix/assets/99852347/e4128045-e696-4ec3-a2ca-70f9e59f80d3
- Firefox
https://github.com/linagora/twake-on-matrix/assets/99852347/c389836f-dd88-4c04-9474-f8ef8b569a0b
- Chrome
https://github.com/linagora/twake-on-matrix/assets/99852347/5e3a0693-f36d-4a5f-8914-3c376a85d28b

TW-1283: Fix refresh pinned message page

---

lib/domain/model/room/room_extension.dart
lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_item_title.dart
lib/pages/chat_list/chat_list_view_builder.dart
lib/pages/chat_list/chat_list_view_style.dart
lib/presentation/decorators/chat_list/subtitle_text_style_decorator/subtitle_text_style_decorator.dart
lib/presentation/enum/chat_list/chat_list_enum.dart
lib/widgets/chat_settings_popup_menu.dart

https://github.com/linagora/twake-on-matrix/assets/48354990/8368a9ec-e89f-4e89-b1ab-ce6dc60eee88
#1394

TW-1394: Add Slidable Chat List Item - Mute/Unmute

---

lib/pages/chat/chat_pinned_events/pinned_events_controller.dart
lib/pages/chat/input_bar/focus_suggestion_controller.dart

- #1240
- When I disposed of a `ValueNotifier` but still listen to value from it. So need to check if a `ValueNotifier` has been disposed, you can use a try-catch block to catch the `FlutterError` that is thrown when you try to access a disposed `ValueNotifier`.

TW-1240: Use try catch for `ValueNotifier`

---

lib/pages/chat/input_bar/input_bar.dart

- enable the context menu on mobile, because it's sometimes convenient.
- disable in web because of the limited in copy/paste
https://github.com/linagora/twake-on-matrix/assets/43041967/77ec244c-bb1f-4654-90ca-624f9c1d3e0b

hot-fix: reenable context menu in mobile and other devices

---

lib/pages/chat/dialog_reject_invite_widget.dart
lib/pages/chat_search/chat_search_view.dart
lib/pages/forward/forward_view.dart
lib/pages/search/search_view.dart

- #1308 
- The PopScope widget, within its onPopInvoked method (triggered as the page exits the screen), contains a redundant call to Navigator.pop(). This call should be exclusively reserved for instances where the user initiates a predictive back action on Android (identified by didPop = true).
- Firefox:
https://github.com/linagora/twake-on-matrix/assets/43041967/bae6acb8-4939-4b60-9e8d-a679f86e15fa
- Safari:
https://github.com/linagora/twake-on-matrix/assets/43041967/85052f56-1133-4f44-a89d-5eece26d3c61
- Chrome:
https://github.com/linagora/twake-on-matrix/assets/43041967/6bf796cf-c44c-429b-9246-bef841a9e9dc
- Android:
https://github.com/linagora/twake-on-matrix/assets/43041967/a022d29b-c053-472a-b543-dbc40844fae4
- IOS:
https://github.com/linagora/twake-on-matrix/assets/43041967/6a394 …

TW-1308: crash app when reject the invitation

---

lib/presentation/extensions/send_file_web_extension.dart
lib/presentation/mixins/handle_video_download_mixin.dart
lib/utils/extension/web_url_creation_extension.dart

#1269 
When using Flutter for web applications, Flutter team use the HTML `<video>` tag to implement video playback functionality. To play video in Twake, we create a Blob object that encapsulates video data fetched from a server. However, video can't be played with the Safari browser.
The problem is missing the MIME type of the Blob object.
Browsers like Safari are particularly strict about security and content handling, and they rely on MIME types to optimize resource loading and enforce security policies. Without the correct MIME type, Safari might not attempt to play the video because it cannot confidently determine the video format and whether it supports that format.
https://stackoverflow.com/questions/13231915/loading-audio-via-a-blob-url-fails-in-safari?rq=3 …

TW-1269: can't play video in safari

---

lib/data/datasource_impl/contact/phonebook_contact_datasource_impl.dart
lib/utils/string_extension.dart
test/data/datasource_impl/contact/phonebook_contact_datasource_impl_test.dart
test/utils/string_extension_test.dart

- #1153 
- Duplicated contacts:
- Because a contact in the device's address book can have multiple phone numbers that differ only in format (From user created, social media,...). Therefore when fetching contacts, it duplicated.
- Filter contacts by normalize raw phone number (remove non-numeric digits) after fetching
https://github.com/linagora/twake-on-matrix/assets/80142234/70e3d424-122b-46e8-80c9-a82488184a2e

[TW-1153] Duplicated contacts from device's address book

---

lib/pages/chat/chat.dart
lib/pages/chat/chat_event_list.dart
lib/pages/chat/chat_view_body.dart
lib/presentation/model/chat/view_event_list_ui_state.dart

- #1480
- Set the default message that will be displayed is 30
- If events after apply filter < 30 ⇒ request history
- If all events are membership ⇒ Request history
- Update the condition `isEmptyChat` ⇒ `hasNoMessage`
https://github.com/linagora/twake-on-matrix/assets/99852347/7644f326-f152-4a0d-96c7-d671748681b8

TW-1480: Fix filter message in chat

---

lib/config/default_power_level_member.dart
lib/di/global/get_it_initializer.dart
lib/domain/model/room/create_new_group_chat_request.dart
lib/domain/usecase/room/create_new_group_chat_interactor.dart
lib/pages/new_group/new_group_chat_info.dart
lib/utils/power_level_manager.dart
pubspec.lock

#1400 
https://github.com/linagora/matrix-dart-sdk/pull/49
Before that, the power level of pin message default to be 100 (means that only admin can pin the message), but when create a room, we have an option to override the default power level of the members in the room. So that, we only need to set the power level of pin/unpin event to equals the power level of user in the room
https://github.com/linagora/twake-on-matrix/assets/43041967/0a19c5c1-d86b-40c7-9bb1-3034ff8f9b69

TW-1400: allow user to change avatar, group name, pin message, invite people in chat

---

lib/utils/date_time_extension.dart
test/utils/date_time_extension_test.dart

- #1503 
- The condition to check if day is in current week is wrong
* Update the condition:
* Subtract now from `now.weekday - 1` to find the start day of the current week
* Subtract the date to format from `date.weekday - 1` to find the start of the week in the date to format
* Compare these 2 values
https://github.com/linagora/twake-on-matrix/assets/80142234/5c84cea2-421d-473f-ae4d-f2799e9fc984

[TW-1503] Format time for message

---

docs/adr/0018-show-in-chat-of-media-functionality.md
lib/pages/chat/events/download_video_widget.dart
lib/pages/chat/events/event_video_player.dart
lib/pages/chat/events/image_bubble.dart
lib/pages/chat_adaptive_scaffold/chat_adaptive_scaffold.dart
lib/pages/chat_details/chat_details.dart
lib/pages/chat_details/chat_details_navigator.dart
lib/pages/chat_details/chat_details_page_view/media/chat_details_media_page.dart
lib/pages/chat_details/chat_details_page_view/media/chat_details_media_style.dart
lib/pages/chat_details/chat_details_view.dart
lib/pages/chat_profile_info/chat_profile_info.dart
lib/pages/chat_profile_info/chat_profile_info_shared/chat_profile_info_shared.dart
lib/pages/image_viewer/image_viewer.dart
lib/pages/image_viewer/image_viewer_view.dart
lib/pages/image_viewer/media_viewer_app_bar.dart
lib/pages/image_viewer/media_viewer_app_bar_style.dart
lib/pages/image_viewer/media_viewer_app_bar_view.dart
lib/presentation/enum/chat/media_viewer_popup_result_enum.dart
lib/presentation/mixins/play_video_action_mixin.dart
lib/widgets/mxc_image.dart
lib/widgets/video_player.dart
lib/widgets/video_viewer_desktop_theme.dart
lib/widgets/video_viewer_mobile_theme.dart

- Remove `onCloseRightColumn` -> use Navigator.pop with result instead
- Hide viewer action currently only work with `DownloadVideoWidget`, not `VideoPlayer`
#1499
https://github.com/linagora/twake-on-matrix/assets/43041967/e2404f37-ddab-4cff-8e82-0b7c6a4e6d57
https://github.com/linagora/twake-on-matrix/assets/43041967/bb47e9c5-1762-42fe-bb77-435b2a1a5e4c
https://github.com/linagora/twake-on-matrix/assets/43041967/c2c48887-798f-4a24-8f1b-62e323acc9e9

TW-1499: video viewer actions

---

lib/pages/chat_search/chat_search_view.dart

- The `pop()` inside PopScope is redundancy, and no need to have in Android device (even with device support [predictive back gesture](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture))
https://github.com/linagora/twake-on-matrix/assets/43041967/e751d825-105e-40d6-a79c-890ade7659ed

TW-1406: can not go back in chat search screen in android

---

lib/widgets/local_notifications_extension.dart

Issue: https://github.com/linagora/twake-on-matrix/issues/1504
Bug reproduction:
[Capture vidéo du 08-03-2024 10:11:16.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/5b047e84-b83a-4293-90a8-f5bc42b43ffc)
There was a missing condition to display a local notification.
Resolved:
[Capture vidéo du 08-03-2024 10:15:49.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/1fa321c0-fdc7-446f-a58a-c7d490768511)

TW1504: Mute chat is not working properly

---

lib/pages/chat/chat.dart

- Only update chat view when we try request history success in this case `allMembershipEvents` and `canRequestHistory`.
- Problem about scrolling in chat related to this case.
- If `allMembershipEvents` is false and `canRequestHistory` is false update chat view with timeline from `_tryLoadTimeline`
- Case `allMembershipEvents` and `canRequestHistory` is false
https://github.com/linagora/twake-on-matrix/assets/99852347/fdd48a49-812b-4d44-ab7e-dc40d80475c1
- Case `allMembershipEvents` and `canRequestHistory` is true, old chat
https://github.com/linagora/twake-on-matrix/assets/99852347/9acb5b7b-f78e-4b21-be61-d4f8f3838fe0
- Case jump to old message when search in Search screen and Chat search
https://github.com/linagora/twake-on-matrix/assets/99852347/a51bd9af-6a77-4a8f-bdf2-db93a487584d

Hot-fix: Fix loading forever when we open chat

---

lib/presentation/mixins/chat_list_item_mixin.dart
pubspec.lock
pubspec.yaml

- #1435  
- Add option for remove break line so the message preview can have more contents like Tele
- https://github.com/linagora/matrix-dart-sdk/pull/52
- `matrix-dart-sdk` library using list bullet points: `['●', '○', '■', '‣']`
- Change list bullet points follow that using for message: `['-', '-', '-', '‣']`
- Also modify so that during `calcLocalizedBody`, new bullet points will not be removed.
https://github.com/linagora/twake-on-matrix/assets/80142234/2ea54ac5-f450-44eb-a87a-f9759cf0ae17
- Case user type big dot:
https://github.com/linagora/twake-on-matrix/assets/80142234/5a283b5d-e7dd-4e74-bf6a-927005636efd
https://github.com/linagora/twake-on-matrix/assets/80142234/cdd0e60a-ed15-40da-94d5-ec9c107d5054
- Android:
https://github.com/linagora/twake-on-matrix/assets/80142234/6279e42e- …

TW-1435: Big dot in message notification and chat list preview

---

lib/pages/chat/chat.dart

- Missing unpin value when get image path.
https://github.com/linagora/twake-on-matrix/assets/80142234/bd9244b1-2a23-4686-9bd1-2847d1431c26

Hot-fix: Missing unpin icon

---

lib/pages/chat/chat_view.dart
lib/pages/chat/chat_view_style.dart
lib/widgets/twake_components/twake_icon_button.dart

- Pin icon in the chat app bar doesn't change to unpin when select a pinned message.
https://github.com/linagora/twake-on-matrix/assets/80142234/ffd69e05-9a58-45a1-a5ef-ab100ede5050
- We haven't provided icon for pinned message in the chat app bar yet.
- Web:
https://github.com/linagora/twake-on-matrix/assets/80142234/72bd3622-e4d5-4d51-97d5-acbb6da58ec2
- Android:
https://github.com/linagora/twake-on-matrix/assets/80142234/a72bad44-5de9-42fe-af1f-f67871b37f7f

Hot-fix: Add unpin icon for chat app bar

---

lib/pages/chat/chat_view.dart
lib/widgets/twake_components/twake_icon_button.dart

- `TwakeIconButton` has default `colorFilter`
- Web:
https://github.com/linagora/twake-on-matrix/assets/80142234/c4f47697-ac40-447b-aa39-577f1d720c90
- Android:
https://github.com/linagora/twake-on-matrix/assets/80142234/55d87b69-f903-4b51-bd76-2ccbfac1156c

Hot-fix: Icon send button disappeard

---

lib/pages/connect/connect_page_mixin.dart

1. When click on start message on Twake web app 
2. Redirect to sign up tab on public platform side
Automatically  redirect to sign in tab in public platform side
https://github.com/linagora/twake-on-matrix/assets/99852347/32689c11-4e63-4711-b0a7-db4592534e2d

Hot fix: Wrong redirect to public public platform on web

---

lib/pages/chat/events/message_content.dart
lib/pages/chat/events/message_download_content.dart
lib/pages/chat/events/message_download_content_web.dart
lib/pages/chat_search/chat_search_view.dart
lib/pages/image_viewer/image_viewer.dart
lib/utils/manager/download_manager/download_manager.dart
lib/utils/matrix_sdk_extensions/matrix_file_extension.dart
lib/utils/string_extension.dart
lib/widgets/mixins/handle_download_and_preview_file_mixin.dart
pubspec.lock
pubspec.yaml

- In the older version, in don't throw error or let other people handle the case when the user cancel the download. Updated version of file_saver let developer catch the error, or cancel download action. Therefore, we need to update the file_saver version.
https://github.com/linagora/twake-on-matrix/assets/43041967/44eba3c6-3a59-43e2-a294-4753d4a4c42d

Tw 1586: Part 3 downloading file web

---

lib/domain/model/extensions/platform_file/platform_file_extension.dart
lib/pages/chat/events/sending_video_widget.dart
lib/pages/chat_draft/draft_chat.dart
lib/presentation/extensions/send_file_extension.dart
lib/presentation/mixins/send_files_mixin.dart
lib/utils/matrix_sdk_extensions/event_extension.dart
pubspec.lock
pubspec.yaml

- #1605 
- https://github.com/linagora/matrix-dart-sdk/pull/53
- While sending a video, the thumbnail display condition was wrong. This condition says that only when uploading and encrypting will the thumbnail be displayed.
```dart
bool isThumbnailGenerated() {
return fileSendingStatus == FileSendingStatus.encrypting ||
fileSendingStatus == FileSendingStatus.uploading;
}
```
- Delete the false condition, update the new condition 
```dart
matrixFile.bytes != null && matrixFile.bytes!.isNotEmpty
```
https://github.com/linagora/twake-on-matrix/assets/99852347/244df7ae-0102-48af-94a7-8ff8a56ed9ba

TW-1605: Fix display thumbnail when user sent a video

---

lib/pages/search/server_search_controller.dart
lib/utils/string_extension.dart
test/utils/string_extension_test.dart

- #1589 
- Problem when querying URLs in PostgreSQL on the server side.
- https://github.com/matrix-org/synapse/issues/3024
- Step 1: Check if search text is a link and contains http protocol.
- Step 2: Remove http protocol end pass the rest of text to search categories.
https://github.com/linagora/twake-on-matrix/assets/80142234/de665dbe-87e1-4b44-a132-170cf8620139

TW-1589: Cannot search by link

---

pubspec.lock

- When device text's size is small, font size of text inside unordered list will be reduced.
- Web:
- Mobile:
- When `HtmlMessage` widget has `bottomWidgetSpan` property, the text span that wrap `<li>` tag of html parser has `textScaleFactor=0.85` automatically.
- Add `textScaleFactor=1.0` to keep the original size of text.
- https://github.com/linagora/flutter_matrix_html/pull/16
- Web:
https://github.com/linagora/twake-on-matrix/assets/80142234/e14d34c3-a2e7-44e8-9c3c-9cffd5d6bb07
- Mobile:
https://github.com/linagora/twake-on-matrix/assets/80142234/dadb8cbf-bd5c-44e6-b1ff-e60f963070af

Hot-fix: Font size of unordered list text inside messages has been reduced.

---

lib/domain/model/extensions/platform_file/platform_file_extension.dart
lib/pages/chat_draft/draft_chat.dart
lib/presentation/mixins/send_files_mixin.dart

- When get file from `file_picker`, convert to `MatrixFile`
```dart
MatrixFile toMatrixFileOnMobile({
required String temporaryDirectoryPath,
}) {
return MatrixFile.fromMimeType(
bytes: bytes,
name: name,
filePath: path ?? '$temporaryDirectoryPath/$name',
readStream: readStream,
sizeInBytes: size,
);
}
```
1. Failed because On web this is always `null`. You should access `bytes` property instead.
```dart
/// The absolute path for a cached copy of this file. It can be used to create a
/// file instance with a descriptor for the given path.
/// ```
/// final File myFile = File(platformFile.path);
/// ```
/// On web this is always `null`. You should access `bytes` property instead.
/// Read more about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ)
String? _path; …
```

Hotfix: Can't get file on web

---

lib/pages/settings_dashboard/settings/settings_item_builder.dart

TW-1523: Fix chat setting is not align with arrow

---

assets/l10n/intl_en.arb
lib/pages/chat/chat.dart
lib/pages/chat/chat_actions.dart
lib/pages/chat/chat_view.dart
lib/pages/chat/events/message_download_content.dart
lib/presentation/mixins/save_file_to_twake_downloads_folder_mixin.dart
lib/utils/dialog/downloading_file_dialog.dart
lib/utils/dialog/downloading_file_dialog_style.dart
lib/utils/exception/downloading_exception.dart
lib/utils/exception/save_to_downloads_exception.dart
lib/utils/manager/download_manager/download_manager.dart
lib/utils/permission_dialog.dart
lib/utils/permission_service.dart
lib/utils/storage_directory_utils.dart
pubspec.lock
pubspec.yaml
test/files/get_available_file_path_test.dart

- #1573 
- external_path using API `Environment.getExternalStoragePublicDirectory`, so that they can get the path of Downloads folder in device [reference](https://gist.github.com/lopspower/76421751b21594c69eb2?permalink_comment_id=4131989)
- While path_provider use API `getExternalFilesDir` to get Downloads folder path [(compare with 2 APIs)](https://stackoverflow.com/questions/10123812/difference-between-getexternalfilesdir-and-getexternalstoragedirectory)
https://github.com/linagora/twake-on-matrix/assets/43041967/1d0e802b-9cce-4bce-9ebe-c93afd642037
https://github.com/linagora/twake-on-matrix/assets/43041967/9b0bed55-ee2a-45a2-9a8b-bb1e9cd012be
https://github.com/linagora/twake-on-matrix/assets/43041967/914e3f68-3565-4c81-8ae2-2cda6970e0ae …

TW-1573: [MOBILE] [ANDROID ONLY] Part 1 - Save file to Downloads folder device

---

lib/pages/search/server_search_controller.dart

- #1613
https://github.com/linagora/twake-on-matrix/assets/99852347/2718d29f-60d4-4f42-99fb-5d5776aa60f1
https://github.com/linagora/twake-on-matrix/assets/99852347/577fe593-fad5-4693-8ef7-642d7b05ec81
https://github.com/linagora/twake-on-matrix/assets/99852347/405256e5-d9c4-4857-bcf5-327b965cf79c

TW-1613: Searching result should be empty when user remove keywords

---

docs/adr/0021-listen-to-presence-status.md
lib/pages/chat/chat_view.dart
lib/utils/room_status_extension.dart
pubspec.lock
pubspec.yaml

https://github.com/linagora/twake-on-matrix/issues/1675
The root cause was in matrix-dart-sdk. Here is the copy paste of the explanation I made there:
> This was the previous code:
> https://github.com/linagora/matrix-dart-sdk/blob/e0b65295255b852532878a948662920d6963cc6f/lib/src/client.dart#L1793-L1799
> 
> The UI previously listened to `onPresenceChanged` which is a `CachedStreamController` . This instance had a new value added in the `for each` loop for every items in `sync.presence`list. This means if there's  different values in `sync.presence` , the UI will be updated 6 times.
> 
> To handle that I changed for this code:
> 
> https://github.com/linagora/matrix-dart-sdk/blob/b0c34117c60360d3f1241af9653ddaaa88aaead4/lib/src/client.dart#L1809-L1829
> 
> Here `lowestLastActivePresence` …

TW-1675: status of user is not correct

---

lib/utils/matrix_sdk_extensions/download_file_extension.dart

https://drive.google.com/file/d/1UDY0YDVBhkMwULUPO8IaQGh3gg6Tli7T/view?usp=sharing
https://github.com/linagora/twake-on-matrix/assets/43041967/cc4d0cf3-d726-4195-bec3-47faf91608c1

TW-1693: delele the encrypted file after downloading it

---

docs/adr/memory_leak_tracking/0001-dispose-valuenotifier-when-not-used.md
docs/adr/memory_leak_tracking/0002-cancel-stream-subscription-when-not-used.md
docs/adr/memory_leak_tracking/0003-do-not-set-null-to-variable-after-cancel.md
lib/domain/usecase/room/chat_get_pinned_events_interactor.dart
lib/pages/chat/chat.dart
lib/pages/chat/events/message/message.dart
lib/widgets/matrix.dart
lib/widgets/swipeable.dart
lib/widgets/video_player.dart

https://github.com/linagora/twake-on-matrix/assets/43041967/9c460e3e-e6b1-4ad7-8503-aceae1aea0ad
https://github.com/linagora/twake-on-matrix/assets/43041967/eaf2400b-dc96-483b-9db7-812272a2054b

Tw 1650 part i/find memory leak in chat

---

pubspec.lock
pubspec.yaml

- https://github.com/linagora/dart_matrix_api_lite/pull/1
- https://github.com/linagora/matrix-dart-sdk/pull/57

update new logger for matrix sdk

---

lib/pages/chat/chat.dart
lib/widgets/context_menu/twake_context_menu.dart

- #1733
- Root cause:
- Context menu overflow on mobile
- Incorrect calculation of bottom position when opening context menu on mobile
- Chat room screen disappear when clicking on context menu actions 
- When using the context menu in the chat screen, it was popped up twice at `popupItemByTwakeAppRouter` and `TwakeContextMenu`
https://github.com/linagora/twake-on-matrix/assets/99852347/ac9518c9-07d9-4b42-9eed-0a2cd63efe7e
https://github.com/linagora/twake-on-matrix/assets/99852347/96d132ec-0708-4462-8cea-6b6f93255b82

TW-1733: Fix context menu overflow on mobile

---

lib/data/datasource/pubic_room_datasource.dart
lib/data/datasource_impl/pubilc_room_datasource_impl.dart
lib/data/model/search/public_room_request.dart
lib/data/model/search/public_room_response.dart
lib/data/network/homeserver_endpoint.dart
lib/data/network/search/public_room_api.dart
lib/data/repository/public_room_repository_impl.dart
lib/di/global/get_it_initializer.dart
lib/domain/app_state/search/public_room_state.dart
lib/domain/repository/public_room_reposity.dart
lib/domain/usecase/search/public_room_interactor.dart

[PART-1] TW-1690: Implement search external channel

---

lib/pages/chat/chat.dart
lib/pages/chat/events/event_video_player.dart
lib/pages/chat/events/html_message.dart
lib/pages/chat/events/image_bubble.dart
lib/pages/chat/events/image_builder_web.dart
lib/pages/chat/events/images_builder/image_bubble.dart
lib/pages/chat/events/images_builder/image_builder_web.dart
lib/pages/chat/events/images_builder/image_placeholder.dart
lib/pages/chat/events/images_builder/message_content_image_builder.dart
lib/pages/chat/events/images_builder/sending_image_info_widget.dart
lib/pages/chat/events/images_builder/unencrypted_image_builder_web.dart
lib/pages/chat/events/message/message.dart
lib/pages/chat/events/message_content.dart
lib/pages/chat/events/message_content_style.dart
lib/pages/chat/events/sticker.dart
lib/pages/chat/send_file_dialog/media_page_view_widget.dart
lib/pages/chat/sticker_picker_dialog.dart
lib/pages/image_viewer/image_viewer.dart
lib/pages/image_viewer/image_viewer_view.dart
lib/utils/extension/build_context_extension.dart
lib/utils/matrix_sdk_extensions/event_extension.dart
lib/widgets/avatar/avatar.dart
lib/widgets/mxc_image.dart

#1650 
- Currently, we use `Image.memory` to load image data to view, which required two steps, its need to downloaded to memory first, then pass it to the widget, which make app freezes a lot while scrolling.
-  Moreover, `MxcImage` use combination of animation and setState when image is downloaded, which is not efficient.
-`Image.network` have multiple optimization, and build-in method (`loadingBuilder` and `frameBuilder`) which make the rendering in web more efficient. And We don't have to convert to bytes anymore, use the download link, and the browser will help us caching the image.
- For the case of encrypted chat, we still have to use `Image.memory` because of we have to decrypte bytes data after downloading done
- For the case of `Avatar`, use cacheWidth to reduce the memory usage …

TW-1650: part II: memory footprint in web: remove unnecessary animation and Image.memory in web

---

pubspec.lock

https://github.com/linagora/dart_matrix_api_lite/pull/2
The log only show in android, and not show in ios. And its because this `log` function from dart:developer is used specially for Flutter debug devtools not for `stdout` of terminal. So back to use `print` function. 
https://stackoverflow.com/questions/69689138/developer-log-does-not-print-log

hot-fix: logger is not show in mobile platform

---

lib/pages/chat/chat.dart
lib/pages/chat_details/chat_details.dart
lib/pages/chat_details/chat_details_page_view/chat_details_members_page.dart
lib/presentation/extensions/event_update_extension.dart

When the `StreamBuilder` receives a new event update from the network, it rebuilds all widgets under it to ensure the UI is updated correctly. The algorithm for updating widgets relies on changes in their parameters.
In the case of members, the parameter is `memberNotifier`, which isn't updated when new changes come in. For the avatar, the parameter is `avatarUrl`, which updates correctly whenever `avatarUrl` changes.
To solve this issue, we need to have a listener, which will listen for member changed event, then we can updated correctly
https://github.com/linagora/twake-on-matrix/assets/43041967/101f1d85-3dbe-49c2-b0a7-b31d66277fda
https://github.com/linagora/twake-on-matrix/assets/43041967/077657ad-0467-421e-af0b-663ac44331f1
https://github.com/linagora/twake-on-matrix/assets/43041967/7 …

Tw 1773: Members chat group chat isnot updated correctly

---

lib/data/datasource/tom_configurations_datasource.dart
lib/data/datasource_impl/tom_configurations_datasource_impl.dart
lib/data/repository/tom_configurations_repository_impl.dart
lib/domain/repository/tom_configurations_repository.dart
lib/pages/settings_dashboard/settings/settings.dart
lib/presentation/mixins/connect_page_mixin.dart
lib/widgets/matrix.dart

- #1785 
- When login success, only set value for `authUrl` however when set active to another account we can't set it again
- When logout an account on multi account, the condition for deleting ToM database is wrong
- please prevent delete all tom-db when client logout, only do it when no client available.
- delete specific client in tom-db when this client logout.
https://github.com/linagora/twake-on-matrix/assets/99852347/a79042b9-1e35-453e-a371-4e45e00ec702
https://github.com/linagora/twake-on-matrix/assets/99852347/aefe4150-08cc-4710-9e20-519191731f91

TW-1785: Improve logout for multiple homeserver

---

lib/pages/chat_list/chat_list.dart

- #1526 
The `pushRuleState` is checked against the current `pushRuleState` of each room inside the loop. If they are the same, the loop continues to the next iteration without executing the following code. If they are different, the setPushRuleState(pushRuleState) method is called to update the `pushRuleState` of the room. 
The `pushRuleState` variable is defined outside the for loop, and its value is determined before the loop starts. This means that the `pushRuleState` value will be the same for all iterations of the loop.
- Mobile 
1. Mute/unmute
https://github.com/linagora/twake-on-matrix/assets/99852347/62b4b150-67d9-44d2-9007-8e9e9e12eee0
2. Read/unread
https://github.com/linagora/twake-on-matrix/assets/99852347/deb403c1-eb17-44a2-aa48-0ce23f0b0075
3. Pin/unpin …

TW-1526: Fix Cannot unmute more than 2 chats at the same time

---

lib/domain/app_state/search/pre_search_state.dart
lib/domain/usecase/search/pre_search_recent_contacts_interactor.dart
lib/pages/search/recent_contacts_banner_widget.dart
lib/pages/search/search.dart
lib/pages/search/search_view.dart

###DESC:
- #1793 
- Change from member of recent groups to recents direct chat
- android:
https://github.com/linagora/twake-on-matrix/assets/43041967/7807d8f8-281c-4f8b-b5bc-6d98712924d2
- ios:
https://github.com/linagora/twake-on-matrix/assets/43041967/546a1eea-e14a-4585-baa9-2b407e201e35
- web:
https://github.com/linagora/twake-on-matrix/assets/43041967/05a55db1-daf4-495c-94cb-c0dc5e5770ed

TW-1793: recent chats are not recent

---

assets/l10n/intl_en.arb
lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_header.dart
lib/pages/homeserver_picker/homeserver_picker.dart
lib/pages/multiple_accounts/multiple_accounts_picker.dart
lib/pages/settings_dashboard/settings/settings.dart
lib/pages/settings_dashboard/settings_profile/settings_profile.dart
lib/pages/settings_dashboard/settings_profile/settings_profile_state/get_clients_ui_state.dart
lib/pages/settings_dashboard/settings_profile/settings_profile_view.dart
lib/pages/settings_dashboard/settings_profile/settings_profile_view_mobile.dart
lib/pages/settings_dashboard/settings_profile/settings_profile_view_mobile_style.dart
lib/pages/settings_dashboard/settings_profile/settings_profile_view_web.dart
lib/widgets/avatar/avatar.dart
lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body.dart
lib/widgets/matrix.dart
lib/widgets/twake_components/twake_header.dart
lib/widgets/twake_components/twake_header_style.dart

The currentProfileNotifier is updated multiple times during the build of chat list, and when its first build, the `_activeClient` default is first client in the all clients.
-> Solution: move `currentProfileNotifier` to only the TwakeHeader, and make sure it avatar updated only one if have the new change in avatar or the inital build. Add the condition for check the `_activeClient` for update the avatar correctly
https://github.com/linagora/twake-on-matrix/assets/99852347/db435564-50bf-4998-b886-3e3109f6b1d6
- Switch and logout
https://github.com/linagora/twake-on-matrix/assets/99852347/d5b83890-204e-42d4-a0da-42661bbbfe25

TW-1356: Reword accounts picker

---

.github/workflows/build.yaml
.github/workflows/gh-pages.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
.gitlab-ci.yml
Dockerfile
scripts/build-android-apk.sh
scripts/build-android-debug.sh
scripts/build-linux-debug.sh
scripts/build-linux.sh
scripts/build-macos.sh
scripts/build-web.sh
scripts/build-windows.sh
scripts/code_analyze.sh
scripts/prepare-ios.sh
scripts/release-playstore-beta.sh

in 3.22.1, flutter hot fix the bug related to build_runner that make us to rerun flutter pub get again.
https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md#3221-may-22-2024

hot-fix: fix the error l10n not found after build runner build

---

lib/pages/chat_details/participant_list_item/participant_list_item.dart
lib/pages/invitation_selection/invitation_selection.dart
lib/pages/new_group/contacts_selection_view.dart
lib/pages/profile_info/profile_info_view.dart
lib/widgets/app_bars/searchable_app_bar.dart

- #1841 
- When we open a dialog on Web using `Navigator` however when we close a dialog → we use `go_router` (ex: context.pop() ...) →confusion when using `go_router` and `Navigator`
https://github.com/linagora/twake-on-matrix/assets/99852347/8c30b68b-e03a-40f6-a180-b9d6f8179803
https://github.com/linagora/twake-on-matrix/assets/99852347/0b30d55b-4153-4b79-abde-9227932cb669

TW-1841: Fix back screen when use `go_router` and `Navigator`

---

scripts/prepare-ios.sh

We're using `macos-latest` runner, which corresponds to:
https://github.com/actions/runner-images/blob/870d08d9cbff9a9a2b0e805c7e41e5238c184bf0/images/macos/macos-14-arm64-Readme.md?plain=1#L75

Removed xcbeautify installation because it's preinstalled on runners

---

lib/pages/chat/chat.dart
lib/pages/chat/chat_event_list.dart
lib/pages/chat/chat_pinned_events/pinned_messages.dart
lib/pages/chat/chat_pinned_events/pinned_messages_screen.dart
lib/pages/chat/events/message/message.dart
lib/pages/chat/events/message/message_content_with_timestamp_builder.dart
lib/pages/chat_list/chat_list.dart
lib/widgets/context_menu/context_menu_action.dart
lib/widgets/context_menu/context_menu_action_item_widget.dart
lib/widgets/context_menu/twake_context_menu.dart
lib/widgets/context_menu/twake_context_menu_area.dart
lib/widgets/mixins/twake_context_menu_mixin.dart
lib/widgets/mixins/twake_context_menu_style.dart

- #1787 
- Right now, `close` context menu function and context menu `actions` function are called parallel -> for actions that show loading dialog, the expected behavior will not work
- Move UI of `actions item` into context menu widget
- Call `actions` function after `close` function
- Web:
https://github.com/linagora/twake-on-matrix/assets/80142234/269b68b5-4667-4826-b3b1-d1c5657a0cb0
https://github.com/linagora/twake-on-matrix/assets/80142234/b324f911-5b02-461f-83c9-a2c29d045ddd
- Android:
https://github.com/linagora/twake-on-matrix/assets/80142234/eee65d22-020d-45e0-8a66-f6040e1d4778
https://github.com/linagora/twake-on-matrix/assets/80142234/48cecf8a-7fd0-4539-a6a9-3283862d2330

TW-1787: Improve when leave chat

---

lib/pages/search/search_text_field.dart

#1812 
wrapped the suffixIcon in   `ValueListenableBuilder`  to determine if the icon should be displayed or not 
[chat1.webm](https://github.com/linagora/twake-on-matrix/assets/160496984/e1729a3f-fbb6-4cd8-9294-46de515345e2)
https://github.com/linagora/twake-on-matrix/assets/160496984/fc9458a7-c848-469d-a888-82c01ab08e7b

TW-1812 Remove X from the search bar when it's empty

---

assets/l10n/intl_en.arb
lib/presentation/mixins/media_picker_mixin.dart
lib/presentation/mixins/single_image_picker_mixin.dart
lib/presentation/style/media_picker_style.dart
pubspec.lock

https://github.com/linagora/linagora-design-flutter/pull/44
https://github.com/linagora/twake-on-matrix/issues/1644
https://github.com/linagora/twake-on-matrix/assets/43041967/e4eb9390-234a-40d4-bd0e-81d4eb29fcac
https://github.com/linagora/twake-on-matrix/assets/43041967/c6113142-1b8e-4fe9-857b-bc2ab2ea5c95

TW-1644: allow access to the gallery is not center

---

lib/app_state/success.dart
lib/domain/contact_manager/contacts_manager.dart
lib/pages/multiple_accounts/multiple_accounts_picker.dart
lib/presentation/extensions/value_notifier_custom.dart
lib/presentation/mixins/contacts_view_controller_mixin.dart
lib/widgets/matrix.dart
test/domain/contacts/contacts_manager_test.dart
test/mixin/contacts_view_controller_mixin_test.dart

- #1791 
https://github.com/linagora/twake-on-matrix/assets/99852347/c8b57a6e-8b56-4d77-ab5c-ce13ca7b6b05
https://github.com/linagora/twake-on-matrix/assets/99852347/4f1e3451-9a53-4765-91d9-9dfdc3b289ec
https://github.com/linagora/twake-on-matrix/assets/99852347/38e95d45-262f-4d25-bdd0-6654cff9f6c1

TW-1791: Improve display contacts on multiple homeserver

---

Dockerfile

Fixed https://github.com/linagora/twake-on-matrix/issues/1883

Pinned Nix version to 2.22.1 to fix broken build

---

lib/presentation/extensions/go_router_extensions.dart
lib/utils/background_push.dart

- #1587
- Reproduce:
1. Open room A, received notifications and still stay in room A
2. Click on notifications and go to room
3. Back to chat list and can't open room A
- Root cause: 
- When use `_clearAllNavigatorAvailable` missing the case still stays in the current room
- Side effect:
- #915 
- If click on notification, go to room same current room not use `_clearAllNavigatorAvailable`
- iOS
https://github.com/linagora/twake-on-matrix/assets/99852347/075a636e-898b-4048-830c-d6c68db3e41a
- Android
https://github.com/linagora/twake-on-matrix/assets/99852347/683e68eb-02ca-4b34-8ab3-d7628e2de1d7
https://github.com/linagora/twake-on-matrix/assets/99852347/f0b61b6a-b33f-40c9-954f-7165bc187aa7
- Web
https://github.com/linagora/twake-on-matrix/assets/99852347/090543ad-46bb-43c0-b814-65011bb9a1b …

TW-1587: Fix can't open chat when click on notification

---

.github/workflows/release.yaml

So the UI can display artifact name for each OSes: `twake-release-android`, `twake-release-windows`, `twake-release-linux`, `twake-release-macos`.
Currently it's missing `android`:

Renamed artifact to describe the OS

---

assets/l10n/intl_en.arb
lib/pages/chat/chat.dart
lib/pages/chat/chat_app_bar_title.dart
lib/pages/chat/chat_view.dart
lib/utils/date_time_extension.dart
lib/utils/room_status_extension.dart
test/utils/get_localize_status_test.dart

- for chat we don't have `lastActiveTimestamp`, keep `offine` status (in this case, it means user never online before or in the case of can't get presence of user)
- for people that offline longer than 10 hours, we display `aWhile ago` instead of `offline`
https://github.com/linagora/twake-on-matrix/assets/43041967/12bc31cc-babd-4fb2-a860-bcd8297ddc32
https://github.com/linagora/twake-on-matrix/assets/43041967/6e10b9f4-b82f-4bda-b9f4-935748262cc6

TW-1827: online status is not updated correctly

---

lib/pages/bootstrap/bootstrap_dialog.dart
lib/pages/bootstrap/tom_bootstrap_dialog.dart

https://github.com/linagora/twake-on-matrix/assets/99852347/bed1f24b-001e-43a6-9d1e-52f18c92aeee
https://github.com/linagora/twake-on-matrix/assets/99852347/2676a739-e45f-4d00-b7b5-eff1c5bf090c
https://github.com/linagora/twake-on-matrix/assets/99852347/53a23f58-d8fb-499c-8684-2b9427d160e4

Handle error recovery key lost

---

lib/pages/settings_dashboard/settings_profile/settings_profile.dart
lib/widgets/mixins/on_account_data_listen_mixin.dart
lib/widgets/twake_components/twake_header.dart

#1834 
- The avatar in the chat list screen have not listen for uploading new avatar, so only when you terminate the app, the avatar will be updated correctly
- We can listen for uploading new avatar using onAccountData stream from matrix client. We also need to put it in the `didUpdateWidget` method, because when switch account, we need to listen to the right client
- The other change is for improve the UX a bit when uploading new avatar
https://github.com/linagora/twake-on-matrix/assets/43041967/41452fd2-a0f9-4e86-ac9f-3789d3386aa5
https://github.com/linagora/twake-on-matrix/assets/43041967/30a1f25e-f751-461d-bd54-05d0f38319b6

TW-1834: profile image is not updated in multiple account

---

lib/domain/keychain_sharing/keychain_sharing_manager.dart
lib/utils/matrix_sdk_extensions/flutter_hive_collections_database.dart

#1900
- in your iphone, lock the iphone and make sure the Twake Chat is terminated. Wait for a notification from encrypted room to come, when the notification appear in the screen, wait for 5-10 second, then unlock the iphone, click the notification, the user will be redirect to /twakeWelcome page.
- Logs:
- When the device are locked, Twake chat can't access to the keychain storage, then because of the twake chat is terminated, the app need to run from main() again, in main method, it need to create client again. When creating a new client, the old logic need to write data to the Keychain -> this operation will throw an exception at runtime, and the client is null -> user is log out
add a try/catch in the write operation to keychain, so that if its failed, it still return the old client. …

Tw 1900: IOS is forced to log out many times

---

lib/pages/contacts_tab/contacts_appbar.dart
lib/pages/search/search_text_field.dart
lib/widgets/app_bars/searchable_app_bar.dart
test/widget/app_bars/searchable_app_bar_test.dart

hot-fix for: https://github.com/linagora/twake-on-matrix/issues/1812
Removed x from search bar in contacts tab, chat creation and group chat creation
https://github.com/linagora/twake-on-matrix/assets/160496984/6c6ab9c0-4f20-42f0-a3b0-7d2e9ef5479e
[1812mobile.webm](https://github.com/linagora/twake-on-matrix/assets/160496984/aadf9518-6baa-43b5-a85c-9dd79cde42b1)

hot-fix:TW-1812-remove x when searchbar is empty

---

lib/pages/chat_adaptive_scaffold/chat_adaptive_scaffold_builder.dart

#1920
When the width of the screen is less than `bodyRadioWidth` (which is 472), the `getChatBodyRatio` will be large then 1, which will make the `getMinDesktopWidth` be negative. The negative number in breakpoint will make the responsive wrong when the width is less than 472.
The solution is when the width of screen is less than `bodyRadioWidth`, we will make the breakpoint for desktop to be constant like before. So that only when the screen is in tablet or desktop will apply the ratio calculated by new formular. …

TW-1920: hot-fix: wrong responsive when size of screen is small

---

lib/pages/contacts_tab/contacts_tab.dart
lib/pages/contacts_tab/contacts_tab_body_view.dart
lib/pages/contacts_tab/contacts_tab_view_style.dart
lib/pages/search/recent_item_widget.dart
lib/presentation/mixins/contacts_view_controller_mixin.dart

- #1916 
- Right now, when search for exact Matrix ID, it will return contacts as an External contact.
- Right now, we use `Contact` widget for rendering recent contact. However, `Contact` widget will only fetch profile information if `status` is `active`. Because recent contact don't have `status` value, cannot fetch avatar.
- Only return External contact if search for contact return `empty` and keyword is a Matrix ID
- Use `RecentItemWidget` instead.
- Need merge: #1911 
- Change base branch to `main`
- Web:
https://github.com/linagora/twake-on-matrix/assets/80142234/c1b81e02-cb79-44a2-b753-ffa2da4f25f7
- Android:
https://github.com/linagora/twake-on-matrix/assets/80142234/f5f28600-684b-48d6-8cbf-37465335b02c
- IOS:

TW-1916: Improve search exact Matrix ID inside Contact tab

---

lib/pages/bootstrap/bootstrap_dialog.dart
lib/pages/bootstrap/tom_bootstrap_dialog.dart

#1766 
We create the bootstrap dialog at the wrong time, so the state of bootstrap dialog always be `newSSSSKey`, that means, it will call to POST request to upload new key no matter what even when you have got the recovery key success before in tom server.
The solution is direct. We move the creating bootstrap dialog after we have loaded successfully the roomData and accountData from homeserver. This will make sure that the bootstrap state is correct and will not call to upload recoveryKey everytime we log in.
Can …

TW-1766: fix 500,404 error in POST request when login

---

lib/pages/chat_list/chat_custom_slidable_action.dart
lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_view_builder.dart
lib/pages/chat_list/chat_list_view_style.dart
lib/pages/chat_list/common_chat_list_item.dart
lib/pages/chat_list/slidable_chat_list_item.dart
test/pages/chat_list/chat_list_test.dart

- #1941 
- Change background color of chat list item's actions
- Web:
https://github.com/linagora/twake-on-matrix/assets/80142234/e10fbfb3-fadb-4667-856b-9c458a12089d
- Android:
- IOS:

TW-1941: Update quick actions

---

CHANGELOG.md
pubspec.yaml

- #1879 Fix online status is not updated correctly
- #1892 Handle error recovery key lost
- #1898 Fix memory leak in file picker
- #1897 Fix profile image is not updated in multiple account
- #1903 Check dialog status before sending file
- #1911 Fix can't open chat when search exact Matrix ID
- #1921 Fix iOS is forced to log out many times
- #1910 Remove x when searchbar is empty 
- #1938 Fix wrong responsive when size of screen is small
- #1930 Improve search exact Matrix ID inside Contact tab
- #1948 Fix jump exactly to message in the notification on Mobile
- #1946 Fix 500,404 error in POST request when login
- #1940 Upload feature
- #1890 Renamed artifact to describe the OS
- #1880 Standarlize Appbar and Appgrid popup
- #1889 Change style loading dialog
- #1894 Change message info …

Bump version to v2.6.0

---

lib/config/app_config.dart
lib/presentation/extensions/send_file_extension.dart
lib/presentation/extensions/send_file_web_extension.dart
lib/utils/matrix_sdk_extensions/download_file_extension.dart
lib/widgets/mxc_image.dart

#1901 
Sometimes the thumbnail of video is not an image (this is due to testing or old video or maybe come from another platform), so that when display to screen, it will throw an exception during decode the image.
Now when create a thumbnail, we will add the extension which indicate its an image, and in the receiver side, if the thumbnail is not the image, we will throw an exception and handle the exception.
Try to send video and …

TW-1901: crash app when open play video mobile

---

lib/presentation/extensions/send_file_extension.dart
lib/utils/manager/storage_directory_manager.dart
pubspec.lock
pubspec.yaml

#1980 
HEIC, HEIF image format can't display in web platform
We have to convert HEIC, HEIF format to common image format like JPG when send images from iOS, so that it can be displayed in other platform. 
- `https://pub.dev/packages/image_editor_plus` has an output is raw data not file, so i don't use it, it may freeze the app
Try sending HEIC, HEIF files from iOS device, then see that its displayed well in other platforms or not …

TW-1980: Convert HEIC files to jpg file

---

lib/utils/string_extension.dart
test/utils/string_extension_test.dart

- #1968 
- Create a test case to verify that the `buildHighlightTextSpans` method correctly handles special characters in the `highlightText`.
- Ensure the test case checks for proper escaping and highlighting of the text.
- Web:
- IOS:
https://github.com/user-attachments/assets/22e75d69-6c1b-4bbe-8f82-d85ae37c4cef

TW-1968: Break UI when search with keyword

---

lib/pages/search/server_search_controller.dart

- #1994 
- When using load more for chat search, missing the condition.
- Web:
https://github.com/user-attachments/assets/056ecd6d-b848-4e4a-ad6c-0373a5ba8656
https://github.com/user-attachments/assets/e8648103-6157-4d0d-bfd2-335880b2082e
- IOS:
https://github.com/user-attachments/assets/20e74586-8e84-4d6c-925f-6415f0abab0c

TW-1994: Fix load more for chat search

---

android/app/src/main/AndroidManifest.xml
pubspec.lock
pubspec.yaml

- #2002 
- Google Console rejected because deep link `matrix.to` no working
- Remove deep link `matrix.to` on android
- We're improving it later

TW-2002: Remove deeplink `matrix.to` on android

---

lib/presentation/extensions/send_file_extension.dart
lib/presentation/extensions/send_file_web_extension.dart

#2001 
- We accidentally upload the original file instead of thumbnail file
- We do not use correct file mimeType for thumbnail
- Upload original file -> thumbnail file
- add mimeType for thumbnail when sending video
- Send video, image in multiple platform to see if have thumbnail or not
- Android:
https://github.com/user-attachments/assets/2bb4eded-8918-451a-b559-45113884a9f0
- Web:
https://github.com/user-attachments/assets/d119b838-5c06-4ed0-828a-748a7c856334
- IOS:

Tw 2001: No previews for video

---

lib/pages/chat/chat.dart
lib/pages/chat/chat_event_list.dart
lib/pages/chat/chat_pinned_events/pinned_events_controller.dart

- #1974 
- For load more:
- I updated logic to load more in chat. When user scrolls to the last element of the list message, we're display a refresh icon and call back to request history. 
- Updated the highlight message when click to reply message
- Remove old logic ( `requestHistory` ) of listen scroll in chat
- Web:
https://github.com/user-attachments/assets/6c606b29-4eea-47ea-b273-d3d186b476ba
- IOS:
https://github.com/user-attachments/assets/5cf5494b-c760-437d-9038-1fb3b94e389f

TW-1974: Fix cannot jump to reply

---

lib/presentation/mixins/contacts_view_controller_mixin.dart

https://github.com/linagora/twake-on-matrix/issues/1964
The external search was not handled on presentationContactNotifier failure
handle this case
- Web:
Chrome:
[Capture vidéo du 26-07-2024 14:42:10.webm](https://github.com/user-attachments/assets/216654e4-56d1-4010-b77f-cc822e371a2c)
[Capture vidéo du 26-07-2024 14:36:51.webm](https://github.com/user-attachments/assets/5231c6ac-0181-4e5d-bf32-49ee6ee7f168)
- Android:
https://github.com/user-attachments/assets/9ce18539-b5f2-48c0-80cc-25a31ce145e5
- IOS:

TW-1964: handle full matrix id on presentationContactNotifier fail

---

lib/config/go_routes/go_router.dart
lib/pages/chat_details/participant_list_item/participant_list_item.dart
lib/pages/chat_list/receive_sharing_intent_mixin.dart
lib/pages/share/share.dart

#1936 
Change from `go` to `push`
- Web:
- Android:
https://github.com/user-attachments/assets/f98fb53c-e0f5-49da-94d6-edbc605fbea3
- IOS:
https://github.com/user-attachments/assets/97314f25-234b-434c-9977-cebcb064aa95

TW-1936: fix the share screen don't show up when sharing an image

---

lib/domain/model/room/room_list_extension.dart
lib/pages/search/search_contacts_and_chats_controller.dart

https://github.com/linagora/twake-on-matrix/issues/1963
- #1982 
Search keywork did not include matrix id. Also the `!` without checking first if the thing is null or not throwed some errors which blocked the search.
Add matrix id matchers
Check if value is null, if it is return a boolean as default value.
- Web:
- Chrome
[Capture vidéo du 25-07-2024 21:24:31.webm](https://github.com/user-attachments/assets/02b55b38-df68-49b9-8ff5-c0232ae7874c)
- Android:
https://github.com/user-attachments/assets/a96bd246-4005-4543-94fb-2e06200e61d0 …

TW-1963: update search keyword matching

---

lib/pages/chat_list/receive_sharing_intent_mixin.dart
lib/utils/background_push.dart
lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body.dart
lib/widgets/layouts/agruments/app_adaptive_scaffold_body_args.dart
lib/widgets/layouts/agruments/receive_content_args.dart
lib/widgets/twake_app.dart

- #1878 
- Side effect when use `GoRouter` and `Navigation`
- Web:
- Android:
https://github.com/user-attachments/assets/da8b341d-8866-4163-907d-d4bc45999e75
- IOS:

TW-1878: Fix can't open notification when open Media in chat details

---

assets/l10n/intl_en.arb
assets/l10n/intl_fr.arb
lib/pages/chat/chat_app_bar_title.dart
lib/presentation/mixins/common_media_picker_mixin.dart
lib/presentation/mixins/contacts_view_controller_mixin.dart
lib/presentation/mixins/save_file_to_twake_downloads_folder_mixin.dart
lib/presentation/mixins/save_media_to_gallery_android_mixin.dart
lib/utils/permission_dialog.dart
lib/utils/permission_service.dart
lib/widgets/contacts_warning_banner/contacts_warning_banner_view.dart
lib/widgets/mixins/handle_download_and_preview_file_mixin.dart

- #2022 
- IOS:
https://github.com/user-attachments/assets/1a6f8f07-f50a-43aa-993b-0350f849fe87

TW-2022: Change explain text in permission dialog

---

lib/pages/new_private_chat/widget/contact_status_widget.dart
lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
test/pages/new_private_chat/widget/contact_status_widget_test.dart

#1996 
According to the [figma design](https://www.figma.com/design/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=25783-37873&t=2LUxJI6eCDu1cVUk-0 ) only the Not-Activated status should be kept
the activated status in contacts tab is removed
- Web:
https://github.com/user-attachments/assets/a5696b73-e888-4d16-bb37-398a85fc50c8
- Android:
[contacts_demo1.webm](https://github.com/user-attachments/assets/77994f9a-ff3a-431e-afcd-6f41bc8d32c4)
- IOS:

TW-1996-removed-activated-status-in-accounts-tab

---

android/fastlane/Fastfile

Since our app is stable, we don't need to upload as draft release in internal track any more.

Set uploaded appbundles status to completed

---

CHANGELOG.md

- #1817 Added french and russian translation in camera screen
- Set uploaded appbundles status to completed
- #1813 Change event description for pinned files
- #1980 Convert HEIC files to jpg file
- #1886 Update chat list UI part 1
- #1972 Update logic for cancel upload files with captions
- #1968 Break UI when search with keyword
- #1542 make message highlight brighter
- #1878 Fix can't open notification when open Media in chat details
- #1918 Fixed typo error in externalContactMessage
- #1994 Fix load more for chat search
- #1844 Fix distorted images when using camera in android phone
- #2001 No previews for video
- #1974 Fix cannot jump to reply
- #1982 Fix can't create direct chat when search in contact tab
- #1936 Fix the share screen don't show up when sharing an image
- #1926 …

Bump version to v2.6.4

---

lib/pages/chat/chat.dart

- This is a side effect from ticket #1998 so all the action scroll to message is a highlight. 
- In the case when open the chat with new message, jump to the last message and no need to highlight.
- Web:
https://github.com/user-attachments/assets/d5c4632d-65a9-43d7-91fb-fe762b901cb8
- IOS:
https://github.com/user-attachments/assets/983e426f-9e9f-42ba-b999-f0fd11dd6a9b

Fix wrong highlight message when open chat

---

lib/presentation/mixins/connect_page_mixin.dart
lib/utils/string_extension.dart
test/utils/string_extension_test.dart

https://github.com/user-attachments/assets/c9b49668-85f1-4909-9fe3-f1776ddbd6a9
https://github.com/user-attachments/assets/339ff24c-932e-47cc-a44c-b2a47f88d566
- Stg env
https://github.com/user-attachments/assets/062991f9-d6ae-4e0c-bdb2-6e54cfe5351b
- Dev env
https://github.com/user-attachments/assets/efa5c14c-6d9a-4c8d-847a-10f2d09d3db2
- Linagora env
https://github.com/user-attachments/assets/be8bc693-1138-47ff-b5bc-7c16a4424786
- Matrix env
https://github.com/user-attachments/assets/0c9a324f-2e63-401e-9a7a-d157878c2375

Fix location path on web

---

Dockerfile
configurations/nginx.conf.template

Use `TWAKECHAT_LISTEN_PORT` at run to customize:
```bash
docker run -p <your port>:<your port> -e TWAKECHAT_LISTEN_PORT=<your port> ...
```
cc @nqhhdev

Added support for nginx port customization

---

lib/pages/forward/forward_view.dart

- #2064 
- In this screen on web, using `Navigation` to open forward screen, however when click on button cancel using `go_router` so can't close this screen.
- Use `Navigation` when click on cancel button
- Web:
https://github.com/user-attachments/assets/2487f363-bbd0-4fe6-8d18-34dc715eec84
- Mobile:
https://github.com/user-attachments/assets/b1694df7-2e43-4345-8e93-ed84c871faed

TW-2064: Fix cancel button in forward screen on web

---

pubspec.lock
pubspec.yaml

- https://github.com/linagora/matrix-dart-sdk/pull/65
- #1950 
- Enable all extensions in `markdown`
- Disable `InlineLatexSyntax ` extension in `markdown`
https://github.com/user-attachments/assets/30be2b5f-69ee-4c2c-a8fd-23096a9d6fb0
https://github.com/user-attachments/assets/ea4b8fd0-ba45-4e65-a7ea-37030bb10187
https://github.com/user-attachments/assets/5c398003-6c89-44c3-a463-ab88db945b3a

TW-1950: Update markdown when send message in chat

---

assets/l10n/intl_en.arb
lib/pages/settings_dashboard/settings/settings.dart
lib/utils/dialog/twake_dialog.dart
lib/widgets/twake_components/twake_text_button.dart

- #1942 
- Update style of logout confirm dialog follow new design.
- Open a dialog and test for: Adaptive, buttons function in all platforms.
- Web:
https://github.com/user-attachments/assets/eec15a99-3492-40a6-8bdb-8ef12230dce5
- Android:
- IOS:

TW-1942: Change the design of log out dialog

---

CHANGELOG.md
pubspec.yaml

- Fix cancel button in forward screen on web
- #2075 Fix upload avatar on web
- #2067 Fix location path on web
- Fix wrong highlight message when open chat
- #2039 Update readme with customized homeserver
- #2077 Update markdown when send message in chat
- #2057 Update contacts screen ui
- #2086 Change texts in settings screen
- #2082 Update composer UI
- Added support for nginx port customization
- Added support for base href customization
- #2040 Update settings UI

Bump version to `v2.6.6`

---

lib/pages/new_group/new_group_chat_info.dart
lib/utils/power_level_manager.dart
test/utils/power_level_manager_test.dart

#2018 
only the admin can :
-Change group chat avatar
-Change name of the group chat
-Change group chat description
-Add members
-Remove members
https://github.com/user-attachments/assets/f6145003-4935-4a77-9b8d-021a13a81245

TW-2018 Changed power levels in group chats

---

lib/config/app_config.dart
lib/pages/chat/events/message/message_content_builder_mixin.dart

- #2113 
- Wrong padding message
- Web:
https://github.com/user-attachments/assets/1cff1e06-d373-46b7-8ff8-0791043b2943
- Mobile:

TW-2113: Fix text message overlaps time stamp in message bubble

---

lib/presentation/mixins/connect_page_mixin.dart
lib/utils/string_extension.dart
test/utils/string_extension_test.dart

- #2124 
- Side effect #2092 
- Web
https://github.com/user-attachments/assets/a7aa7fed-75fe-40c2-a3d1-d021eff98541
- Mobile
https://github.com/user-attachments/assets/1f962c59-cbd4-4a53-bd8b-2eb8c146f247

TW-2124: Fixed wrong url when using logout

---

assets/l10n/intl_en.arb
lib/pages/chat/chat_context_menu_actions.dart
lib/pages/chat/events/html_message.dart
lib/pages/chat/phone_number_context_menu_actions.dart
lib/presentation/mixins/linkify_mixin.dart
lib/utils/url_launcher.dart
lib/widgets/twake_components/twake_preview_link/twake_link_preview.dart
pubspec.lock
pubspec.yaml

- #2114 
- https://github.com/linagora/flutter_matrix_html/pull/19
- https://github.com/nqhhdev/linkfy_text/pull/1
- Web:
- Android:
- IOS:

TW-2114: Display phone number as a clickable in message bubble

---

lib/pages/chat/chat.dart

- #2065 
save to gallery button available only on mobile
- Web:
https://github.com/user-attachments/assets/99b0518a-71e1-4af4-8d8d-4c6c9ca835d0
- Android:
https://github.com/user-attachments/assets/d1725017-348c-4ff1-8ccd-b11357b5e83f
- IOS:

TW-2065 remove save to gallery button in web

---

assets/l10n/intl_en.arb
lib/di/global/get_it_initializer.dart
lib/domain/app_state/validator/verify_name_view_state.dart
lib/domain/exception/verify_name_exception.dart
lib/domain/model/extensions/list_validator_extension.dart
lib/domain/model/extensions/validator_failure_extension.dart
lib/domain/model/verification/composite_name_validator.dart
lib/domain/model/verification/empty_name_validator.dart
lib/domain/model/verification/name_with_space_only_validator.dart
lib/domain/model/verification/new_name_request.dart
lib/domain/model/verification/validator.dart
lib/domain/usecase/verify_name_interactor.dart
lib/pages/chat_details/chat_details_edit.dart
lib/pages/chat_details/chat_details_edit_view.dart
lib/pages/new_group/new_group_chat_info.dart
lib/pages/new_group/new_group_chat_info_view.dart
lib/pages/new_group/new_group_info_controller.dart
test/domain/model/verification/composite_name_validator_test.dart
test/domain/usecase/verify_name_interactor_test.dart

- #2046 
Added validation for group name
- Web:
https://github.com/user-attachments/assets/2cf86cf2-187a-47ab-b7f4-a24f003a4a71
- Android:
- IOS:

Tw 2046 group name validation

---

CHANGELOG.md
lib/config/config_saas/config_saas.dart
pubspec.yaml

- #2099 Fix design review v2.6.7
- #2018 Changed power levels in group chats
- #2122 Fix group information disappeared
- #2113 Fix text message overlaps time stamp in message bubble
- #2124 Fixed wrong url when using logout
- #1849 Fix bug weird grey counter sometimes appears
- #2068 Fix can't see message after accept invitation
- #2065 Remove save to gallery button in web
- #2114 Display phone number as a clickable in message bubble
- #2128 Implement QR code to download app
- #2088 Systemize app bar
- Improve style for error dialog (#2136)
- #2046 Add Group name validation

Bump v2.6.9

---

lib/pages/chat/chat_input_row.dart
lib/pages/chat/chat_input_row_send_btn.dart
lib/pages/chat/chat_input_row_style.dart
lib/pages/chat/chat_view_body.dart
lib/pages/chat_adaptive_scaffold/chat_adaptive_scaffold.dart
lib/pages/chat_draft/draft_chat_input_row.dart
lib/pages/chat_draft/draft_chat_input_row_style.dart
lib/pages/chat_draft/draft_chat_view.dart
lib/utils/dialog/twake_dialog.dart
pubspec.lock
pubspec.yaml

https://github.com/linagora/future-loading-dialog/pull/4
- Web:
https://github.com/user-attachments/assets/041522ee-ba92-4e95-b6d5-9a0d8fe837f0
- Mobile
https://github.com/user-attachments/assets/3f59abff-7996-4cf2-abb4-b36c36e532cc
https://github.com/user-attachments/assets/a1a90d37-adf6-4d39-81e6-84f8e4d87315

Update width button dialog

---

lib/pages/chat_details/chat_details_edit.dart

- #2150
- side effect from  #2119 
The initial value for `isValidGroupNameNotifier` is set to false as a result  the button is not displayed when you only change the avatar
https://github.com/user-attachments/assets/9b32e9f3-4a63-4920-a460-051798e4ee3d
- Web:
https://github.com/user-attachments/assets/da0404ee-ef59-4414-96b8-b2233db72c4f
- Android:
- IOS:

TW-2150 fix confirm button not displaying when changing group avatar

---

lib/presentation/mixins/chat_list_item_mixin.dart
test/mixin/chat/chat_list_item_mixin_test.dart

- #2157 
- #2154
- Side effect from PR #2134 
- Missing conditions for mark unread
- Web:
https://github.com/user-attachments/assets/1ce3a464-70bc-4859-920c-94bc9d831a2c
- Android:
- IOS:

TW-2157: Fix can't mark a chat as unread

---

CHANGELOG.md
pubspec.yaml

- Fixed issue when packaging linux
- Update width button dialog
- Update input bar for draft chat and chat
- Update send button for draft chat
- #2150 Fix confirm button not displaying when changing group avatar
- #2157 Fix can't mark a chat as unread
- #2154 Fix no counter of unread messages for muted chats
- #1927 Change animation for Search screen for mobile

Bump version to v2.6.11

---

config.sample.json
docs/configurations/config_web_app_for_public_platform.md
lib/config/app_config.dart
pubspec.lock

- https://github.com/linagora/dart_matrix_api_lite/pull/4

Support enable logs

---

lib/widgets/stream_image_view.dart

- #2163 
- When using `Image` with property is `fit: BoxFit.contain` As large as possible while still containing the source entirely within the target box.
- https://flutter.github.io/assets-for-api-docs/assets/painting/box_fit_contain.png
- Change property to `fit: BoxFit.cover` As small as possible while still covering the entire target box.
- https://flutter.github.io/assets-for-api-docs/assets/painting/box_fit_cover.png
- Web:
https://github.com/user-attachments/assets/18c197a9-3909-4499-ad50-5cb5428b11cf
- Mobile:
https://github.com/user-attachments/assets/18ec2f2c-159a-4f09-b1f2-27c9252a169c

TW-2163: Fix avatar cut off when change new image

---

assets/l10n/intl_en.arb
lib/pages/chat/chat_actions.dart
lib/pages/chat/chat_actions_style.dart
lib/pages/chat/item_actions_bottom_widget.dart
lib/pages/chat/send_file_dialog/send_file_dialog_style.dart
lib/presentation/mixins/media_picker_mixin.dart
lib/presentation/style/media_picker_style.dart
pubspec.lock
pubspec.yaml

- #1846 
- [Figma](https://www.figma.com/design/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=27748-127572&node-type=canvas&t=sPZToiwwUHMATNc7-0)
- https://github.com/linagora/linagora-design-flutter/pull/53
Design update for image picker
- Web:
- Android:
- IOS:

Tw 1846 update style of image picker

---

lib/pages/chat/events/message/message.dart
lib/pages/chat/events/message/message_content_builder.dart
lib/pages/chat/events/message/message_content_with_timestamp_builder.dart
lib/presentation/mixins/message_avatar_mixin.dart
lib/utils/matrix_sdk_extensions/event_extension.dart
pubspec.lock
test/mixin/message_avatar_mixin_test.dart

- #2169 
Added avatar and username for sent messages/images inside a chat
- https://github.com/linagora/matrix-dart-sdk/pull/70
- Web:
- Android:
- IOS:

TW-2169 added avatar and name for sender messages in web

---

lib/config/app_config.dart
lib/presentation/mixins/pick_avatar_mixin.dart

- #2100 
- Only supported for image type `png`  `jpg`  `jpeg`   `jfif` when picking new avatar on web
- Refer Telegram web
- Web:
https://github.com/user-attachments/assets/f72755f3-0132-4ccf-b804-c64991adc423
https://github.com/user-attachments/assets/f96b89e4-f0f5-44e1-811e-515a5c00ccc6
https://github.com/user-attachments/assets/97775313-3bf4-4149-95dc-0e1635b2c5a5

TW-2100: Update image type supported when picking new avatar

---

lib/domain/app_state/settings/update_profile_success.dart
lib/domain/usecase/settings/update_profile_interactor.dart
lib/pages/settings_dashboard/settings_profile/settings_profile.dart
lib/presentation/model/pick_avatar_state.dart

- #2112 
- Web:
https://github.com/user-attachments/assets/af6c74c8-472d-4eb1-ad00-5a5912dfe019
- IOS:
https://github.com/user-attachments/assets/586fe42c-da7e-4fa8-9a27-2a5bf302ceb7

TW-2112: Fix bug Remove profile picture / avatar doesn't work

---

lib/pages/new_group/widget/contacts_selection_list.dart

- #2106 
verify if we dont have any matching contacts displayed before showing external search widget
- Web:
- Android
https://github.com/user-attachments/assets/6151562d-3811-4d9e-a8b3-96655e89b8cc
- IOS:

TW-2106 Fix duplicate result when adding member with mxid

---

docs/adr/0025-improve-tag-suggesstion-and-dispay-members-in-group-chat-detail.md
lib/pages/chat/chat.dart
lib/pages/chat_details/chat_details_page_view/chat_details_members_page.dart
lib/presentation/mixins/chat_details_tab_mixin.dart
pubspec.lock
pubspec.yaml

- #2165 
- https://github.com/linagora/matrix-dart-sdk/pull/71
- Web:
https://github.com/user-attachments/assets/119f2c8d-f788-47c9-8578-1819dc639c5f
https://github.com/user-attachments/assets/3c85a3ee-0f7d-453f-bd97-54427628c1ef

TW-2165: Improve tag suggestion with members in room

---

CHANGELOG.md
pubspec.yaml

- #2152 Fix full-word search for unencrypted messages isn't performed until you put a space after the word
- #2111 Fix replies do not appear in search results.
- #2112 Fix bug Remove profile picture / avatar doesn't work
- #2106 Fix duplicate result when adding member with mxid
- #2165 Improve tag suggestion in chat
- Upgrade gradle to `Xmx4096m`
- #2100 Update image type supported when picking new avatar
- #2151 Support enable/disable context menu Browser
- #2144 Update search result list item
- Update new link support page - [TWP-217](https://github.com/linagora/twake-workplace-private/issues/217) 
- #2169 Added avatar and name for sender messages in web
- Added widget test for message_avatar_mixin
- #2151 Add a toast message when copying a phone number

Bump version to v2.6.15

---

lib/pages/chat_details/chat_details_edit.dart
lib/pages/chat_details/chat_details_edit_view.dart
lib/pages/settings_dashboard/settings_profile/settings_profile.dart

- Related #2112 
- Missing state when deleting avatar in chat details edit
https://github.com/user-attachments/assets/83015d4e-a261-4597-8bb6-482b7af03d29
https://github.com/user-attachments/assets/76e7d812-f548-4a64-bd8e-924be943f8e7
https://github.com/user-attachments/assets/37d47350-a17e-47e3-ad55-2f3f0d38f41c
https://github.com/user-attachments/assets/2108e28c-f61a-4013-9d8d-f0844626859e
https://github.com/user-attachments/assets/2a79861c-38e8-458e-8fcd-0f16bf5686d9

Hotfix: Missing state when deleting avatar in chat details edit

---

CHANGELOG.md
pubspec.yaml

- Hotfix: Missing state when deleting avatar in chat details edit
- Downgrade ruby to fix building mobile app

Bump version to v2.6.16

---

lib/pages/chat_list/receive_sharing_intent_mixin.dart

- #2214
- Open the share screen 2 times
- Wrong when using context 
- Web:
- Android:
- IOS:

TW-2214: Fix Wrong behaviour when sharing a file from other app to Twake

---

CHANGELOG.md
pubspec.yaml

- [Encryption] Fix timeout for first sync
- [Encryption] Change log level to verbose when enable log
- [Encryption] Remove timeout for loading dialog
- #2215 Fix cannot preview share media

Bump v2.6.18

---

lib/pages/settings_dashboard/settings/settings.dart

- logout in Twake maybe not success if logout_redirect not success
- upload message key in sync event is not success
- upload key first, before loging out
- handle auto upload key in every sync, but not process if before task not completed.

[Encrypted] Try to upload key to server before logout

---

analysis_options.yaml
lib/pages/chat/chat_event_list.dart
lib/pages/forward/forward_view.dart
lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
lib/utils/matrix_sdk_extensions/download_file_extension.dart
lib/utils/matrix_sdk_extensions/matrix_file_extension.dart
lib/widgets/mxc_image.dart
pubspec.lock
test/utils/matrix_sdk_extensions/matrix_file_extension_test.dart

- thumbnail information wrong, but app put the video into preview image for this video
- media uri API endpoint deprecated from spec v1.11 
https://github.com/user-attachments/assets/791abd46-c451-489f-80c2-271dcb588e7f

Fix crash when video display in chat with wrong thumbnail information

---

lib/presentation/mixins/connect_page_mixin.dart

Cannot log out on the web when using LemonLDAP as SSO
LemonLDAP does not accept the `url` parameter if the host is not configured in the vhosts or is not an HTTP URL.
removes the `url` parameter from SSO logout

🐛 fix SSO logout for web

---

lib/pages/chat/chat.dart

- #2402 
Setting `html.window.location.href = newLocation;` 
- In a Flutter web app causes a full page reload (hard navigation), because it instructs the browser to navigate to a new URL, reloading the entire app
- Remove old logic and use the `replaceState()` method of the [History](https://developer.mozilla.org/en-US/docs/Web/API/History) interface modifies the current history entry, replacing it with the state object and URL passed in the method parameters. This method is particularly useful when you want to update the state object or URL of the current history entry in response to some user action.
- Web:
https://github.com/user-attachments/assets/15d9b6e2-9b83-4b13-81bd-2089d27e41f3

TW-2402: Automatically jump to the latest message after go to search result

---

lib/presentation/mixins/chat_details_tab_mixin.dart

https://github.com/user-attachments/assets/1a92c32f-10b5-4034-b79b-a5c64858cb41
- Improper handling when click load more after adding member to group chat
https://github.com/user-attachments/assets/97f2bf8e-abd1-488e-ad8f-fd8006f85c5b

HOTFIX Duplicate member on load more

---

assets/l10n/intl_fr.arb

"Ne pas lire" does not explain correctly what the button is doing.

Update french wording
