linagora/twake-on-matrix

.github/workflows/build.yaml
Run on PR merge, PR opened on `refactor/ui` or manually
=> Run build workflow on UI refactor branch

.github/workflows/gh-pages.yaml, config.sample.json, web/index.html
Triggered on pushes to `main` and `refactor/ui` branch.
Can be accessed at https://twakematrix-on-commit.twake.app
Need to configure branch protection in the settings.
=> Added GitHub pages deployment

.github/workflows/gh-pages.yaml, config.sample.json
Accessable at https://twakematrix-on-commit.twake.app/web
=> Changed Twake deployment to `web` subpath

lib/pages/chat/chat_view.dart, lib/pages/chat/events/image_bubble.dart, lib/pages/chat/events/message.dart, lib/pages/chat/events/message/message_style.dart, lib/pages/chat/events/message_time.dart, lib/pages/chat/events/reply_content.dart, lib/pages/chat/seen_by_row.dart, lib/widgets/mxc_image.dart
https://user-images.githubusercontent.com/107173849/229983790-cdc548c3-ea8b-4658-b3a2-1f57d70fec71.mov
=> fix some bug of chat content

PRIVACY.md, android/app/build.gradle, android/app/src/profile/AndroidManifest.xml, android/fastlane/Appfile
=> Change appId for Android

lib/data/datasource/tom_configurations_datasource.dart, lib/data/datasource_impl/tom_configurations_datasource_impl.dart, lib/data/hive/dto/tom_configurations_hive_obj.dart, lib/data/hive/dto/tom_server_information_hive_obj.dart, lib/data/hive/hive_collection_tom_database.dart, lib/data/hive/hive_constants.dart, lib/data/repository/tom_configurations_repository_impl.dart, lib/di/abstract_di.dart, lib/di/base_di.dart, lib/di/global/configuration/tom_configuration_di.dart, lib/di/global/get_it_initializer.dart, lib/di/global/hive_di.dart, lib/domain/exception/tom_configuration_not_found.dart, lib/domain/model/extensions/homeserver_summary_extensions.dart, lib/domain/model/tom_configurations.dart, lib/domain/model/tom_server_information.dart, lib/domain/repository/tom_configurations_repository.dart, lib/utils/matrix_sdk_extensions/flutter_hive_collections_database.dart, lib/widgets/matrix.dart, pubspec.lock, pubspec.yaml
=> Store configuration

lib/pages/chat/events/html_message.dart, lib/pages/chat/events/message.dart, lib/pages/chat/events/message/message_style.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/message_content_style.dart, lib/pages/chat/events/message_reactions.dart, lib/pages/chat/events/message_reactions_style.dart, lib/pages/chat/events/message_time.dart, lib/pages/chat/events/message_time_style.dart, lib/pages/chat/seen_by_row.dart, lib/widgets/twake_link_text.dart, pubspec.lock, pubspec.yaml
https://github.com/linagora/twake-on-matrix/assets/43041967/500b1318-681c-4fae-963c-584a99ac19bc
=> Apply m3 to chat bubble

assets/l10n/intl_en.arb, lib/config/routes.dart, lib/domain/usecase/fetch_contacts_interactor.dart, lib/pages/contacts/di/contact_di.dart, lib/pages/new_group/new_group.dart, lib/pages/new_group/new_group_view.dart, lib/pages/new_group/widget/contacts_selection_list.dart, lib/pages/new_group/widget/selected_participants_list.dart, lib/pages/new_private_chat/fetch_contacts_controller.dart, lib/pages/new_private_chat/new_private_chat.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/new_private_chat/search_contacts_controller.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart, lib/pages/new_private_chat/widget/expansion_list.dart, lib/pages/new_private_chat/widget/search_contact_appbar.dart, lib/widgets/avatar/avatar_with_bottom_icon_widget.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/1178e463-45d2-4025-a2fd-9b86e0107d69
=> Tf-98/multiple selections contact picker

lib/pages/chat/events/state_message.dart
=> TW-113: apply new style for chat event

lib/pages/chat/chat.dart
=> TW-111 scroll down after sending a message

lib/pages/chat/chat_view.dart, lib/pages/chat_list/chat_list_item.dart, lib/utils/string_extension.dart, lib/widgets/unread_rooms_badge.dart
- Adds up notifications count instead of number of unread rooms 
- Change the color of invite badge
=> feat: adds up notification in room

lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_body.dart, lib/pages/chat_list/client_chooser_button.dart, lib/pages/chat_list/home_screen.dart, lib/widgets/mxc_image.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/41e3ea4e-92b1-4dc8-9f3b-f618b8b44409
=> TW-105: avoid blink in avtar and name

lib/pages/chat/chat_app_bar_title.dart, lib/widgets/twake_components/twake_loading/twake_loading_indicator.dart
- Add No Connection on app bar 
- Change typing animation
This is related to #102
=> TW-102 - App Bar Style Offline & Typing

lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_body.dart, lib/pages/forward/forward.dart, lib/pages/forward/forward_view.dart
- Issue: Can't display Groups chat in Chat List and Forward screen
- Resolved: Update filter for all chats
https://github.com/linagora/twake-on-matrix/assets/99852347/ea7634e4-9238-434c-874c-bae96c5dbbfd
=> Hot fix can't display Groups chat in Chat List and Forward screen

analysis_options.yaml, assets/l10n/intl_en.arb, lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/events/message.dart, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_body.dart, lib/pages/forward/forward.dart, lib/pages/forward/forward_item.dart, lib/pages/forward/forward_item_style.dart, lib/pages/forward/forward_view.dart, lib/pages/forward/forward_view_style.dart, lib/pages/forward/search_forward_controller.dart
- Issue : #133 
- Resolved: 
`IOS`
https://github.com/linagora/twake-on-matrix/assets/99852347/bc0ce5eb-d547-45c0-b780-6463362e65c0
`ANDROID`
[device-2023-06-08-165156.webm](https://github.com/linagora/twake-on-matrix/assets/99852347/e850912d-9423-4458-bbcf-d0d55233507c)
- Hide ReactionsPicker and Only select one message
https://github.com/linagora/twake-on-matrix/assets/99852347/15ce940c-9f81-4743-bd18-0e5f67a04163
- Forward Image: 
https://github.com/linagora/twake-on-matrix/assets/99852347/4aee0223-bd04-452b-931d-4e6683a124e9
=> TW-133: Forward a single text message to existed chat

lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/forward/forward.dart, lib/pages/forward/forward_view.dart, lib/widgets/matrix.dart
- Issue: #149 
- Resolved: 
- Support forward multi message (Image, text)
`Sender`
https://github.com/linagora/twake-on-matrix/assets/99852347/e1c2b3e1-a413-4c63-abab-3eee7901c2bf
`Receiver`
https://github.com/linagora/twake-on-matrix/assets/99852347/861e867b-bc09-41bd-9c22-887981936060
=> TW-149: Forward multi text message to a existed chat

lib/domain/model/extensions/contact/contact_extension.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
=> TW-129 : feat: add avatar on contact tab

assets/l10n/intl_en.arb, lib/di/global/get_it_initializer.dart, lib/di/global/network_connectivity_di.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_app_bar_title.dart, lib/utils/network_connection_service.dart, lib/widgets/fluffy_chat_app.dart
- Add Network Connectivity Service
- Update rich presence status badge according to connection
- Update app bar status bar according to connection
=> feat: add No Connection feature on app bar

pubspec.lock
- Support Draggable scrollable for bottom sheet
https://github.com/linagora/twake-on-matrix/assets/99852347/cd4d8534-ee81-4515-b76a-ff3900091192
=> Support Draggable scrollable for bottom sheet

lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/events/message.dart, lib/pages/chat/events/message_content.dart, lib/pages/forward/forward.dart, lib/pages/forward/forward_view.dart, lib/widgets/matrix.dart, pubspec.lock
- Issue: 
```late List<Map<String, dynamic>?> _shareContentList;```
- In your case, the error is happening because the _shareContentList variable is declared with late and has not been initialized before it is accessed in the shareContentList getter. 
- Resolved:
- To fix this error, you need to initialize _shareContentList before accessing it. When we use `shareContentList` should be checked is not null
- Update bottom forward when select contact in `ForwardView`
```
List<Map<String, dynamic>?> get shareContentList => _shareContentList ?? [];
set shareContentList(List<Map<String, dynamic>?> content) {
_shareContentList = content;
onShareContentChanged.add(_shareContent);
}
List<Map<String, dynamic>?>? _shareContentList;
```
https://github.com/linagora/twake-on-matrix/assets/99852347/a5b92 …
=> Hot fix can't forward message

lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
- Case `Successfuly`
https://github.com/linagora/twake-on-matrix/assets/99852347/339d6f68-8035-4069-9005-3401bf476992
- Case `Failure`
https://github.com/linagora/twake-on-matrix/assets/99852347/e9c793ca-cbb5-47a9-9940-324022878e93
- Case `Error`
https://github.com/linagora/twake-on-matrix/assets/99852347/1c3aa06e-feae-4f13-b5a8-af33b6e540c9
=> Support get profile with ExpansionContactListTile

assets/l10n/intl_en.arb, lib/config/routes.dart, lib/pages/new_group/new_group.dart, lib/pages/new_group/new_group_chat_info.dart, lib/pages/new_group/new_group_info_controller.dart, lib/pages/new_group/widget/expansion_participants_list.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/09eaad0c-dd78-4cec-aee4-1d73b5fcb43e
https://github.com/linagora/twake-on-matrix/assets/43041967/5aed6090-3c35-4579-9d9e-5405819114e5
=> Improve various UX/UI in Create group chat

lib/pages/chat_encryption_settings/chat_encryption_settings_view.dart, lib/pages/homeserver_picker/homeserver_bottom_sheet.dart, lib/pages/homeserver_picker/homeserver_picker_view.dart, lib/pages/settings/settings_view.dart, lib/utils/platform_infos.dart, lib/utils/uia_request_manager.dart, lib/utils/url_launcher.dart, lib/widgets/matrix.dart, pubspec.lock, pubspec.yaml
https://github.com/linagora/twake-on-matrix/assets/43041967/6eb650ec-7383-4a61-99b4-ad26cbdb2246
=> fix-bug: temp change browser when open link in app in Android

lib/pages/chat/events/message_content.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/2c4d27fa-fc27-48ec-b736-c2710f45ec41
=> hot-fix/unable-to-tap-link-message

.gitignore, lib/config/app_config.dart, lib/data/datasource/recovery_words_data_source.dart, lib/data/datasource_impl/recovery_words_data_source_impl.dart, lib/data/model/recovery_words_json.dart, lib/data/network/recovery_words/recovery_words_api.dart, lib/data/network/tom_endpoint.dart, lib/data/repository/recovery_words_repository_impl.dart, lib/di/global/get_it_initializer.dart, lib/di/global/network_di.dart, lib/di/presentation/recovery_words_di.dart, lib/domain/app_state/recovery_words/get_recovery_words_failed.dart, lib/domain/app_state/recovery_words/get_recovery_words_success.dart, lib/domain/app_state/recovery_words/save_recovery_words_failed.dart, lib/domain/app_state/recovery_words/save_recovery_words_success.dart, lib/domain/model/recovery_words/recovery_words.dart, lib/domain/repository/recovery_words_repository.dart, lib/domain/usecases/get_recovery_words_interactor.dart, lib/domain/usecases/save_recovery_words_interactor.dart, lib/pages/bootstrap/tom_bootstrap_dialog.dart, lib/pages/chat_list/chat_list.dart
https://github.com/linagora/twake-on-matrix/assets/6462404/44afc5c2-6129-4821-b2c4-f1712447dc24
=> Integrate recovery vault

lib/config/routes.dart, lib/pages/new_group/new_group.dart, lib/pages/new_group/widget/selected_participants_list.dart, lib/pages/new_private_chat/search_contacts_controller.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart, lib/pages/new_private_chat/widget/search_contact_appbar.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/859efe62-b6ed-4873-8237-c8a89c73a4b4
=> improve UX in create group chat

lib/config/routes.dart, lib/widgets/mxc_image.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/69979a2e-31bc-43d5-8222-6eed044dde0b
=> Hot fix/mxc image is not clickable

.github/workflows/build.yaml
Also enable notifications in Settings > Notifications:
=> Build debug version at 17:30 everyday

.github/workflows/build.yaml
Now builds at 18:00 Vietnamese time.
=> Correct time to match timezone

.github/workflows/gh-pages.yaml
Switched to a new domain: https://beta.twake.app/web
=> Deploy Page on tag pushes

docs/adr/0003-improve-for-load-image-first-time.md, lib/config/themes.dart, lib/pages/chat/events/image_bubble.dart, lib/pages/chat/events/message_content.dart, lib/widgets/mxc_image.dart
- Issue: #220 
- Resolved:
https://github.com/linagora/twake-on-matrix/assets/99852347/da687d51-55f7-4dc8-8cba-f96db11f4f1e
=> TW-220: Improve for load image first time and keep image when scrolling

lib/config/app_config.dart, lib/pages/chat/events/message_content.dart
=> fix: edit message font size

lib/data/datasource/tom_contacts_datasource.dart, lib/data/datasource_impl/contact/tom_contacts_datasource_impl.dart, lib/data/network/contact/tom_contact_api.dart, lib/data/repository/contact/tom_contact_repository_impl.dart, lib/di/contact/contact_di.dart, lib/domain/app_state/contact/get_network_contact_success.dart, lib/domain/model/contact/lookup_mxid_request.dart, lib/domain/model/extensions/contact/contact_extension.dart, lib/domain/repository/contact_repository.dart, lib/domain/usecase/load_more_internal_contacts.dart, lib/pages/new_group/new_group.dart, lib/pages/new_group/new_group_view.dart, lib/pages/new_group/selected_contacts_map_change_notiifer.dart, lib/pages/new_group/widget/contacts_selection_list.dart, lib/pages/new_group/widget/selected_participants_list.dart, lib/pages/new_private_chat/fetch_contacts_controller.dart, lib/pages/new_private_chat/new_private_chat.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/new_private_chat/widget/expansion_list.dart, lib/presentation/mixin/load_more_contacts_mixin.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/7c24ca85-1604-455b-a711-924444b63907
https://github.com/linagora/twake-on-matrix/assets/43041967/26331ebd-dae5-485a-bbd0-a3c5179e1875
=> TW-192 Load more contact for Contact tab

lib/pages/chat/events/html_message.dart, lib/pages/chat/events/message_content.dart, lib/utils/string_extension.dart, lib/widgets/clean_rich_text.dart, lib/widgets/twake_components/twake_preview_link.dart, lib/widgets/twake_link_text.dart, pubspec.lock, pubspec.yaml
- Previewing the first valid link 
Example : If there are 2 links and the first one is not working, it will preview the second one
This Closes #163
=> feat: add preview link

lib/pages/chat/chat_event_list.dart
- Issue: #202 
- Resolved:
- Fix overflow for `DirectChatEmptyView` and `GroupChatEmptyView`
https://github.com/linagora/twake-on-matrix/assets/99852347/7031610f-a795-4ad9-b534-6ba4681fc26a
=> TW-202: Fix overflow for `DirectChatEmptyView` and `GroupChatEmptyView`

lib/pages/new_group/widget/contacts_selection_list.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart, lib/pages/new_private_chat/widget/expansion_list.dart
- Issue: #198 
- Resolved:
- `Contacts Tab`
https://github.com/linagora/twake-on-matrix/assets/99852347/046f381e-4182-44b8-a920-0d3f27ffbdaa
- `Chats Tab`
https://github.com/linagora/twake-on-matrix/assets/99852347/3fb31977-d64d-4107-b058-b9afd39005b9
=> TW-198: Fix blink blink effect in display name of contact when search in chats, contacts

lib/config/themes.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/reply_content.dart
waiting for designer reply
This Closes #239
=> fix: add font size to M3 styles

lib/pages/image_viewer/image_viewer_view.dart
=> feat: add save image button

lib/config/themes.dart
Design: https://www.figma.com/file/Cu4NB44bcURKEy40DEfwWi/Design-system-1.0?type=design&node-id=49848%3A6285&mode=design&t=X0jvzyzUSvuyjZa7-1
=> Update theme text style

lib/pages/chat_list/chat_list.dart
- shows private chat when have at least message in chat
https://github.com/linagora/twake-on-matrix/assets/43041967/ffea00bf-e643-439f-b414-b61de1da3668
- shows group chat when group chat is created
https://github.com/linagora/twake-on-matrix/assets/43041967/6aa93603-1536-4975-84e0-d6d2ce18cb81
- Event when last event is not message, it still works
https://github.com/linagora/twake-on-matrix/assets/43041967/5adae201-cdec-472b-a7f9-853d6a7a6bf7
=> TW-230/only show chat when have message

lib/pages/chat/events/html_message.dart, lib/pages/chat/events/message.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/reply_content.dart, lib/pages/chat/reply_display.dart, lib/presentation/extensions/room_extension.dart, lib/utils/matrix_sdk_extensions/event_extension.dart, lib/widgets/pill.dart, pubspec.lock, pubspec.yaml
https://github.com/linagora/twake-on-matrix/assets/43041967/ba6e1d5c-cbcc-4f32-b04b-253078acfa61
https://github.com/linagora/twake-on-matrix/assets/43041967/fe532df2-aa8a-4995-a844-71b9da934762
=> TW-245: fix-bug/remove blink-blink effect when mentions user or room

assets/l10n/intl_en.arb
=> fix: rename recent chats

lib/pages/chat/events/message.dart
=> fix: put displayed time outside of swipeable

lib/pages/chat/chat_event_list.dart, lib/pages/chat/direct_chat_empty_view.dart
Inkwell has ripple effect by default
This Closes #273
=> feat: add composer focus and ripple to empty view

lib/widgets/twake_components/twake_header.dart
=> fix: remove unused three dots button in chat list

assets/l10n/intl_en.arb
=> feat: rename chat message hint

lib/pages/chat/chat.dart, lib/pages/chat/empty_chat.dart, lib/pages/chat/empty_chat_view.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/8385ab85-3bd6-422d-a328-515d80e89fd2
=> hot-fix/fix some bugs in change UX behavior of create_private_chat

lib/data/network/contact/tom_contact_api.dart, lib/domain/model/contact/tom_contact.dart, lib/domain/model/extensions/contact/tom_contact_extension.dart
=> Change displayName in contact from identity server

lib/data/datasource_impl/tom_configurations_datasource_impl.dart, lib/data/hive/dto/tom_configurations_hive_obj.dart, lib/data/hive/dto/tom_server_information_hive_obj.dart, lib/data/hive/hive_collection_tom_database.dart, lib/pages/bootstrap/tom_bootstrap_dialog.dart, lib/pages/chat_list/chat_list.dart, lib/utils/matrix_sdk_extensions/flutter_hive_collections_database.dart, lib/widgets/matrix.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/c1e0a335-a1c9-4e16-a901-333835d2d334
=> [WIP]: Hide `TomBootstrapDialog` and config hive db for web

ios/Runner.xcodeproj/project.pbxproj, ios/Runner/AppDelegate.swift, ios/en.lproj/Localizable.strings, lib/config/app_config.dart, lib/utils/background_push.dart
=> fix: iOS push notification

lib/config/routes.dart, lib/di/forward/forward_di.dart, lib/domain/app_state/forward/forward_message_state.dart, lib/domain/usecase/forward/forward_message_interactor.dart, lib/pages/chat/chat.dart, lib/pages/forward/forward.dart, lib/pages/forward/forward_view.dart, lib/widgets/twake_components/twake_fab.dart
- Issue: #218 
- Resolved: 
https://github.com/linagora/twake-on-matrix/assets/99852347/3fe1f03a-082d-45e3-b125-54892b3f9d5a
=> TW-218: Fix double click on forward msg

lib/pages/chat/chat_input_row.dart, lib/pages/chat/events/message.dart, lib/presentation/mixin/image_picker_mixin.dart
- Issues: 
- #276 
- Can't show camera when clicking on camera icon
- Resolved :
https://github.com/linagora/twake-on-matrix/assets/99852347/85d77f0c-5321-408c-b2f7-72ae32b6a48d
=> TW-276: Remove padding when selected msg

lib/config/routes.dart, lib/di/chat/chat_di.dart, lib/di/create_direct_chat/create_direct_chat_di.dart, lib/pages/contacts_tab/contacts_appbar.dart, lib/pages/contacts_tab/contacts_tab.dart, lib/pages/new_group/new_group.dart, lib/pages/settings/settings_view.dart, lib/widgets/fluffy_chat_app.dart
- Issues: 
-  Hide change theme func in settings
-  Can't search in contacts tab
- Can't open `NewCreateGroup` screen
- Resolved:
=> Hotfix: Hide change theme func in settings

lib/pages/new_private_chat/search_contacts_controller.dart
https://github.com/linagora/twake-on-matrix/assets/6462404/2cb2dfe6-3cda-435e-b6c1-8960738e763c
=> TW-249 Auto Select search keyword after select a contact

ios/Runner/AppDelegate.swift, ios/Runner/Info.plist, lib/utils/background_push.dart, lib/utils/push_helper.dart
- #342 
- Handle notification when app in Foreground, Background and Terminated
https://github.com/linagora/twake-on-matrix/assets/12546908/d12af5f9-7689-409b-8ecd-9dae404cab8b
=> TW-342 handle notificaton on ios

lib/pages/chat_details/participant_list_item.dart, lib/pages/dialer/pip/dismiss_keyboard.dart, lib/pages/dialer/pip/pip_view.dart, lib/pages/new_group/new_group_view.dart, lib/pages/new_group/selected_contacts_map_change_notiifer.dart, lib/pages/new_group/widget/contacts_selection_list.dart, lib/pages/new_private_chat/new_private_chat_view.dart
=> TW-250: Fix dismiss keyboard on scroll in new grp view

lib/pages/search/recent_contacts_banner_widget.dart, lib/pages/search/recent_contacts_banner_widget_style.dart, lib/pages/search/recent_item_widget.dart, lib/pages/search/search_view.dart, lib/widgets/highlight_text.dart
- Issue: #346 
1. List recent contacts is empty
https://github.com/linagora/twake-on-matrix/assets/99852347/c30e7ac0-a8ca-42ba-9812-90a3122c2207
2. Searching and scrolling
https://github.com/linagora/twake-on-matrix/assets/99852347/240d8c6d-64d5-4a9d-916d-8854c97e62cf
=> TW-346: Add highlight in search

lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart
- #366 
https://github.com/linagora/twake-on-matrix/assets/12546908/dd7d84b8-91db-4cba-8e21-89e188e10d3c
https://github.com/linagora/twake-on-matrix/assets/12546908/adc06921-131b-45d7-af1e-f5cdb1fdf63c
=> TW-366 Reduce Frame rate when typing text in Chat

assets/l10n/intl_en.arb, lib/domain/app_state/room/create_new_group_chat_state.dart, lib/pages/new_group/new_group.dart, lib/pages/new_group/new_group_chat_info.dart, lib/pages/new_group/new_group_info_controller.dart
- #318 
- Display image immediately after selected from library
- Upload avatar first then create new room in series
- Improve: Disable UI while creating 
https://github.com/linagora/twake-on-matrix/assets/12546908/15049eff-8ce1-4c7f-902b-3d091f78640f
=> TW-318 [Room] Improve upload avatar when create new group

lib/pages/homeserver_picker/homeserver_picker.dart, lib/pages/homeserver_picker/homeserver_picker_view.dart, lib/pages/homeserver_picker/homeserver_state.dart
- Issue: #92 
- Resolved: 
https://github.com/linagora/twake-on-matrix/assets/99852347/2a109950-b4f9-454a-a77e-8b643a767657
https://github.com/linagora/twake-on-matrix/assets/99852347/f48cda70-9db0-471c-a559-97def1669f14
=> TW-92: Update logic and new design for set up homeserver

pubspec.lock, pubspec.yaml
Hot fix: Change import ssh for Matrix lib in pubspec.yaml
=> Hot fix: Change import ssh for Matrix lib in pubspec.yaml

lib/config/app_config.dart
- #351 
https://github.com/linagora/twake-on-matrix/assets/12546908/e5c29aef-31f4-43d0-9f9e-ca2d7bb1095f
=> TW-351 [Notification] Enable notification for iOS in both production and sandbox

pubspec.lock
- https://github.com/linagora/matrix-dart-sdk/pull/4/files
- #275
See in https://github.com/linagora/matrix-dart-sdk/pull/4/files
=> TW-275 [M1] What happen if user typing+ sending very fast a lot of message

.github/workflows/build.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml, .gitlab-ci.yml, analysis_options.yaml, docs/code_style.md, ios/Runner.xcodeproj/project.pbxproj, lib/data/network/upload_file/upload_file_api.dart, lib/pages/chat/events/html_message.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/pinned_events.dart, lib/pages/chat/send_file_dialog.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/key_verification/key_verification_dialog.dart, lib/pages/new_group/new_group_view.dart, lib/pages/settings_style/settings_style_view.dart, lib/pages/story/story_view.dart, lib/presentation/extensions/asset_entity_extension.dart, lib/utils/matrix_sdk_extensions/event_extension.dart, lib/utils/matrix_sdk_extensions/matrix_file_extension.dart, lib/utils/matrix_sdk_extensions/matrix_locals.dart, lib/utils/uia_request_manager.dart, lib/widgets/pill.dart, lib/widgets/public_room_bottom_sheet.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, scripts/code_analyze.sh, scripts/update-dependencies.sh
- https://github.com/linagora/flutter_matrix_html/pull/5
- #416
=> TW-416 Support 3.10.6

docs/adr/0004-cannot-get-current-location-and-current-context.md, lib/pages/chat_list/chat_list.dart, lib/utils/background_push.dart, lib/widgets/fluffy_chat_app.dart, lib/widgets/matrix.dart
- Issue: #418 
- Resolved:
https://github.com/linagora/twake-on-matrix/assets/99852347/53a65683-c3da-4656-80be-d199d86236f6
=> TW-418: Cannot get active room id and go to room screen with roomid

assets/l10n/intl_en.arb, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_appbar.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_appbar_style.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_shell.dart
- Issue: #421 
- Resolved:
https://github.com/linagora/twake-on-matrix/assets/99852347/9dfac3f4-ab2d-4523-8088-5a3003de4140
=> TW-421: Display appbar on Web version

lib/config/go_routes/go_router.dart, lib/pages/chat_list/client_chooser_button_style.dart, lib/utils/responsive/responsive_utils.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation_style.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_shell.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_shell_view.dart, lib/widgets/twake_components/twake_header.dart
- Issue: #425 
- Resolved:
https://github.com/linagora/twake-on-matrix/assets/99852347/058c0346-810f-4bf0-99b6-cb6d3a94e3a1
=> TW-425: Update primary navigation bar for web

android/build.gradle, lib/mixin/comparable_presentation_contact_mixin.dart, lib/mixin/comparable_presentation_search_mixin.dart, pubspec.lock, pubspec.yaml
- update `linagora_design_flutter` to latest
- update dart language to at least 3.0.0
=> Update dart lang to 3.x.x

docs/adr/0004-cannot-get-current-location-and-current-context.md, lib/utils/background_push.dart, lib/widgets/fluffy_chat_app.dart, lib/widgets/matrix.dart
Issue:
1. currently, we are using `GoRouterState` to get the current location but in class `BackgroundPush` is not a Page route, the code throws a GoError exception
2. if (settings is! Page<Object?>) {: This line checks if the settings object is an instance of the Page<Object?> class. In Flutter, a Page is a wrapper around a Route that represents a higher-level logical screen or page in your app. It's a more abstract representation that can hold information about the route's visual content and other related data.
Resolved: 
https://github.com/linagora/twake-on-matrix/assets/99852347/d5e89804-f29f-40a9-9773-ccff7901ee73
=> Fix can't receive notification

scripts/code_analyze.sh, scripts/pre-commit
=> hotfix: CI/CD should exit if have code unformatted

lib/pages/chat/chat.dart, lib/pages/chat/chat_view.dart, lib/pages/image_viewer/image_viewer.dart, lib/pages/image_viewer/image_viewer_view.dart
Issue: #405 
Root: 
- Can not write byte -> will be added on other ticket to support download to gallery 
- and not support edit message now -> disable
=> TW-405 Fix error of share action in Message selected

lib/config/go_routes/go_router.dart, lib/pages/chat/events/message.dart, lib/presentation/mixins/image_picker_mixin.dart, lib/presentation/mixins/send_files_mixin.dart, lib/widgets/swipeable.dart, pubspec.lock, pubspec.yaml
https://github.com/linagora/twake-on-matrix/assets/43041967/3a7fe338-60b9-4258-b3a6-64356e27c7c1
https://github.com/linagora/twake-on-matrix/assets/43041967/4da2b688-f63f-4f48-91e7-9e99a6ee58ea
=> TW-353: improve for the swipe

lib/domain/usecase/create_direct_chat_interactor.dart, lib/domain/usecase/forward/forward_message_interactor.dart, lib/pages/chat_draft/draft_chat.dart, lib/widgets/matrix.dart
Issue: #395 
Fixed:
https://github.com/linagora/twake-on-matrix/assets/6462404/3242a7da-cf81-46f2-b8a8-756badcbe1c0
=> TW-395 forward error

assets/l10n/intl_en.arb, lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/new_group/new_group.dart, lib/pages/new_group/new_group_view.dart, lib/pages/new_group/widget/contacts_selection_list.dart, lib/pages/new_private_chat/new_private_chat.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/new_private_chat/search_contacts_controller.dart, lib/pages/new_private_chat/widget/expansion_list.dart, lib/pages/new_private_chat/widget/external_contact_widget.dart, lib/presentation/converters/presentation_contact_converter.dart, lib/presentation/model/presentation_contact_success.dart, lib/utils/dialog/warning_dialog.dart, lib/utils/warning_dialog.dart
- #415 
https://github.com/linagora/twake-on-matrix/assets/12546908/58385c20-3070-4381-99c1-dd2ad728b209
=> TW-415 Can invite people with a matrix account to direct chat

lib/pages/chat_details/chat_details.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/invitation_selection/invitation_selection_view.dart, lib/utils/extension/build_context_extension.dart
- #415 
https://github.com/linagora/twake-on-matrix/assets/12546908/15280349-99be-446e-b1ed-4e8543e0d34d
https://github.com/linagora/twake-on-matrix/assets/12546908/5611638e-1436-4a77-86b5-f0942e51b12c
=> TW-415 Can not click on invite in Chat settings

assets/l10n/intl_en.arb, lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/dialog_accept_invite_style.dart, lib/pages/chat/dialog_accept_invite_widget.dart, lib/pages/chat_list/chat_list_item.dart
- Issue: #429 
- Resolved:
https://github.com/linagora/twake-on-matrix/assets/99852347/2168e39e-099c-40bd-97d7-85a117a2ad2b
https://github.com/linagora/twake-on-matrix/assets/99852347/0364c14e-90de-47c7-ac0e-aea58792690f
=> TW-429 can accept or decline to join in any chat

lib/utils/date_time_extension.dart
old : 
new : 
This Closes #468
=> feat: show center timestamps once per day

lib/di/global/get_it_initializer.dart, lib/domain/usecase/send_file_on_web_interactor.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/send_image_info_widget.dart, lib/presentation/extensions/send_file_web_extension.dart, lib/presentation/mixins/send_files_mixin.dart
- Issue: #423 
- Resolved: 
https://github.com/linagora/twake-on-matrix/assets/99852347/c0469a9d-344a-4fa9-b0bd-576d29e57c31
=> TW-423: Send image and file for web

lib/pages/chat/chat_app_bar_title.dart, lib/pages/chat/chat_app_bar_title_style.dart, lib/pages/chat/chat_view_style.dart, lib/pages/chat_draft/draft_chat_view.dart
design : https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=11661%3A185387&mode=dev
=> fix: update chat app bar web ui

lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart, lib/pages/search/recent_item_widget.dart, lib/presentation/extensions/search/presentation_search_extensions.dart, lib/widgets/avatar/avatar_with_bottom_icon_widget.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/8ea9ec49-8941-4ad0-8bce-a712c531a7c1
https://github.com/linagora/twake-on-matrix/assets/43041967/b45f4d47-a936-4747-ba90-ebaa16a20833
=> hot-fix: unmatch avatar in group chat

lib/pages/chat/chat_event_list.dart
=> fix: dismiss keyboard in chat list on drag

lib/pages/chat/events/image_bubble.dart, lib/widgets/twake_components/twake_preview_link.dart, lib/widgets/twake_components/twake_preview_placeholder.dart
=> fix: update preview link and image borders

.github/workflows/build.yaml, .github/workflows/release.yaml, ios/Runner/GoogleService-Info.plist, linux/packaging/appimage/make_config.yaml, macos/Gemfile, macos/Gemfile.lock, macos/Podfile.lock, macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, macos/Runner/DebugProfile.entitlements, macos/Runner/Release.entitlements, macos/fastlane/Appfile, macos/fastlane/Fastfile, macos/fastlane/Matchfile, macos/fastlane/README.md, macos/packaging/dmg/make_config.yaml, pubspec.yaml, scripts/build-linux-debug.sh, scripts/build-macos-debug.sh, scripts/build-windows-debug.sh, scripts/build-windows.ps1, scripts/build-windows.sh, scripts/package-linux-debug.sh, scripts/package-linux.sh, scripts/package-macos-debug.sh, scripts/package-macos.sh, scripts/package-windows-debug.sh, scripts/package-windows.sh, windows/packaging/exe/inno_setup.iss, windows/packaging/exe/make_config.yaml
This PR added desktop builds to our CI/CD pipeline.
Release builds are triggered when there's a new tag push. Debug builds are manually triggered or on schedule.
=> Added debug and release workflows for desktop OSes builds

lib/pages/chat_list/chat_list_header.dart, lib/pages/chat_list/chat_list_header_style.dart, lib/pages/search/search.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_view.dart
- When changing another navigator bar, color does not change
- Can't click on search item in search screen
https://github.com/linagora/twake-on-matrix/assets/99852347/3c655f13-f38a-4630-91f9-b332a411633f
=> HotFix: Cannot show highlight for botton bar

.github/workflows/tests.yaml, pubspec.lock
- https://github.com/linagora/matrix-dart-sdk/pull/10
- #473 
https://github.com/linagora/twake-on-matrix/assets/12546908/73fc3f06-2184-4d5e-a982-e6277fc65431
=> TW-473 Keep error message in exactly position of the time it is sent

lib/data/network/upload_file/file_info_extension.dart, lib/domain/usecase/send_file_interactor.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/send_image_info_widget.dart, lib/pages/chat/events/sending_image_info_widget.dart
https://github.com/linagora/matrix-dart-sdk/pull/9
https://github.com/linagora/twake-on-matrix/assets/43041967/e3ccd2d8-e989-4f38-b4ed-064a69960d61
https://github.com/linagora/twake-on-matrix/assets/43041967/e24ebf51-10bb-4096-ad6b-20dd625bcd30
=> hot-fix: fix-message-image-is-blink-in-chat

lib/pages/chat/chat.dart, pubspec.lock
- https://github.com/linagora/matrix-dart-sdk/pull/11
- #364 
https://github.com/linagora/twake-on-matrix/assets/12546908/a104bce7-e81e-4985-b20f-0389197ee7c3
=> TW-364 Resend error message

lib/pages/contacts_tab/contacts_appbar.dart, lib/pages/dialer/pip/pip_view.dart, lib/pages/new_group/selected_contacts_map_change_notifier.dart, lib/pages/search/search_view.dart, lib/widgets/app_bars/searchable_app_bar.dart
Contact 
Create group
New private 
Search
Invite
This Closes #398
=> feat: dismiss keyboard when pressing outside of textfields

lib/pages/chat/events/message.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/seen_by_row.dart
=> TW-502 [New design] Show error message

web/index.html, web/splash/style.css
- images are no more pixelated
- items are centered
This Closes #491
=> fix: align web splash

.github/workflows/gh-pages.yaml, .github/workflows/image.yaml, Dockerfile
2 images with be created: linagora/twake-web on Docker Hub and ghcr.io/linagora/twake-web on Github Container Registry.
Image tag with the latest commit is `main`.
Image tags with tagged release are `release` and `<semver>`.
=> Added Docker image builds workflow

.github/workflows/image.yaml
=> fixup: added missing $

lib/presentation/extensions/send_file_extension.dart, lib/presentation/extensions/send_file_web_extension.dart, lib/widgets/mxc_image.dart, pubspec.lock, pubspec.yaml, web/index.html
- #400 
https://github.com/linagora/twake-on-matrix/assets/12546908/f5936a6c-85a2-43e2-84fa-ee8d23a85feb
https://github.com/linagora/twake-on-matrix/assets/12546908/38bc1493-7db7-4bc2-bc26-7f923130f176
=> TW-400 Memory Improve Image message in place holder while sending image

config.sample.json, lib/config/app_config.dart, lib/pages/connect/connect_page_mixin.dart
https://github.com/linagora/twake-on-matrix/assets/6462404/b379ffd5-4924-4c2b-9a09-fee749c920f1
=> Change redirectURL to Support Build web on Github Deployment

.github/workflows/gh-pages.yaml
This should hopefully fix the redirect link.
=> Use string instead of converting to number

lib/widgets/mxc_image.dart
- #386 
https://github.com/linagora/twake-on-matrix/assets/12546908/9d24f8bf-de96-4aec-8e62-2e31125999fd
https://github.com/linagora/twake-on-matrix/assets/12546908/81edf6fd-d558-4b7c-a497-eb5b1be4cb40
=> TW-386 [View message] As an user, I want to go to the position of the message which I replied

lib/utils/extension/build_context_extension.dart
Get full width when calculate message bubble size
=> Get full width when calculate message bubble size

.github/workflows/gh-pages.yaml
Building from a tagged release instead of from HEAD
=> Pinned libolm to a specific version

android/app/src/main/AndroidManifest.xml, lib/data/datasource_impl/tom_configurations_datasource_impl.dart, lib/data/hive/dto/tom_configurations_hive_obj.dart, lib/domain/model/tom_configurations.dart, lib/pages/connect/connect_page_mixin.dart, lib/pages/login/login.dart, lib/pages/settings/settings.dart, lib/widgets/matrix.dart
- #117 
https://github.com/linagora/twake-on-matrix/assets/12546908/c96024f4-f2e5-4326-90d6-cfed724eb826
https://github.com/linagora/twake-on-matrix/assets/12546908/9f228574-5f6c-4b21-a508-c89648fcd971
https://github.com/linagora/twake-on-matrix/assets/12546908/b7e61dd7-d589-4208-ac7f-a3ec489adc5b
=> TW 117 Logout

lib/pages/chat_draft/draft_chat_view.dart
=> TW-474 : fix profile not found in draft chat view

lib/widgets/layouts/adaptive_layout/adaptive_scaffold_view.dart, lib/widgets/twake_components/twake_navigation_icon/twake_navigation_icon.dart, lib/widgets/twake_components/twake_navigation_icon/twake_navigation_icon_style.dart, lib/widgets/unread_rooms_badge.dart, pubspec.lock, pubspec.yaml
=> TW-548 : add notifications bubble to navigation chat icon

lib/pages/chat/chat_app_bar_title.dart, lib/pages/chat/chat_app_bar_title_style.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/chat_view_style.dart, lib/pages/chat/events/message.dart, lib/pages/chat/events/message/message_style.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_details/chat_details_view_style.dart, lib/pages/chat_draft/draft_chat_view.dart, lib/pages/chat_draft/draft_chat_view_style.dart, lib/pages/chat_list/chat_list_header.dart, lib/pages/chat_list/chat_list_item.dart, lib/pages/contacts_tab/contacts_appbar.dart, lib/pages/contacts_tab/contacts_tab_view.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart, lib/utils/date_time_extension.dart, lib/utils/extension/build_context_extension.dart, lib/utils/responsive/responsive_utils.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation_style.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_route.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_view.dart, lib/widgets/twake_components/twake_icon_button.dart, pubspec.lock
=> Hotfix fix UI web

lib/pages/homeserver_picker/homeserver_picker_view.dart, lib/utils/url_launcher.dart
Mobile version (no side effect)
#552
=> TW-538 : Connect page - submit no enter and fix privacy link 

lib/pages/chat/chat.dart, lib/pages/chat/chat_context_menu_actions.dart, lib/utils/matrix_sdk_extensions/matrix_file_extension.dart
=> TW-589 : support download file web

lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart
Display group chat empty
https://github.com/linagora/twake-on-matrix/assets/99852347/accb61a5-6b55-4f30-8470-d1a047235ca1
https://github.com/linagora/twake-on-matrix/assets/99852347/690ba45b-eb99-4653-b6cb-51347bf9398d
=> Hotfix: Display group chat empty

assets/l10n/intl_en.arb, lib/pages/chat/chat.dart, lib/pages/chat/chat_context_menu_actions.dart, lib/pages/image_viewer/image_viewer.dart, lib/pages/image_viewer/image_viewer_view.dart, lib/pages/settings_security/settings_security.dart, lib/utils/matrix_sdk_extensions/event_extension.dart, lib/utils/matrix_sdk_extensions/matrix_file_extension.dart, lib/utils/string_extension.dart, pubspec.lock, pubspec.yaml
- Android
- IOS
https://github.com/linagora/twake-on-matrix/assets/99852347/2d9763a7-3a76-4409-aa1b-81db99eaedfc
- WEB
=> TW-435: Save Gallery Action

lib/pages/chat/chat_input_row.dart, lib/pages/chat/chat_input_row_mobile.dart, lib/pages/chat/chat_input_row_style.dart, lib/pages/chat/chat_input_row_web.dart, lib/pages/chat_draft/draft_chat_view.dart, lib/utils/responsive/responsive_utils.dart
#562
Demo :
design : https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=11116%3A182605&mode=dev
=> TW-562 web improvements of input row

lib/pages/chat/chat.dart, lib/pages/chat/chat_emoji_picker.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/chat_input_row_mobile.dart, lib/pages/chat/chat_input_row_web.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/events/message.dart, lib/pages/chat/reactions_picker.dart, lib/utils/extension/value_notifier_extension.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
https://github.com/linagora/twake-on-matrix/assets/99852347/8c1bc403-6c45-4f3d-98d9-4f6991aee530
=> TW-594: Fix while scrolling the keyboard blinks

docs/adr/0006-dom-exception-error-when-delete-disk-for-web.md, lib/data/hive/hive_collection_tom_database.dart, lib/main.dart, lib/pages/chat/events/html_message.dart, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/receive_sharing_intent_mixin.dart, lib/pages/homeserver_picker/homeserver_picker.dart, lib/pages/invitation_selection/invitation_selection.dart, lib/pages/settings/settings.dart, lib/utils/background_push.dart, lib/utils/matrix_sdk_extensions/flutter_hive_collections_database.dart, lib/utils/uia_request_manager.dart, lib/utils/voip_plugin.dart, lib/widgets/fluffy_chat_app.dart, lib/widgets/local_notifications_extension.dart, lib/widgets/matrix.dart, lib/widgets/mixins/popup_menu_widget_mixin.dart, lib/widgets/twake_app.dart
[ADR](https://github.com/linagora/twake-on-matrix/blob/a30abd7078afbc9bc40645993fee3b4ebcc2fd91/docs/adr/0006-dom-exception-error-when-delete-disk-for-web.md)
https://github.com/linagora/twake-on-matrix/assets/99852347/d80eabe8-5cd0-471d-8c81-ae5aba02e4a3
https://github.com/linagora/twake-on-matrix/assets/99852347/48e9aab6-194e-43b0-8e67-a16b45f7396d
https://github.com/linagora/twake-on-matrix/assets/99852347/cf3e42fb-8246-4e6a-b739-3792eb6a4135
https://github.com/linagora/twake-on-matrix/assets/99852347/1f5da0ff-03b8-4c5d-93ab-aa091d288878
=> HotFix: Clear hive  database when logout 

assets/l10n/intl_en.arb, docs/adr/0006-implement-search-in-chat-room.md, lib/config/app_config.dart, lib/di/global/get_it_initializer.dart, lib/domain/app_state/room/chat_room_search_state.dart, lib/domain/usecase/room/chat_room_search_interactor.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_app_bar_title.dart, lib/pages/chat/chat_room_search_mixin.dart, lib/pages/chat/chat_search_bottom_view.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/chat_view_style.dart, lib/pages/chat/events/html_message.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat_details/chat_details.dart, lib/utils/string_extension.dart, lib/widgets/clean_rich_text.dart, lib/widgets/highlight_text.dart, lib/widgets/twake_components/twake_icon_button.dart, lib/widgets/twake_link_text.dart, pubspec.lock, pubspec.yaml, test/string_extension_test.dart
- https://github.com/Sorunome/matrix_link_text/pull/4
- https://www.notion.so/As-a-user-I-want-to-perform-search-inside-chat-89b4e3fd3cbb481cb7633bf2b81855af
https://github.com/linagora/twake-on-matrix/assets/12546908/25d77f77-1b6f-428b-943b-6901afffc17d
https://github.com/linagora/twake-on-matrix/assets/12546908/3b8dc568-fb22-4622-905c-fdd86cd1860c
https://github.com/linagora/twake-on-matrix/assets/12546908/c03c5033-8193-4442-8bfb-077d4c7df8f2
https://github.com/linagora/twake-on-matrix/assets/12546908/c6f5bce8-e7b4-461b-9cf6-ce81020e292b
https://github.com/linagora/twake-on-matrix/assets/12546908/c0fdec13-f985-4e29-97fa-1e6e7fbfac81
=> feat: Chat search

lib/pages/chat/seen_by_row.dart
=> TW-596: change delivery status logic

lib/pages/chat/input_bar.dart
#247 
https://github.com/linagora/twake-on-matrix/assets/48354990/457bd574-6257-4c7a-a146-1ff382d9324c
=> WIP : TW-247 : Improve members autocompletion input row

lib/config/app_config.dart, lib/data/network/media/media_api.dart, lib/domain/usecase/send_file_on_web_interactor.dart, lib/pages/chat_details/chat_details_page_view/media/chat_details_media_page.dart, lib/presentation/extensions/send_file_extension.dart, lib/presentation/extensions/send_file_web_extension.dart, lib/presentation/model/file/video_asset_entity.dart, lib/utils/matrix_sdk_extensions/event_extension.dart, lib/widgets/mxc_image.dart, pubspec.lock, pubspec.yaml
- #650 
- #616
- I want to upload video thumbnail and the duration
- It support only mobile for now
=> TW-616 Video thumbnail and duration

lib/widgets/video_viewer_dialog.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/b23e77c2-2228-4e0d-a2a4-6524068ecc70
=> TW-611: close video player in web

lib/pages/chat_list/chat_list.dart, lib/utils/uia_request_manager.dart, lib/widgets/twake_app.dart
https://github.com/linagora/twake-on-matrix/assets/6462404/4013d51b-aabf-4e9d-a7f4-cdc5e92f9cc0
https://github.com/linagora/twake-on-matrix/assets/6462404/a34332a7-c60b-4356-91dc-315d422fbf04
=> [Backup] Change the context to show loading dialog in web

lib/pages/chat_details/chat_details_page_view/links/chat_details_links_item.dart, lib/pages/chat_details/chat_details_page_view/links/chat_details_links_page.dart, lib/pages/chat_details/chat_details_page_view/links/chat_details_links_style.dart, lib/utils/matrix_sdk_extensions/event_extension.dart, lib/widgets/mixins/get_preview_url_mixin.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview.dart
=> TW-615 List all link of chat in chat details only mobile

lib/pages/chat/events/event_video_player.dart, lib/pages/chat/events/image_bubble.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat_details/chat_details.dart, lib/pages/chat_details/chat_details_page_view/media/chat_details_media_page.dart, lib/presentation/mixins/play_video_action_mixin.dart, lib/widgets/mxc_image.dart, lib/widgets/video_viewer_dialog.dart
- #616 
https://github.com/linagora/twake-on-matrix/assets/12546908/de6ad356-d1f4-4bcc-a357-b71639400427
https://github.com/linagora/twake-on-matrix/assets/12546908/2ec614a6-d0e8-48d5-8e76-b7ca6c2f2ec1
=> TW-616 Video player for media page

lib/config/go_routes/go_router.dart, lib/domain/app_state/room/create_new_group_chat_state.dart, lib/domain/usecase/room/create_new_group_chat_interactor.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_app_bar_title.dart, lib/pages/chat/chat_view.dart, lib/pages/chat_draft/draft_chat.dart, lib/pages/new_group/new_group.dart, pubspec.lock
demo with throttling (slow connection)
https://github.com/linagora/twake-on-matrix/assets/48354990/51f0b707-4b15-4d09-af9a-da1e1fd334c5
Direct chat
https://github.com/linagora/twake-on-matrix/assets/48354990/04efab4e-1c16-448a-807f-47409e27162e
Room
https://github.com/linagora/twake-on-matrix/assets/48354990/625af1bb-481e-4d3f-88df-b48d65adc5ea
External ID 
https://github.com/linagora/twake-on-matrix/assets/48354990/9d95b744-e167-49b5-84f9-c32d1d1976b8
#580
=> TW-580 : feat enhance chat app bar from draft

lib/pages/chat/chat_room_search_mixin.dart
https://github.com/linagora/twake-on-matrix/assets/12546908/76948018-a895-473a-8074-cc7ad906b346
https://github.com/linagora/twake-on-matrix/assets/12546908/57dc9ac0-1f07-4c5d-a90c-328a07d0d115
=> fix: Search hide loading after no result

lib/pages/error_page/error_page.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold.dart
- Before
https://github.com/linagora/twake-on-matrix/assets/99852347/c69c01b7-a9bb-4e3f-8d18-1c4a9027fcdc
- After
https://github.com/linagora/twake-on-matrix/assets/99852347/7bcec68f-e65e-4649-8bdd-5521da8c80de
- Before
https://github.com/linagora/twake-on-matrix/assets/99852347/694052ae-3ea0-4f3a-a88b-69b3331932b7
- After
https://github.com/linagora/twake-on-matrix/assets/99852347/4ffad6a7-4002-47b0-8cf0-eecbe26d3f08
=> Fix: Settings page, error page and UI.

pubspec.lock
- https://github.com/linagora/matrix-dart-sdk/pull/20
- https://github.com/famedly/matrix-dart-sdk/pull/1560/files
=> fix: search duplicate events

lib/pages/chat/events/message_content.dart, lib/pages/chat/events/message_download_content.dart
=> fix: Highlight file event

lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_body.dart, lib/pages/chat_list/chat_list_item.dart, lib/widgets/twake_components/twake_header.dart, lib/widgets/twake_components/twake_header_style.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/41ad9980-55b3-4ba3-8554-d3cf365befde
https://github.com/linagora/twake-on-matrix/assets/99852347/e36191fe-e7b6-4aee-bde7-550da1be70fa
=> Hot fix:  Fix UI for chat list

lib/config/app_config.dart, lib/presentation/extensions/send_file_extension.dart, lib/presentation/extensions/send_file_web_extension.dart, lib/utils/js_window/js_window.dart, lib/utils/js_window/non_js_window.dart, lib/utils/js_window/universal_image_bitmap.dart, pubspec.lock, pubspec.yaml
- https://github.com/linagora/matrix-dart-sdk/pull/21
- #688 
https://github.com/linagora/twake-on-matrix/assets/12546908/ce9296df-ea24-4318-a2c5-e8f38d86ce6d
https://github.com/linagora/twake-on-matrix/assets/12546908/e89d351f-1f60-491c-ae83-469cbdc48f07
=> TW-688 Avoid Freeze when uploading file

lib/pages/chat_list/chat_list.dart, lib/pages/forward/forward.dart, lib/pages/share/share.dart, lib/pages/share/share_view.dart, lib/presentation/enum/chat_list/chat_list_enum.dart, lib/presentation/extensions/client_extension.dart
- #570 
https://github.com/linagora/twake-on-matrix/assets/99852347/accca145-93fc-4e7d-a5dd-57b46f76970f
https://github.com/linagora/twake-on-matrix/assets/99852347/b63fc225-f996-4c51-a8e2-8d28ae397a4a
=> TW-570: Update sort for chat list by time and pin msg

lib/presentation/extensions/send_file_web_extension.dart
https://github.com/linagora/twake-on-matrix/assets/12546908/419cd6c7-3970-4ff8-82c0-64e6544fca0a
=> fix: send video dimensions on web

lib/pages/homeserver_picker/homeserver_picker.dart, lib/pages/homeserver_picker/homeserver_picker_view.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/672fe0f1-37b7-4fd3-8eed-5e599306a50a
=> When click on login to submit homeserver remove focus in textfiled

lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/new_group/widget/contacts_selection_list.dart, lib/pages/new_group/widget/contacts_selection_list_style.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart, lib/pages/new_private_chat/widget/expansion_list.dart, lib/pages/search/recent_item_widget.dart, lib/utils/display_name_widget.dart, lib/widgets/highlight_text.dart
https://github.com/linagora/twake-on-matrix/assets/12546908/201b93cd-27fa-4a03-8167-91221aa2cd4b
=> fix: Highlight keyword when search contacts

lib/pages/forward/forward.dart, lib/utils/extension/navigator_state_extension.dart
- #555 
https://github.com/linagora/twake-on-matrix/assets/12546908/c66c2df9-c2cc-40a5-ad08-fc7768ce3e52
https://github.com/linagora/twake-on-matrix/assets/12546908/b5eef353-c93c-46ff-b3d9-38c274229f0e
=> TW-555 Foward Image hide dialog

lib/pages/chat_draft/draft_chat.dart, lib/pages/chat_draft/draft_chat_view.dart, lib/presentation/mixins/send_files_mixin.dart
#321 
https://github.com/linagora/twake-on-matrix/assets/48354990/1ca456c4-d26d-4838-a1a4-def2d999c196
=> TW-321 : Send files on draft web

lib/domain/model/room/room_extension.dart, lib/pages/chat_details/chat_details.dart, lib/pages/chat_details/chat_details_actions_enum.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_list/chat_list.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/70aed8a5-f6a9-4c78-a32c-52b90f463ceb
https://github.com/linagora/twake-on-matrix/assets/43041967/b51487a2-db98-4dd1-ad30-877d6b13596f
https://github.com/linagora/twake-on-matrix/assets/43041967/a41cb607-4e94-48e0-b74e-dbf952fc50c6
=> fix: remove actions in chat details

lib/pages/chat_list/chat_list_item_subtitle.dart, lib/utils/matrix_sdk_extensions/matrix_locals.dart, pubspec.lock, pubspec.yaml
https://github.com/orgs/linagora/projects/6?pane=issue&itemId=38677010
https://github.com/linagora/twake-on-matrix/assets/43041967/dd6400ef-7460-40b7-88e6-346718a5f193
=> TW-636: show unread icon in muted chat

lib/pages/chat/chat.dart, lib/pages/chat/chat_room_search_mixin.dart, lib/pages/chat/chat_view.dart
https://github.com/linagora/twake-on-matrix/assets/12546908/ecc0470c-d432-4d29-bdaa-e6513d0e36d1
https://github.com/linagora/twake-on-matrix/assets/12546908/91221bce-be7c-47cb-9796-1ebb88445021
=> fix: blynk when scroll in search room

lib/widgets/twake_components/twake_header.dart, lib/widgets/twake_components/twake_header_style.dart, lib/widgets/twake_components/twake_preview_link/twake_link_view.dart
- Duplicated padding for bubble chat
- Title in chat list wrong for web
- Update padding for chat list
https://github.com/linagora/twake-on-matrix/assets/99852347/845dab56-088b-423d-abaa-d0b20c6a4e6a
=> Fix UI chat wrong

lib/presentation/extensions/client_extension.dart
The chat list is out of order after pin/unpin a chat
https://github.com/linagora/twake-on-matrix/assets/43041967/83e04433-bde2-445b-8fba-77637106b00e
https://github.com/linagora/twake-on-matrix/assets/43041967/51fa15ca-2f06-42b4-ab2e-6f913ed877f7
https://github.com/linagora/twake-on-matrix/assets/43041967/a9068e40-a992-4c1b-b13e-dbdad4d3cbaf
=> hot-fix: chat list out of order

lib/main.dart, lib/utils/matrix_sdk_extensions/flutter_hive_collections_database.dart, pubspec.lock
- #715 
- https://github.com/linagora/matrix-dart-sdk/pull/24
https://github.com/linagora/twake-on-matrix/assets/99852347/6041703d-ee8a-4a34-934b-e900ffece5c6
=> TW-715: Fix clear DB when logout in web

lib/pages/chat_list/chat_list_item_mixin.dart
=> TW-658 fix: last sender display name null safety

lib/pages/chat/chat.dart
=> TW-720 fix: remove download file when no attachment

lib/domain/model/extensions/platform_file/platform_file_extension.dart, lib/domain/usecase/send_file_on_web_interactor.dart, lib/pages/chat/chat.dart, lib/pages/chat_draft/draft_chat.dart, lib/presentation/mixins/send_files_mixin.dart
waiting for PR deployment for demo
https://github.com/linagora/twake-on-matrix/assets/48354990/b1f4a22a-73c6-48c4-9620-816c4e5e3639
#718
=> TW-718 fix: drag & drop on web version

lib/pages/chat_details/chat_details_page_view/same_type_events_list_builder_view.dart, lib/pages/contacts_tab/contacts_tab.dart, lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/contacts_tab/contacts_tab_view.dart, lib/pages/contacts_tab/contacts_tab_view_style.dart, lib/pages/new_group/contacts_selection_view.dart, lib/pages/new_group/widget/contacts_selection_list.dart, lib/pages/new_private_chat/search_contacts_controller.dart, lib/pages/search/get_contacts_controller.dart, lib/widgets/twake_components/twake_loading/center_loading_indicator.dart, lib/widgets/twake_components/twake_smart_refresher.dart, pubspec.lock, pubspec.yaml
- #732 
- #679 
https://github.com/linagora/twake-on-matrix/assets/12546908/0950efce-6e00-4826-b02e-e24dddfa597a
https://github.com/linagora/twake-on-matrix/assets/12546908/eff851e7-0f62-430c-b414-eb1fc598ce8b
=> Tw 732 load more in add member in group need support mouse scroll

lib/pages/chat/events/message.dart
=> TW-719 feat: display only first message display name when multi

lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/input_bar.dart, lib/pages/chat_draft/draft_chat.dart, lib/pages/chat_draft/draft_chat_view.dart, lib/utils/extension/raw_key_event_extension.dart
- #724
https://github.com/linagora/twake-on-matrix/assets/12546908/f1bf24fe-4e6d-4831-bef6-103fe80af81a
https://github.com/linagora/twake-on-matrix/assets/12546908/ec53dd02-3954-48ea-b0a2-55575d8c0e35
https://github.com/linagora/twake-on-matrix/assets/12546908/1cb9d4a5-bb31-4875-aa58-82061abc3f0c
https://github.com/linagora/twake-on-matrix/assets/12546908/6c9012a4-e010-4191-8c0c-45b20c188963
=> TW-724 Improve composer with enter shortcut and need support Vietnamese

lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
https://github.com/linagora/twake-on-matrix/assets/12546908/22dd45de-4c00-4ebe-bfb3-6c58d5512257
https://github.com/linagora/twake-on-matrix/assets/12546908/eaf809db-6dc4-4337-b807-c79a668c0596
=> fix: Search contacts cached

lib/pages/settings_dashboard/settings/settings.dart, lib/utils/background_push.dart
https://github.com/linagora/twake-on-matrix/assets/12546908/7023a5fa-0afd-4627-9a30-5ab4d4519dac
https://github.com/linagora/twake-on-matrix/assets/12546908/3d10ad07-6bd9-436f-bf60-422c03c24c01
https://github.com/linagora/twake-on-matrix/assets/12546908/b2e4a5c5-d22c-4799-875a-48e46c4b79d1
=> fix: remove pusher when logout

lib/pages/chat/chat.dart, lib/pages/chat/events/message.dart
#734
#745 
https://github.com/linagora/twake-on-matrix/assets/48354990/e2440c71-2759-4b22-a502-a1bb19d7b85f
=> TW-734/TW-745 feat: remove forward from quick action in web

lib/widgets/layouts/adaptive_layout/adaptive_scaffold.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_view.dart, lib/widgets/layouts/enum/adaptive_destinations_enum.dart
- #765 
https://github.com/linagora/twake-on-matrix/assets/99852347/c75e9f73-b2df-4a7d-b6c6-42411d686454
=> TW-765: Keep navigation bar when open search page

assets/l10n/intl_en.arb, lib/domain/model/extensions/mime_type_extension.dart, lib/domain/model/preview_file/supported_preview_file_types.dart, lib/pages/chat/add_widget_tile.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_room_search_mixin.dart, lib/pages/chat/events/audio_player.dart, lib/pages/chat/events/event_video_player.dart, lib/pages/chat_details/chat_details.dart, lib/pages/chat_draft/draft_chat.dart, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_item.dart, lib/pages/chat_permissions_settings/chat_permissions_settings.dart, lib/pages/invitation_selection/invitation_selection.dart, lib/pages/login/login.dart, lib/pages/settings_dashboard/settings_profile/settings_profile.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_item_style.dart, lib/pages/settings_dashboard/settings_security/settings_security.dart, lib/pages/story/story_page.dart, lib/pages/user_bottom_sheet/user_bottom_sheet.dart, lib/presentation/mixins/media_picker_mixin.dart, lib/resource/image_paths.dart, lib/utils/fluffy_share.dart, lib/utils/matrix_sdk_extensions/event_extension.dart, lib/utils/matrix_sdk_extensions/matrix_file_extension.dart, lib/utils/twake_snackbar.dart, lib/utils/url_launcher.dart, lib/utils/voip_plugin.dart, lib/widgets/matrix.dart
[WEB] Open file on new tab if it's a PDF, if it's not then download it
#633 
Demo : 
https://github.com/linagora/twake-on-matrix/assets/48354990/8c1b23ca-7710-4800-a7f3-9fe5e5cbd34f
Error : 
https://github.com/linagora/twake-on-matrix/assets/48354990/f9690c6c-0e9e-4e36-9fd4-ecbac78e2393
Toast : 
https://github.com/linagora/twake-on-matrix/assets/48354990/1d3d5258-acf9-4663-8872-69ad43d398af
https://github.com/linagora/twake-on-matrix/assets/48354990/0f9bf476-8501-4bbc-a82e-93a0f2aa449d
=> TW-633 feat: preview pdf on web client

lib/pages/chat/chat_event_list.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message/message_style.dart
#738 
Demo : 
https://github.com/linagora/twake-on-matrix/assets/48354990/5c8ad0d3-6b9a-4940-a572-10b78f9b4323
Proof : 
Green : no gap 
Red : 8px gap (not same sender)
Blue : 4px gap (same sender)
https://github.com/linagora/twake-on-matrix/assets/48354990/ff7b375e-9d51-40c6-8544-0701cfcd8545
=> TW-738 feat: add spacing between messages bubbles

lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/widgets/twake_components/twake_smart_refresher.dart
https://github.com/linagora/twake-on-matrix/assets/12546908/939fea36-e9bd-498a-8616-1715f9291aee
=> fix: contacts on refresh

lib/pages/chat_list/chat_list.dart, lib/pages/settings_dashboard/settings/settings.dart, lib/presentation/enum/settings/settings_enum.dart, lib/utils/platform_infos.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold.dart, lib/widgets/log_view.dart
- #783 
https://github.com/linagora/twake-on-matrix/assets/99852347/edbb1b2d-745b-413c-862a-43615c792410
- Fix lost active chat
https://github.com/linagora/twake-on-matrix/assets/99852347/c0b2e73f-a91b-4d54-a33e-fd478fb1a38c
- Remove setting item that is active when back to settings list
https://github.com/linagora/twake-on-matrix/assets/99852347/1b929382-62f0-49ed-9214-a47511659d6b
- Support show version app in settings
https://github.com/linagora/twake-on-matrix/assets/99852347/4d6a71de-893e-4645-9213-ef25ccf69226
=> TW-783: Lost active chat when open settings

lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/chat_view.dart, lib/pages/chat_list/chat_list.dart
#727 
Mobile
https://github.com/linagora/twake-on-matrix/assets/48354990/7cde9b73-0487-44ab-a2e1-1781770c6992
Web
https://github.com/linagora/twake-on-matrix/assets/48354990/e4408cd6-862e-41b4-a7b6-f6a28052a9a6
=> TW-727: close selection mode after action

lib/pages/settings_dashboard/settings/settings.dart, lib/pages/settings_dashboard/settings_profile/settings_profile.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_context_menu_actions.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view_mobile.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view_web.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_view.dart, lib/widgets/mixins/popup_menu_widget_mixin.dart, pubspec.lock
- #780 
- Bottom navigator bar wrong color 
- Web 
https://github.com/linagora/twake-on-matrix/assets/99852347/aa3f5e8d-9aec-4c85-83b0-652cac422a93
- Mobile
https://github.com/linagora/twake-on-matrix/assets/99852347/4216ae01-42a8-44d9-96c9-a58888724712
https://github.com/linagora/twake-on-matrix/assets/99852347/9a8576db-04f4-4e44-955d-a06699af2db0
=> TW-780: Cannot changing avatar in settings

assets/l10n/intl_en.arb, assets/l10n/intl_ru.arb, assets/l10n/intl_vi.arb, lib/pages/chat/chat_app_bar_title.dart, lib/pages/chat/chat_view.dart, lib/utils/common_helper.dart, lib/utils/date_time_extension.dart, lib/utils/room_status_extension.dart, lib/widgets/matrix.dart, pubspec.lock
- `Online`
- < 1 hour: `? minutes ago` 
- 1 hour < x < 10 hours: `x hours ago`
- `Offline`
Less than 1 hour
Between 1 hour and 10 hours
More than 10 hours OR never activated / logged in
- ## set presence when closing app / put the app in background
https://github.com/linagora/twake-on-matrix/assets/48354990/93e4e4e5-308a-4f0f-9dec-9133b5c12f14
- ## initialize presence when room is direct chat, presence is null when reloading the window
Old : 
https://github.com/linagora/twake-on-matrix/assets/48354990/28d0fa49-b986-4ff3-9ac4-d37fd53fc9db
New : 
https://github.com/linagora/twake-on-matrix/assets/48354990/87acce8d-d1de-4c34-9528-2f417559f8cc
#578
=> TW-578 : Improve Room Status Sync

lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/events/button_content.dart, lib/pages/chat/events/button_content_style.dart, lib/pages/chat/events/call_invite_content.dart, lib/pages/chat/events/encrypted_content.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/message_content_mixin.dart, lib/pages/chat/events/redacted_content.dart, lib/pages/chat/events/unknown_content.dart, pubspec.lock
#777
Mobile 
Web 
No delete functionality
=> TW-777: refactor all messages content

lib/pages/chat_list/chat_list_item_subtitle.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/44a78416-baf2-41c1-88c5-7c4a896afdd7
=> Fix wrong UI for chat list

lib/pages/chat_list/chat_list.dart, lib/presentation/decorators/chat_list/subtitle_text_style_decorator/subtitle_text_style_decorator.dart, lib/presentation/decorators/chat_list/title_text_style_decorator/title_text_style_decorator.dart, lib/presentation/mixins/chat_list_item_mixin.dart
- Space subtitle chat list is wrong
- Can't unmute converstation chat list
- Wrong color for decorator style
- Fixed text style
https://github.com/linagora/twake-on-matrix/assets/99852347/469a43f7-dac9-49ad-b6f3-916bd46c5714
- Fixed unmute
https://github.com/linagora/twake-on-matrix/assets/99852347/a4600dd2-afb3-46d1-bea2-d4d6aaedc614
=> Hotfix text style for chat list

lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_item.dart, lib/pages/chat_list/chat_list_item_subtitle.dart, lib/pages/chat_list/chat_list_item_title.dart, lib/pages/chat_list/chat_list_view_builder.dart, lib/presentation/decorators/chat_list/subtitle_text_style_decorator/subtitle_text_style_decorator.dart, lib/presentation/decorators/chat_list/title_text_style_decorator/title_text_style_decorator.dart, lib/widgets/twake_components/twake_header.dart
- #756 
https://github.com/linagora/twake-on-matrix/assets/99852347/33e63cc1-7e5f-4f03-8a7f-0836d9856fda
=> TW - 756 Unread and read is wrong

lib/widgets/layouts/adaptive_layout/adaptive_scaffold_route.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_route_style.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_view.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_view_style.dart
- Support to display bottom navigation bar for tablet
https://github.com/linagora/twake-on-matrix/assets/99852347/0d58abee-ba73-41d9-810b-462c9c8be40c
=> Support to display bottom navigation bar for tablet

lib/domain/usecase/forward/forward_message_interactor.dart, lib/event/twake_event_types.dart, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/receive_sharing_intent_mixin.dart, lib/pages/share/share.dart, lib/widgets/app_bars/searchable_app_bar.dart, lib/widgets/matrix.dart
When user not in chat list screen, user back to background, share files do not redirect user to the share page.
https://github.com/linagora/twake-on-matrix/assets/43041967/38762067-a530-4d26-8a1f-22b926c9e5ae
https://github.com/linagora/twake-on-matrix/assets/43041967/f8229426-b3f0-4297-8107-a8247f0c2ff2
=> TW-728 - PART I: move receive sharing intent to matrix

lib/config/app_config.dart, lib/config/setting_keys.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/chat_input_row_mobile.dart, lib/pages/chat/chat_input_row_web.dart, lib/pages/chat/input_bar/context_menu_input_bar.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat/input_bar/input_bar_shortcut.dart, lib/pages/chat_draft/draft_chat_view.dart, lib/pages/settings_dashboard/settings_chat/settings_chat_view.dart, lib/presentation/extensions/text_editting_controller_extension.dart, lib/utils/one_time_debouncer.dart, lib/widgets/matrix.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/e0a16d91-fca5-42e3-9ccb-4738cacae119
https://github.com/linagora/twake-on-matrix/assets/43041967/b5f76eaf-21ca-408f-b101-9dec18589b27
=> feat: support shift-enter in web

ios/Runner.xcodeproj/project.pbxproj
This should fix the build errors.
=> Fixed signing and provisioning profile in XCode

lib/domain/model/room/room_list_extension.dart
#845 
https://github.com/linagora/twake-on-matrix/assets/48354990/ab955a42-2049-45c6-bdfa-2205f4685982
=> TW-845: add case insensitive to global search

lib/pages/chat/events/message/message.dart, lib/pages/chat/input_bar/input_bar.dart, lib/utils/string_extension.dart, lib/widgets/pill.dart
- #772 
- Timeline and displayName is too long: 
```
Calculate the length of `displayName` and the length of the content message to give the length of the witdh
```
https://github.com/linagora/twake-on-matrix/assets/99852347/2ebb6ba6-4cf3-4913-9312-3a2e76d00296
https://github.com/linagora/twake-on-matrix/assets/99852347/4774852d-8f05-4de9-9182-bdae49f7a285
https://github.com/linagora/twake-on-matrix/assets/99852347/e7920840-62df-4d45-a324-67c865a062f8
=> TW-772 improvement message bubble

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, lib/pages/connect/connect_page_mixin.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, web/auth.html, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
- #702 
- Web
https://github.com/linagora/twake-on-matrix/assets/99852347/9fa99b80-f0c5-42c8-9ba2-b78ea7c8db16
- Android
https://github.com/linagora/twake-on-matrix/assets/99852347/a1a2bbe4-fe42-49ce-823a-1cb7f98dcdde
=> TW-702: Can't close webview sso when login success for android system

lib/pages/chat_details/chat_details.dart, lib/pages/new_private_chat/search_contacts_controller.dart, lib/pages/search/get_contacts_controller.dart, lib/presentation/same_type_events_builder/same_type_events_controller.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview_item.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview_item_style.dart, lib/widgets/twake_components/twake_preview_link/twake_link_view.dart
- #853 
https://github.com/linagora/twake-on-matrix/assets/99852347/10f6e400-2bb6-4226-bf24-137d6eba9f4d
=> TW-853 improvement preview link

lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/input_bar/focus_suggestion_controller.dart, lib/pages/chat/input_bar/focus_suggestion_list.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat/input_bar/input_bar_shortcut.dart, lib/pages/chat_draft/draft_chat.dart, lib/pages/chat_draft/draft_chat_view.dart
- #759 
https://github.com/linagora/twake-on-matrix/assets/12546908/a181c8c9-41a1-4028-acd5-34b02a7369aa
https://github.com/linagora/twake-on-matrix/assets/12546908/6b4c33f6-d172-48ef-b69a-a1e087081b01
=> TW-759 Use keyboard to select suggestion item

lib/widgets/layouts/adaptive_layout/adaptive_scaffold_view.dart
Wrong condition
https://github.com/linagora/twake-on-matrix/assets/43041967/ced9bd88-275f-4332-b264-11cb713163f1
=> hot-fix/responsive-web-not-working

lib/pages/chat/chat.dart, lib/pages/chat/events/html_message.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/message_download_content.dart
hotfix: Chat room lagging by highlight keyword
=> hotfix: Chat room lagging by highlight keyword

lib/pages/settings_dashboard/settings_security/settings_security_view.dart
=> TW-869: Hide Change Password

lib/presentation/decorators/chat_list/subtitle_text_style_decorator/subtitle_text_style_decorator.dart, lib/presentation/decorators/chat_list/title_text_style_decorator/title_text_style_decorator.dart
- Style for chat list item is wrong for read/unread
=> Fix color of conversation in chat list

lib/pages/chat_details/chat_details_view.dart, pubspec.lock
#870 
sdk : https://github.com/linagora/matrix-dart-sdk/pull/32
https://github.com/linagora/twake-on-matrix/assets/48354990/a4fc227f-0fcb-4122-9024-d0d38dfd1d4b
=> TW-870: fix remove avatar

lib/pages/chat/chat.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/52d1e563-4aed-43bd-9844-61019afbfd83
=> TW-952: copy text for replied messages

lib/utils/background_push.dart
- #915 
https://github.com/linagora/twake-on-matrix/assets/99852347/20b49df2-117d-4c46-a559-dbba52150d1c
=> TW-915: Fix click on notification to open room for mobile

lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart
https://github.com/linagora/twake-on-matrix/assets/12546908/a4878bb4-fdc7-4df3-a388-34d774276bb9
https://github.com/linagora/twake-on-matrix/assets/12546908/0c294b9e-53b9-465a-9606-a0055d97bcc4
=> fix: Add highlight when search

lib/pages/chat/chat_event_list.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/new_group/widget/contacts_selection_list.dart
- Only the time in message now is tapped to select mode
- Messages is now selectable (double tap and triple tap is not working yet - Flutter team are doing it
https://github.com/linagora/twake-on-matrix/assets/43041967/57ba3ece-a6c2-4f86-bb0c-c5d2d4f0f319
https://github.com/linagora/twake-on-matrix/assets/43041967/9da0542f-ba5a-49a8-80b7-a2a6598e323b
=> TW-849: add selectable text for web

macos/fastlane/Fastfile
=> Always update fastlane before running

lib/widgets/local_notifications_extension.dart, web/index.html, web/script.js
- Can't click on notifications on web
https://github.com/linagora/twake-on-matrix/assets/99852347/624f126b-ba39-4bb5-9344-d80176dc34df
=> TW-915: Fix click on notification to open room in web

lib/pages/chat/events/message_content.dart
- #938 
https://github.com/linagora/twake-on-matrix/assets/99852347/b35839c6-2be6-4926-8d81-d92dcd2d3ce7
=> TW-938: Fix style of reply message same the style of normal message

lib/pages/forward/recent_chat_list.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation_view.dart, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body_view.dart
- #909 
https://github.com/linagora/twake-on-matrix/assets/99852347/27c4237a-5ad5-466c-8a04-510328e47350
https://github.com/linagora/twake-on-matrix/assets/99852347/3f98d59f-33e9-4874-84c0-13624d50aaaf
=> TW-909: Fix small bug version 2.3.6

lib/pages/chat/input_bar/context_menu_input_bar.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat/input_bar/input_bar_shortcut.dart, lib/presentation/extensions/text_editting_controller_extension.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/30005617-1862-4acd-b3f8-96f86cfabc9e
=> TW-976: add cutText in composer web

docs/adr/0011-workaround-for-ios-force-user-relogin.md, lib/data/hive/hive_collection_tom_database.dart, lib/utils/matrix_sdk_extensions/flutter_hive_collections_database.dart
=> #781 Fix re-login ios

assets/l10n/intl_en.arb, lib/utils/date_time_extension.dart, lib/utils/room_status_extension.dart
https://github.com/linagora/twake-on-matrix/assets/48354990/d5b92425-6326-4c2b-be2c-44d4e7058d6c
#934
=> TW-934: change online status of less than 1 minute to active now

lib/pages/chat/events/event_video_player.dart, lib/pages/chat/events/image_bubble.dart, lib/pages/chat/events/sending_video_widget.dart, lib/pages/image_viewer/image_viewer_view.dart, lib/presentation/mixins/play_video_action_mixin.dart, lib/widgets/mxc_image.dart, lib/widgets/video_viewer_mobile_theme.dart
- Remove blink when using hero animation in images
- Fix the error when close sending video back to chat list
https://github.com/linagora/twake-on-matrix/assets/43041967/197235fc-6562-441b-bded-7e0cc32ed2ad
https://github.com/linagora/twake-on-matrix/assets/43041967/fb5406ae-fa1e-4ffb-9e85-0a32a6f2a57c
=> Hot fix/remove hero animation in video

lib/pages/chat/chat_app_bar_title.dart, lib/pages/chat/chat_app_bar_title_style.dart, lib/presentation/mixins/chat_list_item_mixin.dart
https://github.com/linagora/twake-on-matrix/assets/48354990/4550a3aa-f050-4fa4-a001-08258bf8c2d5
#1025
=> TW-1025: recolor active status and chat list typing

lib/pages/forward/forward.dart, lib/pages/forward/forward_view.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/share/share.dart, lib/pages/share/share_view.dart, lib/presentation/mixins/search_recent_chat_mixin.dart, pubspec.lock
1. Can't click on options in contacts warning in new private chat
https://github.com/linagora/twake-on-matrix/assets/99852347/d728809f-efc8-48d1-84fe-80121a0cebdb
2. #1051 
3. #1050
1. 
https://github.com/linagora/twake-on-matrix/assets/99852347/14ed54ce-2c51-4cf5-98bb-ebb5e7ff8eec
2. 
https://github.com/linagora/twake-on-matrix/assets/99852347/216964e2-6d0e-43bf-baa2-26f5330a85e6
3.
https://github.com/linagora/twake-on-matrix/assets/99852347/89a02e5d-809a-4cb6-b330-1bfbc1013c11
=> TW-1051: apply search in forward and share

assets/l10n/intl_en.arb, ios/Runner.xcodeproj/project.pbxproj, lib/config/go_routes/go_router.dart, lib/config/localizations/language_code_constants.dart, lib/config/localizations/localization_service.dart, lib/data/datasource/localizations/localizations_datasource.dart, lib/data/datasource_impl/localizations/localizations_datasource_impl.dart, lib/data/local/localizations/language_cache_manager.dart, lib/data/repository/localizations/localizations_repository_impl.dart, lib/di/global/get_it_initializer.dart, lib/domain/app_state/localizations/save_language_state.dart, lib/domain/repository/localizations/localizations_repository.dart, lib/domain/usecase/settings/save_language_interactor.dart, lib/pages/settings_dashboard/settings/settings.dart, lib/pages/settings_dashboard/settings_app_language/settings_app_language.dart, lib/pages/settings_dashboard/settings_app_language/settings_app_language_view.dart, lib/pages/settings_dashboard/settings_app_language/settings_app_language_view_style.dart, lib/presentation/extensions/localizations/locale_extension.dart, lib/widgets/twake_app.dart, pubspec.lock, pubspec.yaml
- #1032
https://github.com/linagora/twake-on-matrix/assets/99852347/23f18d2f-9023-4406-99d6-69d6eca0284d
https://github.com/linagora/twake-on-matrix/assets/99852347/ef3cd29c-f1fb-4099-83a6-3a799325e44a
=> TW-1032: Language settings

PRIVACY.md, android/app/build.gradle, android/app/google-services.json, android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/app/twake/android/chat/FcmPushService.kt, android/app/src/main/kotlin/app/twake/android/chat/MainActivity.kt, android/app/src/main/kotlin/app/twake/android/chat/UnifiedPushService.kt, android/app/src/profile/AndroidManifest.xml, android/fastlane/Appfile, appimage/AppImageBuilder.yml, ios/Runner.xcodeproj/project.pbxproj, ios/Runner/GoogleService-Info.plist, ios/Runner/Info.plist, ios/Runner/Runner.entitlements, ios/Twake Share/Info.plist, ios/Twake Share/ShareViewController.swift, ios/Twake Share/Twake Share.entitlements, ios/fastlane/Appfile, ios/fastlane/Matchfile, lib/config/app_config.dart, macos/Runner.xcodeproj/project.pbxproj, macos/fastlane/Appfile, macos/fastlane/Fastfile, macos/fastlane/Matchfile, pubspec.yaml, scripts/enable-android-google-services.patch
Issue: #985 
Android: `app.twake.android.chat`
iOS: `app.twake.ios.chat` and  `app.twake.ios.chat.sandbox`
=> [WIP] TW#985 change app ID

lib/presentation/extensions/media/url_preview_extension.dart, lib/presentation/model/media/url_preview_presentation.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview_item.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview_item_style.dart
#916 
Large (h > 200)
Small (h <= 200)
=> TW-916: improve size image preview link

lib/pages/chat/events/message_content.dart
- #1034 
https://github.com/linagora/twake-on-matrix/assets/99852347/beda8f14-62e5-4466-9922-49178d08098b
https://github.com/linagora/twake-on-matrix/assets/99852347/9bcc9629-9156-4b6b-bef9-081306241ee5
=> TW-1034: Reply message has content preview link by preview link

lib/pages/chat/chat_event_list.dart
https://github.com/linagora/twake-on-matrix/assets/12546908/07166bdb-5c3a-4a6c-a0a4-f04fd1ed45d7
=> hotfix: Load more history

lib/pages/chat/chat_app_bar_title_style.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/chat_input_row_mobile.dart, lib/pages/chat/chat_input_row_style.dart, lib/pages/chat/chat_input_row_web.dart, lib/pages/chat/chat_pinned_events/pinned_events_view.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/chat_view_body.dart, lib/pages/chat/chat_view_body_style.dart, lib/pages/chat/chat_view_style.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat/reply_display.dart, lib/pages/chat_blank/chat_blank.dart, lib/pages/chat_draft/draft_chat_view.dart, lib/pages/chat_draft/draft_chat_view_style.dart, lib/pages/chat_list/chat_list_body_view.dart, lib/pages/chat_list/chat_list_view.dart, lib/pages/new_group/contacts_selection_view.dart, lib/pages/new_group/new_group_chat_info_view.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/share/share_view.dart, lib/widgets/app_bars/searchable_app_bar.dart, lib/widgets/app_bars/searchable_app_bar_style.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_appbar.dart, lib/widgets/twake_components/twake_header.dart, lib/widgets/twake_components/twake_icon_button.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/056b4582-020f-48da-97fb-caf7453fe5d0
=> Update style for chat

ios/Flutter/AppFrameworkInfo.plist, ios/Podfile, ios/Runner.xcodeproj/project.pbxproj
Refer: https://github.com/fluttercommunity/plus_plugins/issues/2276#issuecomment-1773056178
=> CI/CD IPHONEOS_DEPLOYMENT_TARGET 12.0

lib/pages/chat/events/html_message.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/reply_content.dart, lib/pages/chat/events/reply_content_style.dart, lib/pages/chat/reply_display.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/a8a5f80b-0548-4ea2-a759-dab5f3a91ba4
https://github.com/linagora/twake-on-matrix/assets/43041967/444fb224-d49e-4166-998f-2bb0436bced8
=> Hot fix/reply image message is not response

lib/domain/model/extensions/search/contact_search_extension.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/events/message/message.dart, lib/pages/new_private_chat/new_private_chat.dart, lib/presentation/extensions/contact/presentation_contact_extension.dart, lib/presentation/model/search/presentation_search.dart, lib/widgets/avatar/avatar.dart
https://github.com/linagora/twake-on-matrix/assets/48354990/3ab19d2d-7404-4314-b84c-6e4ab482da04
#850
=> TW-850: Go to direct chat on avatar click

lib/pages/homeserver_picker/homeserver_picker_view.dart, lib/widgets/layouts/login_scaffold.dart
=> TW-1123: center login app logo

assets/l10n/intl_en.arb, ios/Podfile, ios/Runner.xcodeproj/project.pbxproj, lib/config/go_routes/go_router.dart, lib/di/global/get_it_initializer.dart, lib/domain/app_state/room/update_group_chat_failure.dart, lib/domain/app_state/room/update_group_chat_loading.dart, lib/domain/app_state/room/update_group_chat_success.dart, lib/domain/usecase/room/update_group_chat_interactor.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_view.dart, lib/pages/chat_adaptive_scaffold/chat_adaptive_scaffold.dart, lib/pages/chat_details/chat_details.dart, lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_details/chat_details_edit_context_menu_actions.dart, lib/pages/chat_details/chat_details_edit_ui_state/upload_avatar_ui_state.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/chat_details/chat_details_edit_view_style.dart, lib/pages/chat_details/chat_details_navigator.dart, lib/pages/chat_details/chat_details_page_view/chat_details_members_page.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_details/chat_details_view_style.dart, lib/pages/chat_profile_info/chat_profile_info_style.dart, lib/pages/chat_search/chat_search_view.dart, lib/pages/search/search_view.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view.dart, lib/presentation/enum/chat/right_column_type_enum.dart
- #902
https://github.com/linagora/twake-on-matrix/assets/99852347/ae6980e7-c463-4f64-90b9-eaa20e11bbfa
1. Only update avatar success
https://github.com/linagora/twake-on-matrix/assets/99852347/e8875564-ba1d-4655-9e74-7f71ac498e4f
2. Only update group name success
https://github.com/linagora/twake-on-matrix/assets/99852347/e2c75f56-35c7-49ad-8166-35ec2820471c
3. Only update group descriptions success
https://github.com/linagora/twake-on-matrix/assets/99852347/85922614-41e7-454a-99e0-01e3a2ae2167
4. Update all success
https://github.com/linagora/twake-on-matrix/assets/99852347/0e6f64d5-168c-4289-929c-d2865cd9d10d
5. Only update group avatar failure
https://github.com/linagora/twake-on-matrix/assets/99852347/2bdb6bd8-5a81-455c-9761-5476ba8faaa3
6. Update group avatar success and group name …
=> TW-902: new design group informations

lib/widgets/mentionned_user.dart
=> TW-1037: Remove displayname char limit mentioned

lib/domain/app_state/search/server_search_state.dart, lib/domain/model/search/server_side_search_categories.dart, lib/domain/usecase/search/server_search_interactor.dart, lib/pages/search/search_view.dart, lib/pages/search/server_search_controller.dart, lib/pages/search/server_search_view.dart, lib/presentation/model/search/presentation_server_side_search.dart, lib/utils/string_extension.dart, test/string_extension_test.dart
- #1098 
https://github.com/linagora/twake-on-matrix/assets/99852347/a8b23bbd-0128-4158-bfea-d07c579b6f24
https://github.com/linagora/twake-on-matrix/assets/99852347/8e2ee7b6-d130-4c9c-82e7-3f119418172c
=> TW-1098 [Search] Load more in Server side Search

lib/di/global/get_it_initializer.dart, lib/domain/usecase/send_images_interactor.dart, lib/pages/chat/chat.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat_draft/draft_chat.dart, lib/presentation/mixins/media_picker_mixin.dart, lib/presentation/mixins/send_files_mixin.dart, pubspec.lock
- #1149
https://github.com/linagora/twake-on-matrix/assets/99852347/e031499f-a4d6-40a9-97a2-9f5548a08c15
https://github.com/linagora/twake-on-matrix/assets/99852347/e21945ca-c297-474a-93c0-5eed65fa3da4
=> TW-1149: Send media with caption on mobile

android/app/src/main/AndroidManifest.xml, ios/Twake Share/Info.plist, lib/config/go_routes/go_router.dart, lib/domain/usecase/send_file_interactor.dart, lib/pages/chat/chat.dart, lib/pages/chat_adaptive_scaffold/chat_adaptive_scaffold.dart, lib/pages/chat_list/receive_sharing_intent_mixin.dart, lib/pages/share/share.dart
- #1169 
https://github.com/linagora/twake-on-matrix/assets/99852347/c11601fc-b758-4914-9322-23f34e41dcfb
https://github.com/linagora/twake-on-matrix/assets/99852347/54be03ab-009e-4f7a-b8b0-746c887649f8
https://github.com/linagora/twake-on-matrix/assets/99852347/c69d67ec-792b-4239-af64-6a0cd30363f1
https://github.com/linagora/twake-on-matrix/assets/99852347/728fcbe4-a6ea-457d-a79d-f78e29b8f41d
https://github.com/linagora/twake-on-matrix/assets/99852347/333fde99-9f68-4122-be61-57c3ac4d7e26
https://github.com/linagora/twake-on-matrix/assets/99852347/0e24fa0b-cab5-4952-85bd-9dc7855484a8
=> TW-1169 share multiple files external

lib/pages/chat/events/download_video_widget.dart, lib/pages/chat/events/event_video_player.dart, lib/pages/chat/events/message_content_style.dart, lib/widgets/mxc_image.dart
#1126 
https://github.com/linagora/twake-on-matrix/assets/48354990/933c523b-718e-4896-b8c0-083ec82116a8
https://github.com/linagora/twake-on-matrix/assets/48354990/d86088b6-3b50-41eb-b72e-5c76af65bf38
=> TW-1126: Increase Video player hitbox size

lib/pages/invitation_selection/invitation_selection.dart
https://github.com/linagora/twake-on-matrix/assets/48354990/bf67758c-93c1-41bd-94aa-3604b4cb0c36
https://github.com/linagora/twake-on-matrix/assets/48354990/c717bee6-eb09-49ef-8b88-4e87a1e57d51
=> hotfix: remove unecessary pop after invite members

lib/pages/chat/chat_pinned_events/pinned_events_view.dart, lib/pages/chat/events/html_message.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat_details/chat_details_page_view/links/chat_details_links_item.dart, lib/pages/chat_encryption_settings/chat_encryption_settings_view.dart, lib/pages/chat_list/receive_sharing_intent_mixin.dart, lib/pages/homeserver_picker/homeserver_bottom_sheet.dart, lib/pages/new_private_chat/qr_scanner_modal.dart, lib/pages/settings_dashboard/settings/settings.dart, lib/pages/story/story_view.dart, lib/pages/twake_welcome/twake_welcome_view.dart, lib/pages/user_bottom_sheet/user_bottom_sheet_view.dart, lib/utils/platform_infos.dart, lib/utils/uia_request_manager.dart, lib/utils/url_launcher.dart, lib/widgets/matrix.dart, lib/widgets/profile_bottom_sheet.dart, lib/widgets/public_room_bottom_sheet.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview.dart, lib/widgets/twake_components/twake_preview_link/twake_link_view.dart
#1168 
https://github.com/linagora/twake-on-matrix/assets/48354990/2ae8cc89-9484-4fdd-bc49-29c359fe1437
=> TW-1168: Profile Info too long display name and click on pills

scripts/build-linux-debug.sh, scripts/build-linux.sh
Fixed the issue in our Linux builds
=> Update repo metadata before installing deps

.github/workflows/build.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml, .gitlab-ci.yml, Dockerfile, lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/dialog_reject_invite_widget.dart, lib/pages/chat/input_bar/focus_suggestion_list.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat/input_bar/input_bar_shortcut.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/chat_search/chat_search_view.dart, lib/pages/forward/forward_view.dart, lib/pages/homeserver_picker/homeserver_picker_view.dart, lib/pages/new_group/new_group_chat_info_view.dart, lib/pages/search/search_view.dart, lib/presentation/extensions/text_editting_controller_extension.dart, lib/presentation/mixins/handle_clipboard_action_mixin.dart, lib/presentation/mixins/paste_image_mixin.dart, lib/utils/clipboard.dart, lib/utils/dialog/twake_dialog.dart, lib/utils/extension/build_context_extension.dart, pubspec.lock, pubspec.yaml
- [WillPopScope](https://docs.flutter.dev/release/breaking-changes/android-predictive-back#migrating-a-back-confirmation-dialog:%7E:text=route%20transitions.%0A%7D-,Migrating%20a%20back%20confirmation%20dialog,-WillPopScope%20was%20sometimes)
- [flutter_typeahead](https://pub.dev/packages/flutter_typeahead/changelog)
- [super_clipboard](https://pub.dev/packages/super_clipboard/changelog)
https://github.com/linagora/twake-on-matrix/assets/43041967/97d781ad-595f-4c8c-ae1a-703d535a8be2
=> TW-1161: copy/paste with shortcuts in firefox

lib/config/app_config.dart, lib/config/go_routes/go_router.dart, lib/pages/auto_homeserver_picker/auto_homeserver_picker.dart, lib/pages/auto_homeserver_picker/auto_homeserver_picker_view.dart, lib/pages/connect/connect_page_mixin.dart, lib/utils/exception/check_homeserver_exception.dart, lib/widgets/matrix.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/1d5ad8de-668f-4aa5-b80a-4e21d3e070e5
=> Integrate registration web

ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Info.plist, lib/pages/chat_list/chat_list.dart, lib/utils/push_helper.dart, lib/utils/voip/callkeep_manager.dart, lib/widgets/matrix.dart, pubspec.yaml, scripts/build-linux-debug.sh, scripts/build-linux.sh
- Remove redundant permission in iOS
- apply App Store requirements
=> Rel v2.4.11

lib/pages/chat/input_bar/input_bar.dart, lib/presentation/mixins/paste_image_mixin.dart, lib/utils/clipboard.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/9bf12e59-4353-4982-978d-645847af298e
=> Tw 1162/paste multiple images from os

lib/pages/chat/chat.dart, lib/pages/chat/input_bar/focus_suggestion_controller.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat/input_bar/input_bar_shortcut.dart, lib/pages/homeserver_picker/homeserver_picker_view.dart, pubspec.lock, pubspec.yaml
https://github.com/linagora/twake-on-matrix/assets/99852347/ddfd3344-8eac-43f1-b88c-1a16b0faf4d9
https://github.com/linagora/twake-on-matrix/assets/99852347/bdd35ef3-f0ba-4d78-b834-ca519ad7c6d3
https://github.com/linagora/twake-on-matrix/assets/99852347/9ca581cf-d7ba-4e58-a8b5-8697222dcbfe
=> Fix cant use arrow up or down key when typing in composer

lib/pages/chat/input_bar/input_bar.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/870d5b92-a034-408d-8816-da10e619f4c9
https://github.com/linagora/twake-on-matrix/assets/99852347/35ddc061-7dac-4b43-bdd5-8af441cf6319
=> Hide input bar suggestion when typing in direct chat

lib/pages/chat/input_bar/input_bar.dart
=> Add border for input bar suggestions

lib/pages/search/search_contacts_and_chats_controller.dart, lib/presentation/model/search/presentation_search.dart
#1152 
https://github.com/linagora/twake-on-matrix/assets/48354990/d9787ebe-ebbf-43ae-9fa7-a047013e67b7
=> TW-1152: Search recent chats and contact by mail

lib/pages/chat_list/chat_list.dart, lib/widgets/layouts/agruments/logged_in_other_account_body_args.dart, lib/widgets/matrix.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/eaf1111f-c144-4354-86c0-d0086b7ad81d
=> Support and handle recovery data when logged new account

lib/pages/chat_blank/chat_blank.dart
- #1299 
https://github.com/linagora/twake-on-matrix/assets/99852347/355777f2-ae1f-42ea-a0b1-0bca19a3f312
=> TW-1299: Support create chat when click on pencil in chat blank

lib/pages/chat/send_file_dialog.dart, lib/pages/chat/send_file_dialog_view.dart, lib/presentation/enum/chat/send_media_with_caption_status_enum.dart, lib/presentation/mixins/send_files_with_caption_web_mixin.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/4833e880-290a-4678-bb77-999b2521402f
=> hot-fix: cancel send media also show error toast

lib/pages/chat/events/download_video_widget.dart, lib/pages/chat_details/chat_details.dart, lib/pages/chat_details/chat_details_navigator.dart, lib/widgets/video_viewer_mobile_theme.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/c2fcb6e5-96b0-4169-a71d-c96f22608e20
https://github.com/linagora/twake-on-matrix/assets/43041967/223f9b47-6e76-4f3a-b8e0-f7d65507a47f
=> TW-1269, 1270: Fix video player related errors

lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/chat_input_row_style.dart, lib/pages/chat/chat_loading_view.dart, lib/pages/chat/chat_view_body.dart, lib/pages/chat/chat_view_body_style.dart, lib/pages/chat/events/message/message.dart, lib/presentation/mixins/handle_clipboard_action_mixin.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/4da06524-4af1-4e2b-ba5e-e349292f2bde
https://github.com/linagora/twake-on-matrix/assets/43041967/a1b7c4f3-8370-4f9c-b6c6-39cbe8fa71d4
=> Tw 1297,1295,1296: fix bugs composer web

lib/pages/device_settings/device_settings_view.dart, lib/pages/settings_dashboard/settings/settings_app_bar.dart, lib/pages/settings_dashboard/settings_3pid/settings_3pid_view.dart, lib/pages/settings_dashboard/settings_app_language/settings_app_language_view.dart, lib/pages/settings_dashboard/settings_chat/settings_chat_view.dart, lib/pages/settings_dashboard/settings_emotes/settings_emotes_view.dart, lib/pages/settings_dashboard/settings_ignore_list/settings_ignore_list_view.dart, lib/pages/settings_dashboard/settings_multiple_emotes/settings_multiple_emotes_view.dart, lib/pages/settings_dashboard/settings_notifications/settings_notifications_view.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view.dart, lib/pages/settings_dashboard/settings_security/settings_security_view.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation_view.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/32abdf0d-aca1-40fc-891f-74d56710ce00
=> TW-1311: open profile when click to profile icon

lib/pages/chat/events/message/message.dart, lib/utils/matrix_sdk_extensions/filtered_timeline_extension.dart
- #1312 
- Before
https://github.com/linagora/twake-on-matrix/assets/99852347/deda0b79-8130-460b-8221-a97d4f89f196
- After
https://github.com/linagora/twake-on-matrix/assets/99852347/91434ded-fb27-4a43-b7a9-196150f93135
=> TW-1312: Hide event state join room from room creator

lib/pages/chat_details/chat_details.dart, lib/pages/invitation_selection/invitation_selection_style.dart, lib/pages/invitation_selection/invitation_selection_web.dart, lib/pages/new_group/contacts_selection_view.dart, lib/pages/new_group/contacts_selection_view_style.dart, lib/widgets/app_bars/searchable_app_bar_style.dart
#1265 
https://github.com/linagora/twake-on-matrix/assets/48354990/0892de15-0b73-44da-b890-ffba20ff32d4
https://github.com/linagora/twake-on-matrix/assets/48354990/124ce2f5-6435-4da5-9e9d-0c133296030f
=> TW-1265: fix new group paddings

lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/chat_details/chat_details_edit_view_style.dart
Related to #1280
https://github.com/linagora/twake-on-matrix/assets/48354990/28f06cbf-9c10-4ffc-8791-d1aa4c8f698e
=> TW-1280: fix group infos design

lib/pages/chat_draft/draft_chat_view.dart
https://github.com/linagora/twake-on-matrix/assets/6462404/bc1391a8-d2e0-4208-9272-2971ec2abe41
=> TW-1306 remove back button in draft chat

lib/pages/chat/chat_pinned_events/pinned_messages_screen.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/device_settings/device_settings_view.dart, lib/pages/new_group/contacts_selection_view.dart, lib/pages/new_group/contacts_selection_view_style.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/settings_dashboard/settings/settings_app_bar.dart, lib/pages/settings_dashboard/settings/settings_item_builder.dart, lib/pages/settings_dashboard/settings/settings_view.dart, lib/pages/settings_dashboard/settings_3pid/settings_3pid_view.dart, lib/pages/settings_dashboard/settings_app_language/settings_app_language_view.dart, lib/pages/settings_dashboard/settings_chat/settings_chat_view.dart, lib/pages/settings_dashboard/settings_emotes/settings_emotes_view.dart, lib/pages/settings_dashboard/settings_ignore_list/settings_ignore_list_view.dart, lib/pages/settings_dashboard/settings_multiple_emotes/settings_multiple_emotes_view.dart, lib/pages/settings_dashboard/settings_notifications/settings_notifications_view.dart, lib/pages/settings_dashboard/settings_security/settings_security_view.dart, lib/pages/settings_dashboard/settings_stories/settings_stories_view.dart, lib/pages/settings_dashboard/settings_style/settings_style_view.dart, lib/widgets/app_bars/searchable_app_bar.dart
- #1202 
https://github.com/linagora/twake-on-matrix/assets/99852347/c5c59019-f946-47ca-bf36-11f8bd59cac3
=> TW-1202: Update background color

lib/pages/chat/chat_pinned_events/pinned_messages_screen.dart
=> TW-1282: center title in pinned message view

lib/pages/chat/chat.dart, lib/pages/chat/chat_view_style.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat_list/chat_list.dart, lib/widgets/mixins/popup_context_menu_action_mixin.dart
- #930 
- Firefox
https://github.com/linagora/twake-on-matrix/assets/99852347/f1a2f9de-b48b-4e35-a1cd-580f40dd86ec
- Safari
https://github.com/linagora/twake-on-matrix/assets/99852347/9c4ffa64-06e2-426c-b474-ef49ddf2e445
- Chrome
https://github.com/linagora/twake-on-matrix/assets/99852347/dd86e6ba-c5f5-4210-8ae9-7e88861f2913
=> TW-930: Disable context menu in chat when switch tabs

lib/pages/chat/events/message/display_name_widget.dart, lib/pages/chat/events/message_time.dart, lib/pages/chat/events/message_time_style.dart, lib/pages/chat/events/state_message.dart, lib/pages/chat_list/chat_list_item_style.dart, lib/pages/chat_list/chat_list_item_title.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview_item.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/7dea4466-9135-4a2c-9000-ecc4c68cad01
=> Tw 1313/improve fonts for mobile

lib/pages/new_private_chat/new_private_chat_view.dart
https://github.com/linagora/twake-on-matrix/assets/48354990/52e81800-e348-4641-909b-b40a73d22f13
=> hotfix: padding in new private chat 

lib/pages/new_group/contacts_selection_view.dart, lib/pages/new_group/contacts_selection_view_style.dart, lib/widgets/app_bars/searchable_app_bar.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/5ed32047-b1a8-445a-b59c-aca4f5a94e54
https://github.com/linagora/twake-on-matrix/assets/43041967/0cfdbc35-4eb6-48f1-bb1b-5d3292da2241
https://github.com/linagora/twake-on-matrix/assets/43041967/016488e4-e967-430a-aeaf-89049728bc4a
https://github.com/linagora/twake-on-matrix/assets/43041967/5ab796fd-2e45-41c6-a055-eb43b8dc766f
=> hot-fix: fix padding in invitation selection screen

lib/pages/chat_details/chat_details.dart, lib/pages/chat_details/chat_details_page_view/chat_details_members_page.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_details/participant_list_item.dart, lib/pages/user_bottom_sheet/user_bottom_sheet.dart, pubspec.lock
https://github.com/linagora/matrix-dart-sdk/pull/43
https://github.com/linagora/twake-on-matrix/assets/43041967/f549b2f5-3571-4913-babb-c2de4ed631c5
=> Tw 1154/member list isnot updated when i kicked someone

lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_details/chat_details_view_style.dart, lib/widgets/mentionned_user.dart, lib/widgets/twake_components/twake_icon_button.dart, lib/widgets/twake_components/twake_preview_link/twake_link_view.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/e298e1a1-6f70-4537-8141-df524eb7d3df
=> improve: hover at mentioned name and icon

pubspec.lock
https://github.com/linagora/flutter_matrix_html/pull/13
https://github.com/linagora/matrix-dart-sdk/pull/44
#1328
=> TW-1328: fix bulletpoints and new lines

lib/pages/chat/chat.dart, lib/pages/chat/events/message_time.dart, lib/pages/chat/seen_by_row.dart, lib/utils/room_status_extension.dart
- #1165 
- DM
https://github.com/linagora/twake-on-matrix/assets/99852347/0eaa186b-87ed-4f23-950b-515d9ea91830
-Group
https://github.com/linagora/twake-on-matrix/assets/99852347/53fa17cb-9b5b-4154-a96e-3eb99c1258cf
https://github.com/linagora/twake-on-matrix/assets/99852347/410244ee-2d92-4351-b636-cb2467c11519
=> TW-1165: Fix status of message is't update correct

lib/pages/twake_id/twake_id.dart, lib/pages/twake_id/twake_id_view.dart
- #1315 
- Mobile
https://github.com/linagora/twake-on-matrix/assets/99852347/4164c6e3-e856-480f-a1b2-e93f506d9080
=> TW-1315: integrate sign up for mobile

lib/pages/bootstrap/bootstrap_dialog.dart, lib/pages/settings_dashboard/settings/settings.dart, lib/pages/settings_dashboard/settings/settings_view.dart, lib/pages/settings_dashboard/settings/settings_view_style.dart, lib/widgets/matrix.dart
- #1293 
https://github.com/linagora/twake-on-matrix/assets/99852347/96149eb3-a344-4c8a-b406-37b951c15375
https://github.com/linagora/twake-on-matrix/assets/99852347/fcfdf04d-ffa6-479e-b993-f1eab72e8b44
=> TW-1293: enable recovery data in settings

lib/pages/chat/chat.dart
#1358 
https://github.com/linagora/twake-on-matrix/assets/48354990/ad0de827-7a0d-41a2-a6c9-3089bd91b2e8
https://github.com/linagora/twake-on-matrix/assets/48354990/7b0532be-b8e4-4c74-a4ed-3ab83435e1d7
=> TW-1358: remove unnecessary select actions

lib/presentation/mixins/paste_image_mixin.dart
Demo:
https://github.com/linagora/twake-on-matrix/assets/43041967/1b3c63f8-aabc-47af-a096-b78535dff3bc
=> TW-1338: fix thumbnail of copied image don't have good size

lib/pages/chat/chat.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/widgets/twake_components/twake_icon_button.dart, lib/widgets/twake_components/twake_text_button.dart
- #1349 
- Safari
https://github.com/linagora/twake-on-matrix/assets/99852347/4c43c933-41f7-47de-acb6-772d750fed5c
- Firefox
https://github.com/linagora/twake-on-matrix/assets/99852347/6858e485-3e01-4e8f-a5ff-23dff0aa9bc1
- Chrome
https://github.com/linagora/twake-on-matrix/assets/99852347/8312a2a3-657d-4d13-a8a1-060f65f9ba41
=> TW-1349: Auto focus to composer when clicking on reply

lib/config/app_config.dart, lib/pages/auto_homeserver_picker/auto_homeserver_picker.dart, lib/pages/connect/connect_page_mixin.dart, lib/pages/twake_welcome/twake_welcome.dart, lib/pages/twake_welcome/twake_welcome_view.dart
- #1367 
- Login
https://github.com/linagora/twake-on-matrix/assets/99852347/e1c3f0d0-3aa4-4264-82bc-a81da5e8eb2f
- Register and login
https://github.com/linagora/twake-on-matrix/assets/99852347/3d390fc5-9e78-49c8-9b33-b0caefde8d26
- Already logged in public platform
https://github.com/linagora/twake-on-matrix/assets/99852347/e44dd051-fd6b-47d8-8b39-14a2b430daf5
=> [WEB] TW-1367: Integrate with register site of public platform

lib/pages/chat/events/download_video_widget.dart, lib/pages/chat_details/chat_details.dart, lib/pages/chat_details/chat_details_navigator.dart, lib/widgets/video_viewer_mobile_theme.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/d26d569d-2210-4c50-927a-1e3a949d3bba
https://github.com/linagora/twake-on-matrix/assets/43041967/ac679dc9-817b-4daf-96cb-ab536a8db25b
=> Cherry pick hot fix from 3.16

lib/pages/new_private_chat/new_private_chat.dart, lib/presentation/mixins/go_to_direct_chat_mixin.dart
- #1378
https://github.com/linagora/twake-on-matrix/assets/43041967/f1f74aa9-a302-4fa7-a780-9dac8ff35e7e
https://github.com/linagora/twake-on-matrix/assets/43041967/e2d3bddb-eaba-4e6e-9591-d10a4408a4a6
=> TW-1378: fix wrong rooting when create DM

lib/pages/chat/events/message_content.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview_item.dart, pubspec.lock, pubspec.yaml, test/widget/message/twake_link_preview_item_test.dart
=> TW-1377: [Part I] Create widget test for TwakeLinkPreview

lib/domain/model/room/room_extension.dart, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_header.dart, lib/pages/chat_list/chat_list_item_subtitle.dart, lib/pages/chat_list/chat_list_view.dart, lib/pages/chat_list/chat_list_view_builder.dart, lib/pages/chat_list/chat_list_view_style.dart, lib/presentation/enum/chat_list/chat_list_enum.dart, lib/presentation/mixins/chat_list_item_mixin.dart, lib/widgets/twake_components/twake_header.dart, pubspec.lock, pubspec.yaml
#1359
https://github.com/linagora/twake-on-matrix/assets/48354990/049b80a9-2325-4de7-a34d-f83c9658a592
https://github.com/linagora/twake-on-matrix/assets/48354990/f4d792ad-df69-48a4-96f7-920a70b3caec
https://pub.dev/packages/flutter_slidable
=> TW-1359: Add Slidable Chat List Item - Pin/Unpin

lib/pages/new_group/widget/contacts_selection_list_style.dart, lib/pages/new_private_chat/widget/expansion_list.dart, lib/pages/new_private_chat/widget/no_contacts_found.dart
- #1411 
https://github.com/linagora/twake-on-matrix/assets/99852347/04af0113-60b7-41a9-8779-8dee63834d97
https://github.com/linagora/twake-on-matrix/assets/99852347/76658de7-c1cb-40bc-8130-7786f4961249
=> TW-1411: Improve for search no result in create chat

lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/chat_details/chat_details_edit_view_style.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/42ffe5e9-12d2-4992-8867-9eb24e3ddfe0
https://github.com/linagora/twake-on-matrix/assets/99852347/c281d113-74c4-424e-bc7e-919c30f16593
=> TW-1383: Improve edit group

lib/widgets/twake_components/twake_preview_link/twake_link_preview.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview_item.dart, lib/widgets/twake_components/twake_preview_link/twake_link_view.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/b977a1db-98d5-47fb-8482-b4e1d446d8c1
=> hot-fix: hover-hand-at-link-only-in-message-bubble

lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/homeserver_picker/homeserver_picker_view.dart, pubspec.lock, pubspec.yaml
https://github.com/linagora/twake-on-matrix/assets/43041967/35ca10e2-7f65-48e5-aa9f-49ad4b7ea706
https://github.com/linagora/twake-on-matrix/assets/43041967/7cca2bec-4d8e-430a-9263-9478ecf21a82
=> TW-1402: cannot tag user in safari

assets/l10n/intl_fr.arb, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_body_view.dart, lib/pages/chat_list/chat_list_view_builder.dart, lib/pages/chat_list/chat_list_view_style.dart
https://github.com/linagora/twake-on-matrix/assets/48354990/f42644d7-4f36-4c70-942d-ee7cc3a1dfdd
#1360
=> TW-1360: Add Slidable Chat List Item - Read/Unread

assets/l10n/intl_en.arb, lib/pages/chat/chat.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat_details/chat_details.dart, lib/pages/chat_profile_info/chat_profile_info_view.dart, lib/presentation/extensions/text_editting_controller_extension.dart, lib/presentation/mixins/handle_clipboard_action_mixin.dart, lib/presentation/mixins/paste_image_mixin.dart, lib/utils/clipboard.dart, lib/utils/matrix_sdk_extensions/event_extension.dart, lib/utils/platform_infos.dart, pubspec.lock, pubspec.yaml
- Remove context menu when right-click in the composer
- Remove copy files/images/videos in context menu of message bubble in firefox
- enable copy text in web in context menu of message bubble in all browsers
- upgrade super_clipboard to latest
https://github.com/linagora/twake-on-matrix/assets/43041967/7b522481-82f9-48ae-8ba8-8d66ac7956c6
https://github.com/linagora/twake-on-matrix/assets/43041967/07f968e5-3736-4fc2-8088-5981aa70211d
https://github.com/linagora/twake-on-matrix/assets/43041967/6feda43a-1863-4579-9b22-5c4097fb3a5a
=> TW-1429: Copy paste not work in some case

lib/pages/forward/forward.dart, lib/pages/forward/forward_view.dart, lib/pages/forward/recent_chat_list.dart, lib/pages/forward/recent_chat_list_style.dart, lib/pages/share/share.dart, lib/pages/share/share_view.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/672903f8-10f3-48e5-82ba-32bdcbc60ac2
https://github.com/linagora/twake-on-matrix/assets/43041967/64bb89e0-6139-4c50-bc54-a081487f6afd
=> TW-217: update new UX for share and forward screen

lib/domain/model/extensions/string_extension.dart, lib/pages/chat/events/html_message.dart, lib/pages/chat/input_bar/input_bar.dart, lib/widgets/mentioned_user.dart
- #1196 
https://github.com/linagora/twake-on-matrix/assets/99852347/75229357-6091-4ed5-8276-fac93785771c
=> TW-1196: Update display pill with display name

lib/utils/date_time_extension.dart
- #1314 
- Change format date time from `MM/dd/yy` to `dd/MM/yy`
https://github.com/linagora/twake-on-matrix/assets/99852347/113471b8-0075-4f46-ab22-0183b90db031
=> TW-1314-part-II: Change format date time from MM/dd/yy to dd/MM/yy

lib/pages/chat/reply_display.dart, lib/pages/chat/reply_display_style.dart
- #1423
- Web
https://github.com/linagora/twake-on-matrix/assets/99852347/685419d7-0fad-489a-a512-5928153fe450
- Mobile
https://github.com/linagora/twake-on-matrix/assets/99852347/6a3866e2-e2d4-47ec-b97a-81f72de2541a
https://github.com/linagora/twake-on-matrix/assets/99852347/086862d5-4ab3-47f0-b62c-82c3814ed680
=> TW-1423: Update padding for reply content

assets/l10n/intl_en.arb, lib/pages/invitation_selection/invitation_selection.dart, lib/pages/new_group/contacts_selection_view.dart, lib/pages/new_group/contacts_selection_view_style.dart, lib/pages/new_group/selected_contacts_map_change_notifier.dart, lib/pages/new_group/widget/contacts_selection_list.dart, lib/pages/new_group/widget/contacts_selection_list_style.dart, lib/widgets/app_bars/searchable_app_bar.dart, lib/widgets/app_bars/searchable_app_bar_style.dart
- #1271 
https://github.com/linagora/twake-on-matrix/assets/99852347/0e3d03c0-1e56-411a-8752-5593a24ac460
=> TW-1271: Update UI for dialog invitation

lib/pages/search/search_contacts_and_chats_controller.dart, lib/pages/search/search_view.dart, lib/pages/search/server_search_view.dart
- #1152 
- Web
https://github.com/linagora/twake-on-matrix/assets/99852347/45606f72-bbc2-425a-9bcb-b4141603f4c4
- Mobile 
https://github.com/linagora/twake-on-matrix/assets/99852347/054897ab-f5b3-48a6-9a7c-790c14b82a28
=> TW-1152: Support can search by email on chat list

lib/pages/forward/recent_chat_list.dart, lib/pages/share/share_view.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/c1ceed2e-902e-4ab5-9417-9377590697d4
https://github.com/linagora/twake-on-matrix/assets/43041967/42c0ff3a-3730-44cf-bfbb-d33e7d4c14df
=> hot-fix: share screen dont have send button

android/app/src/main/AndroidManifest.xml, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body.dart, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body_view.dart
- #1457 
- https://docs.flutter.dev/release/breaking-changes/android-predictive-back
https://github.com/linagora/twake-on-matrix/assets/99852347/036d05a8-1767-4386-a969-097aa9a55af6
=> TW-1457: Migrate android predictive back

lib/pages/chat/chat_event_list.dart, lib/pages/chat/events/message/message.dart, pubspec.lock, pubspec.yaml
- #1492 
- https://github.com/linagora/inview_notifier_list/pull/1
https://github.com/linagora/twake-on-matrix/assets/99852347/8e6d98b2-46ca-4e1f-b1e8-faac5a3133b4
https://github.com/linagora/twake-on-matrix/assets/99852347/4c1b6fbc-e9c1-4586-92aa-bcc92416e8a2
=> TW-1492: Fix the message blink when received new message in chat

assets/l10n/intl_en.arb, ios/Podfile, lib/pages/chat_details/chat_details_edit.dart, lib/pages/new_group/new_group_chat_info.dart, lib/pages/settings_dashboard/settings_profile/settings_profile.dart, lib/presentation/mixins/common_media_picker_mixin.dart, lib/presentation/mixins/media_picker_mixin.dart, lib/presentation/mixins/single_image_picker_mixin.dart, lib/utils/permission_dialog.dart, lib/utils/permission_service.dart
- #1455
- Android
https://github.com/linagora/twake-on-matrix/assets/99852347/b83f32ab-4247-4f4e-afa5-8c2c72f56bbc
https://github.com/linagora/twake-on-matrix/assets/99852347/452c037f-19b9-4b4c-989a-1960637b2252
- iOS
https://github.com/linagora/twake-on-matrix/assets/99852347/0519e4a2-e41f-4cca-a2d5-cf4700845838
https://github.com/linagora/twake-on-matrix/assets/99852347/66126449-80ef-4e33-acc3-55f71a8f80ea
=> TW-1455: Fix micro permission when opening camera in chat

.gitignore, lib/pages/chat/chat.dart
Ticket: https://github.com/linagora/twake-on-matrix/issues/1482
[Capture vidéo du 23-02-2024 00:06:13.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/ae17b416-3b03-4889-bdb3-83f41d4c15ff)
=> [TW-1482]  Sometime Timestamp is disappear when scrolling

lib/pages/chat_details/chat_details_edit.dart, lib/presentation/mixins/single_image_picker_mixin.dart, pubspec.lock, pubspec.yaml
Ticket: https://github.com/linagora/twake-on-matrix/issues/1472
/!\ Needs to merge: https://github.com/linagora/linagora-design-flutter/pull/41 
[Capture vidéo du 22-02-2024 15:23:59.webm](https://github.com/linagora/linagora-design-flutter/assets/31937920/29ae4445-028d-4ab4-a509-ad6901cbebb8)
=> [TW-1472] Prevent user can select video in Change Avatar function

.github/workflows/release.yaml, scripts/release-android-apk.sh
Release file name should be `twake-<version>-android.apk`
=> Add Android release APK build and workflow

docs/adr/0017-remove-set-state-for-reply-message.md, lib/pages/chat/chat.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/events/reply_content.dart, lib/pages/chat/reactions_picker.dart, lib/pages/chat/reply_display.dart
- #1469
- SAFARI
https://github.com/linagora/twake-on-matrix/assets/99852347/394c5d13-6b91-41b9-8037-78e84f5a8ab4
- FIREFOX
https://github.com/linagora/twake-on-matrix/assets/99852347/2341924a-4e22-4b28-8c23-8a21bff0a40e
- CHROME
https://github.com/linagora/twake-on-matrix/assets/99852347/55ecb705-8cde-4216-bb3d-707c3d24ed13
=> TW-1469: Fix the cursor automatically focus when changing reply a message

lib/widgets/twake_components/twake_preview_link/twake_link_preview.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview_item.dart, lib/widgets/twake_components/twake_preview_link/twake_link_preview_item_style.dart, pubspec.lock, pubspec.yaml, test/widget/message/twake_link_preview_item_test.dart
- #1498 
- MOBILE
https://github.com/linagora/twake-on-matrix/assets/99852347/f5ff240a-3a35-4a79-bc38-19c1bcf82ffc
- WEB 
https://github.com/linagora/twake-on-matrix/assets/99852347/ebe2018f-7212-4a31-b3bb-4a914bd0d0e3
- WEB
https://github.com/linagora/twake-on-matrix/assets/99852347/3939ba2d-cd56-4829-a409-c22f3476c17d
- MOBILE
https://github.com/linagora/twake-on-matrix/assets/99852347/233dcd7f-5327-4524-8596-90561ceb7113
=> TW-1498: Improve preview link to prevent resizing

lib/pages/chat/chat.dart, lib/pages/chat/chat_pinned_events/pinned_events_controller.dart, lib/pages/chat/chat_pinned_events/pinned_messages.dart, lib/presentation/extensions/event_update_extension.dart, pubspec.lock, pubspec.yaml
- #1519
- https://github.com/linagora/matrix-dart-sdk/pull/51
- **CHAT** 
https://github.com/linagora/twake-on-matrix/assets/99852347/a2348edc-eb27-4691-b2c5-35a74547af78
https://github.com/linagora/twake-on-matrix/assets/99852347/86f7b5b5-7b2e-4b0e-be5b-7fa872a400cd
- **PIN SCREEN**
https://github.com/linagora/twake-on-matrix/assets/99852347/9b1ff3dd-1a12-46ab-abde-b498e7b3effa
https://github.com/linagora/twake-on-matrix/assets/99852347/e46c9a91-75f4-4d35-b652-dfdfa872b917
https://github.com/linagora/twake-on-matrix/assets/99852347/d562f2a3-b1f4-44b3-bd91-c4a4e2419c0a
https://github.com/linagora/twake-on-matrix/assets/99852347/c7628779-fbe5-43be-a606-f060c2fabca5
=> TW-1519: Automatically synchronize pin unpin

lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_details/chat_details_view_style.dart
- #1439 
https://github.com/linagora/twake-on-matrix/assets/99852347/a8c86a79-768f-45a7-a7d3-5911dc0a8b51
https://github.com/linagora/twake-on-matrix/assets/99852347/6414572e-7eaa-46d6-a676-2f54a0a619b4
=> TW-1439: Update UI for group information

ios/Runner.xcodeproj/project.pbxproj, lib/pages/search/recent_item_widget.dart, lib/pages/search/recent_item_widget_style.dart, lib/pages/search/search.dart, lib/pages/search/search_contacts_and_chats_controller.dart, lib/pages/search/search_mixin.dart, lib/pages/search/search_view.dart, lib/pages/search/search_view_style.dart, lib/presentation/model/search/presentation_search.dart, test/mixin/search/search_mixin_test.dart
- #1551 
https://github.com/linagora/twake-on-matrix/assets/99852347/15ca620f-6781-4b5d-acc1-0c6071640a54
=> TW-1551: Improve search in chat list

lib/pages/chat/events/message/message.dart
- #1524 
https://github.com/linagora/twake-on-matrix/assets/99852347/b1dee28d-3b95-436b-8a27-653ccefe2b1d
https://github.com/linagora/twake-on-matrix/assets/99852347/3e35b5b8-dacb-4e58-9e2d-9fc04555aa36
=> TW-1524: Remove hover on timestamp above message in chat

lib/pages/contacts_tab/contacts_tab_body_view.dart
- #1539 
https://github.com/linagora/twake-on-matrix/assets/99852347/a8ec0e24-bdc0-448d-bb97-3d894e0a3402
=> TW-1539: Fix condition for display no result in contacts tab

docs/adr/0020-keyboard-is-disappeared-then-appeared.md, lib/pages/contacts_tab/contacts_appbar.dart, lib/pages/dialer/pip/dismiss_keyboard.dart, lib/pages/search/search.dart, lib/pages/search/search_view.dart, lib/widgets/app_bars/searchable_app_bar.dart
- #1545
https://github.com/linagora/twake-on-matrix/assets/99852347/bbb18640-81f5-47ec-b07a-4f2d03828df1
=> TW-1545: Keyboard is disappeared then appeared

assets/l10n/intl_vi.arb, lib/pages/new_group/new_group.dart, lib/utils/date_time_extension.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation_style.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation_view.dart, lib/widgets/layouts/enum/adaptive_destinations_enum.dart, test/utils/date_time_extension_test.dart
- #1421 
- #1538 
- #1554 
https://github.com/linagora/twake-on-matrix/assets/80142234/294e0302-8899-4306-b7d3-b9933c2df7d5
=> TW-1421: Change name and date translation

lib/pages/chat/chat_context_menu_actions.dart, lib/pages/chat/chat_pinned_events/bottom_menu/bottom_menu_mobile.dart, lib/pages/chat/chat_pinned_events/bottom_menu/bottom_menu_web.dart, lib/pages/chat/chat_pinned_events/pinned_messages.dart, lib/pages/chat/chat_pinned_events/pinned_messages_screen.dart, lib/pages/chat/chat_pinned_events/pinned_messages_style.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat/events/message/multi_platform_message_container.dart, lib/utils/adaptive_bottom_sheet.dart
- #1369 
- Web
https://github.com/linagora/twake-on-matrix/assets/80142234/8afe9c3e-31da-40ac-8aae-77ccc84a880f
- Android
https://github.com/linagora/twake-on-matrix/assets/80142234/1922bef4-0edc-41b8-9f97-475c5f70d7fc
=> TW-1369 Support actions for pinned items

lib/presentation/mixins/send_files_mixin.dart
- #1543 
https://github.com/linagora/twake-on-matrix/assets/99852347/08831d0a-f2c7-4556-9e8f-0ee4990a577d
=> TW-1543: Fix cannot attach file

lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat/events/message/multi_platform_message_container.dart, lib/utils/extension/event_status_custom_extension.dart
- #1567 
https://github.com/linagora/twake-on-matrix/assets/99852347/9c4b240a-dd9b-4ed4-b245-076213983d1e
https://github.com/linagora/twake-on-matrix/assets/99852347/cf04da7b-cd06-4d44-b153-afe4fed5ac78
https://github.com/linagora/twake-on-matrix/assets/99852347/92f935a8-aeeb-47d1-816d-b9c0b275dacf
https://github.com/linagora/twake-on-matrix/assets/99852347/f5a49c82-5279-43f9-a73e-86871c124be0
=> TW-1567: Prevent show action reply/forward when message in sending/error

lib/pages/settings_dashboard/settings_profile/settings_profile.dart
- #1453 
https://github.com/linagora/twake-on-matrix/assets/99852347/fc051330-6fdd-4ac3-ba68-aad6cae97bcb
https://github.com/linagora/twake-on-matrix/assets/99852347/ae701488-cf26-4a38-a3d0-c9d4d5fae92c
=> TW-1453: Error handling when update profile fail

lib/domain/model/preview_file/supported_preview_file_types.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/message_content_style.dart, lib/pages/chat/events/reply_content.dart, lib/utils/extension/event_info_extension.dart, lib/utils/matrix_sdk_extensions/event_extension.dart
- #1565 
https://github.com/linagora/twake-on-matrix/assets/99852347/52e9a1a2-8de5-4fa3-99db-3ce9ee9dac01
https://github.com/linagora/twake-on-matrix/assets/99852347/656ab620-f575-4ccb-97df-5aefc61dd229
=> TW-1565 remove not playable video and change it to file

lib/pages/chat_profile_info/chat_profile_info_style.dart, lib/pages/chat_profile_info/chat_profile_info_view.dart
- #1124 
- Web:
https://github.com/linagora/twake-on-matrix/assets/80142234/e391d2ce-76d7-41cf-9958-f56a06b0d637
- Android:
https://github.com/linagora/twake-on-matrix/assets/80142234/9e7037e3-2f94-4298-ac32-b53a0471a283
=> TW-1124: Profile image looking blur

lib/pages/chat_list/chat_list.dart
- #1528 
- Web:
https://github.com/linagora/twake-on-matrix/assets/80142234/daf22626-85dc-44e0-a80d-b45cf5c05338
- Android:
https://github.com/linagora/twake-on-matrix/assets/80142234/fb092401-3df0-459f-bb5f-6efbc08ae34a
=> TW-1528: Fix selection mode in chat list

lib/pages/chat/events/download_video_widget.dart, lib/pages/image_viewer/media_viewer_app_bar.dart, lib/pages/image_viewer/media_viewer_app_bar_view.dart, lib/pages/image_viewer/media_viewer_app_bar_web.dart, lib/presentation/mixins/media_viewer_app_bar_mixin.dart, lib/widgets/video_player.dart, lib/widgets/video_viewer_desktop_theme.dart, lib/widgets/video_viewer_mobile_theme.dart, lib/widgets/video_viewer_style.dart
- #1564 
- MOBILE
https://github.com/linagora/twake-on-matrix/assets/99852347/f1b899e4-47bf-4d12-bf82-75527fa01c07
- WEB
https://github.com/linagora/twake-on-matrix/assets/99852347/ed7a5857-d0b3-4d63-967e-2811ca3ec113
https://github.com/linagora/twake-on-matrix/assets/99852347/821085a8-020a-4544-933d-a8317a91c7db
=> TW-1453: Improvement for video player

lib/pages/chat/chat_input_row_send_btn.dart, lib/pages/chat_draft/draft_chat.dart, lib/pages/chat_draft/draft_chat_input_row.dart, lib/pages/chat_draft/draft_chat_view.dart
- #1544 
- WEB
https://github.com/linagora/twake-on-matrix/assets/99852347/27497446-cc8e-4394-bc17-e81b72e573e1
- MOBILE
https://github.com/linagora/twake-on-matrix/assets/99852347/8c4c7ebb-fe52-4138-bc68-8321d1554099
=> TW-1544: Prevent create multiple direct chats when creating direct chat

lib/di/global/get_it_initializer.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/message_download_content.dart, lib/pages/image_viewer/image_viewer_view.dart, lib/presentation/mixins/handle_video_download_mixin.dart, lib/presentation/model/chat/downloading_state_presentation_model.dart, lib/utils/manager/download_manager/download_file_info.dart, lib/utils/manager/download_manager/download_file_state.dart, lib/utils/manager/download_manager/download_manager.dart, lib/utils/manager/download_manager/downloading_worker_queue.dart, lib/utils/matrix_sdk_extensions/download_file_extension.dart, lib/utils/matrix_sdk_extensions/int_extension.dart, lib/utils/storage_directory_utils.dart, lib/widgets/file_widget/download_file_tile_widget.dart, lib/widgets/file_widget/file_tile_widget.dart, lib/widgets/file_widget/message_file_tile_style.dart, lib/widgets/mixins/handle_download_and_preview_file_mixin.dart, lib/widgets/mxc_image.dart, test/worker_queue_test.dart
Updated
https://github.com/linagora/twake-on-matrix/assets/43041967/52db9611-d364-43da-86c0-22631e2000bf
https://github.com/linagora/twake-on-matrix/assets/43041967/320796ff-1207-4aa9-b023-8411636d83aa
=> TW 1586-part 2 download file

lib/pages/chat/events/message_download_content.dart, lib/widgets/mixins/handle_download_and_preview_file_mixin.dart
- #1581 
https://github.com/linagora/twake-on-matrix/assets/99852347/55a21458-5f78-4663-a07f-ec39aad31998
https://github.com/linagora/twake-on-matrix/assets/99852347/f7fd6383-0c37-40ca-a40b-55de6f435e47
=> TW-1581: Preview unknown file instead of sharing

lib/pages/chat/chat_pinned_events/pinned_messages.dart
In Chat screen, we have a lot of `StreamSubcription` but we usually don't cancel it, when back to the previous screen. So we have to cancel it everytime the widget is disposed to free the resources. If we don't cancel the subscription, other notifier inside the subscription which is already dispose() can be invoked again.
=> hot-fix: cancel the stream subscription if not used anymore

lib/config/app_config.dart, lib/pages/twake_welcome/twake_welcome.dart, lib/pages/twake_welcome/twake_welcome_view.dart, lib/widgets/matrix.dart
=> Hot fix: Enable `dart-define` for configuration public platform on mobile

lib/pages/chat/events/message_download_content.dart, lib/presentation/extensions/send_file_extension.dart, lib/utils/matrix_sdk_extensions/download_file_extension.dart, lib/utils/matrix_sdk_extensions/event_extension.dart, lib/utils/storage_directory_utils.dart
#1561 
https://github.com/linagora/twake-on-matrix/assets/43041967/f8fb5d3f-0781-4834-ba6c-9d9faf40e822
=> Tw 1561/preview file sent from me

lib/config/first_column_inner_routes.dart, lib/config/go_routes/go_router.dart, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_header.dart, lib/pages/chat_list/chat_list_view.dart, lib/pages/search/search.dart, lib/pages/search/search_text_field.dart, lib/pages/search/search_view.dart, lib/pages/search/search_view_style.dart, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body.dart, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body_view.dart, lib/widgets/layouts/enum/adaptive_destinations_enum.dart, lib/widgets/swipe_to_dismiss_wrap.dart
#1578
https://github.com/linagora/twake-on-matrix/assets/43041967/5327fa26-6acf-4446-afa9-a5edb2049d6d
https://github.com/linagora/twake-on-matrix/assets/43041967/e0931382-d270-4de9-921c-752343f82066
=> Tw 1578/improve animation when open chat list search

lib/presentation/mixins/media_picker_mixin.dart, pubspec.yaml
- Side effect from #1455
https://github.com/linagora/twake-on-matrix/assets/99852347/2b2755d9-eeeb-466d-b515-54cb2ecae6c0
https://github.com/linagora/twake-on-matrix/assets/99852347/3b1b2e70-8790-48f1-82a0-a66717f6249a
=> TW-1662: Can't send a video picture by using camera

lib/pages/chat_search/chat_search_view.dart
- #1614
https://github.com/linagora/twake-on-matrix/assets/99852347/7dee9bcd-7f1a-4c0d-945b-8eb535063db5
=> TW-1614: Update border for search result on chat search

lib/pages/forward/forward.dart, lib/pages/share/share.dart, lib/presentation/enum/chat_list/chat_list_enum.dart
- #1497 
https://github.com/linagora/twake-on-matrix/assets/99852347/80a229bf-5dde-4310-98f2-db7965b81201
https://github.com/linagora/twake-on-matrix/assets/99852347/e0a3afb4-cc96-4a56-8240-6b8954df106d
=> TW-1497: Filter chat is yet accepted invitation

lib/pages/forward/recent_chat_list.dart
https://github.com/linagora/twake-on-matrix/assets/99852347/bae359b0-2e72-4c37-aab0-523cb44863b4
=> Update background for forward screen

lib/pages/contacts_tab/contacts_tab.dart, lib/pages/search/recent_item_widget.dart, lib/pages/search/search.dart
Issue: https://github.com/linagora/twake-on-matrix/issues/1592
Web (+ responsive)
[Capture vidéo du 08-04-2024 15:38:26.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/01786270-2280-4e65-9eb6-7cea862f312a)
Mobile
https://github.com/linagora/twake-on-matrix/assets/31937920/5b10e11b-ad3f-4559-ae50-11b231d77da8
=> TW-1592: go to setting profile when clicking to own contact

.github/workflows/build.yaml
Use unique naming for mobile artifacts
=> Use unique name for upload-artifact to prevent error

assets/l10n/intl_en.arb, lib/config/app_config.dart, lib/pages/auto_homeserver_picker/auto_homeserver_picker.dart, lib/pages/auto_homeserver_picker/auto_homeserver_picker_state.dart, lib/pages/auto_homeserver_picker/auto_homeserver_picker_view.dart, lib/presentation/mixins/init_config_mixin.dart, lib/widgets/matrix.dart
- When we use `AppConfig.homeserver` in `AutoHomeserverPickerController` on web platform however `AppConfig.homeserver` not sure to set up new data from `config.json`. 
→ Can't get login `[Matrix] Found no well known information - XMLHttpRequest error.`
- Use `completer` make sure to set up new data from `config.json`. 
https://github.com/linagora/twake-on-matrix/assets/99852347/0666274e-4a97-4357-af72-7192c3ff8cd0
https://github.com/linagora/twake-on-matrix/assets/99852347/176b4a06-d6b2-4e8f-89d9-9c011193ee23
=> Hot fix setup config json on web

assets/l10n/intl_en.arb, assets/l10n/intl_fr.arb, assets/l10n/intl_ru.arb, assets/l10n/intl_vi.arb
- #1461 
https://github.com/linagora/twake-on-matrix/assets/80142234/69a2b34c-7a82-4d5b-b0a2-b3d51f5a615b
=> TW-1461: Update app language setting subtitles

lib/pages/chat/input_bar/input_bar.dart
- #1719
- Side effect from #1441 
https://github.com/linagora/twake-on-matrix/assets/99852347/00a0bdc0-9904-4013-be60-db81ad12297a
- Emoji
https://github.com/linagora/twake-on-matrix/assets/99852347/fdf6d95e-9b86-4fa7-a47c-d417d38bb1ee
- Web Safari
https://github.com/linagora/twake-on-matrix/assets/99852347/b6ddbdae-d7f9-453b-9972-790c40e3d665
Web firefox
https://github.com/linagora/twake-on-matrix/assets/99852347/364fa9b9-2843-4b1c-a158-5cca7e49defc
=> TW-1791: Fix can't tag name on mobile

lib/pages/chat/events/message_download_content.dart, lib/pages/chat/events/message_download_content_web.dart, lib/presentation/model/chat/downloading_state_presentation_model.dart, lib/utils/matrix_sdk_extensions/download_file_extension.dart, lib/utils/matrix_sdk_extensions/download_file_web_extension.dart, lib/widgets/file_widget/download_file_tile_widget.dart, lib/widgets/file_widget/message_file_tile_style.dart
Ticket: https://github.com/linagora/twake-on-matrix/issues/1702
Demo:
Web:
[Capture vidéo du 19-04-2024 16:14:52.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/cc3be4b8-7afd-4eaa-b78b-336e5f5699d5)
Mobile:
https://github.com/linagora/twake-on-matrix/assets/31937920/4e4bcb3b-25ef-4bfa-b3ea-2b37795ccade
=> TW-1702: DownloadErrorPresentationState added handle errors

assets/l10n/intl_en.arb, lib/pages/chat/chat.dart, lib/pages/chat/chat_actions.dart, lib/pages/chat/chat_view.dart, lib/pages/chat/chat_view_body.dart, lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_details/chat_details_edit_option.dart, lib/pages/chat_details/chat_details_edit_option_style.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/chat_details/chat_details_edit_view_style.dart, lib/presentation/mixins/leave_chat_mixin.dart, lib/utils/exception/leave_room_exception.dart, lib/widgets/context_menu/context_menu_position.dart, lib/widgets/context_menu/twake_context_menu.dart
- #1695 
- Web:
https://github.com/linagora/twake-on-matrix/assets/80142234/5ab97265-7ccb-49b3-bcbe-9ea44d48c9ab
- Android:
https://github.com/linagora/twake-on-matrix/assets/80142234/78f15013-b2b7-49d3-b75a-fb31363af97b
=> TW-1695: Leave group

assets/l10n/intl_en.arb, lib/pages/auto_homeserver_picker/auto_homeserver_picker.dart, lib/pages/login/on_auth_redirect.dart, lib/presentation/mixins/connect_page_mixin.dart, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body.dart
- #1711 
- Case error:
https://github.com/linagora/twake-on-matrix/assets/99852347/bbec5ad2-e602-423a-947e-05570de97611
- Case logged on registration ⇒ open Twake chat
https://github.com/linagora/twake-on-matrix/assets/99852347/8fd03e51-73a3-48b3-8662-1eef0dd13768
=> TW-1711: handle deep link from registration platform

assets/l10n/intl_en.arb, lib/pages/chat_details/participant_list_item/participant_list_item.dart, lib/pages/chat_list/chat_list_view.dart, lib/pages/new_group/new_group_chat_info_view.dart, lib/pages/profile_info/profile_info_body/profile_info_body.dart, lib/pages/profile_info/profile_info_body/profile_info_body_view.dart, lib/pages/profile_info/profile_info_body/profile_info_body_view_style.dart, lib/pages/profile_info/profile_info_page.dart, lib/pages/profile_info/profile_info_view.dart, lib/pages/settings_dashboard/settings_security/settings_security.dart, lib/pages/settings_dashboard/settings_security/settings_security_view.dart, lib/presentation/enum/profile_info/profile_info_body_enum.dart, lib/utils/dialog/warning_dialog.dart, lib/utils/warning_dialog.dart
- #1734 
https://github.com/linagora/twake-on-matrix/assets/99852347/5eea65f8-5a3f-400f-94cb-7f610246c50a
https://github.com/linagora/twake-on-matrix/assets/99852347/fd5d2e3d-fe84-4456-8ded-849d97b182bd
- In Security tab
=> TW-1734: Fix bugs pre prod

lib/pages/chat/events/message_download_content.dart, lib/pages/chat/events/message_video_download_content.dart, lib/pages/chat/events/message_video_download_content_web.dart, lib/widgets/file_widget/download_file_tile_widget.dart
https://github.com/linagora/twake-on-matrix/assets/43041967/fa84fbe2-50df-4bbf-a1dc-a5a56ec29e72
https://github.com/linagora/twake-on-matrix/assets/43041967/ef4035fb-251c-455e-a424-d799042b0d28
https://github.com/linagora/twake-on-matrix/assets/43041967/79b553ca-dbc1-4f55-8fdf-22d8d5c73675
=> Improve download button in video

docs/configurations/config_build_mobile_app_for_public_platform.md, lib/config/app_config.dart, lib/config/config_saas/config_saas.dart, lib/pages/chat_draft/draft_chat.dart, lib/presentation/enum/chat_list/chat_list_enum.dart, lib/presentation/mixins/connect_page_mixin.dart
- #1768 
https://github.com/linagora/twake-on-matrix/assets/99852347/30a44d53-b9df-45c0-a964-06aed08dca0c
https://github.com/linagora/twake-on-matrix/assets/99852347/6211b2f3-63ab-4e1b-b9ee-2ca04bd9fdbc
Case 1: platform is not `saas`
https://github.com/linagora/twake-on-matrix/assets/99852347/23e82555-c1f4-42d0-ac6a-6788019d8ea5
case 2: platform is `saas`
https://github.com/linagora/twake-on-matrix/assets/99852347/be5eb123-1f7a-4ca1-827b-5fc9e5277c83
=> TW-1768: Improve UI for chat screen

lib/pages/search/search_external_contact.dart, lib/pages/search/search_external_contact_style.dart, lib/pages/search/search_view.dart, pubspec.lock, pubspec.yaml
Ticket: https://github.com/linagora/twake-on-matrix/issues/1735
Waiting for this PR to be merged: https://github.com/linagora/matrix-dart-sdk/pull/59
Demo:
[Capture vidéo du 20-05-2024 17:51:03.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/24603954-5df5-42ef-b503-e3415bdee2f0)
=> TW-1735: can't search matrix id

lib/config/app_config.dart, lib/config/go_routes/go_router.dart, lib/pages/twake_welcome/twake_welcome.dart, lib/pages/twake_welcome/twake_welcome_view.dart, lib/presentation/mixins/connect_page_mixin.dart, pubspec.lock
- #1780 
https://github.com/linagora/linagora-design-flutter/pull/42
https://github.com/linagora/twake-on-matrix/assets/99852347/07dd61c1-0c99-4232-8e37-f1b4cfeb072c
=> TW-1780: Open screen can connect with Twake Workplace when add another account

assets/l10n/intl_en.arb, lib/config/app_config.dart, lib/pages/twake_welcome/twake_welcome.dart, lib/pages/twake_welcome/twake_welcome_view.dart, pubspec.lock
Update privacy welcome screen
https://github.com/linagora/twake-on-matrix/assets/99852347/f3f13ac6-e189-4e6e-aca6-0a274300ffd3
=> Update privacy welcome screen

lib/presentation/mixins/media_picker_mixin.dart, lib/presentation/style/media_picker_style.dart, pubspec.lock, pubspec.yaml
- #1645
https://github.com/linagora/twake-on-matrix/assets/99852347/54721e49-13dd-4777-a9a4-d03a14d39f0b
https://github.com/linagora/twake-on-matrix/assets/99852347/866c77f3-cb34-48e7-9716-204e7bca6207
=> TW-1645: Add counting selected image at send icon

lib/presentation/style/media_picker_style.dart
- Size of counter icon big
- Resize to small
https://github.com/linagora/twake-on-matrix/assets/99852347/ed251889-7e7b-4b35-a664-d49a32aa4658
=> [Part-II] TW-1645: Fix size for counter icon

lib/pages/chat/chat.dart, lib/presentation/mixins/handle_clipboard_action_mixin.dart, lib/presentation/mixins/paste_image_mixin.dart, lib/presentation/mixins/send_files_mixin.dart, lib/presentation/mixins/send_files_with_caption_web_mixin.dart
- #1615 
https://github.com/linagora/twake-on-matrix/assets/99852347/0ee94a53-9d4b-4840-8734-fb0d34e7af65
- Drag and drop 
https://github.com/linagora/twake-on-matrix/assets/99852347/d212beb9-43e4-4d29-b328-20641ad9c9a0
- Copy/paste
https://github.com/linagora/twake-on-matrix/assets/99852347/b1488da9-e72d-4ff3-b53d-4ccacd34652a
https://github.com/linagora/twake-on-matrix/assets/99852347/9565bcbf-ad68-430d-8914-f4bcd547be31
https://github.com/linagora/twake-on-matrix/assets/99852347/1741639b-4606-4c4d-9ffb-79be9834a660
=> TW-1615: Support auto jump to lastest message when user send an attachments 

web/index.html
- PUT `assets/....` will work in local and deploy
=> hot-fix: the web_support.js path

lib/pages/chat_search/chat_search.dart, lib/pages/search/search.dart, lib/pages/search/server_search_controller.dart, lib/utils/matrix_sdk_extensions/result_extension.dart
Related ticket: https://github.com/linagora/twake-on-matrix/issues/1635
https://github.com/linagora/twake-on-matrix/assets/43041967/2761ea61-dfef-49ba-ab23-c9f815c9d1a4
https://github.com/linagora/twake-on-matrix/assets/43041967/632f3c13-a2ab-4b8b-b382-6cb97413248e
=> TW-1635: remove the messages contains reply from search result

lib/pages/chat_adaptive_scaffold/chat_adaptive_scaffold_builder.dart, lib/utils/responsive/responsive_utils.dart, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold.dart
#1698 
- add ratio for messageBubble width
###
https://github.com/linagora/twake-on-matrix/assets/43041967/dffa4741-6a29-4208-91cd-5c0d8dfd9e05
=> TW-1698: group details in small in width

lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat/input_bar/input_bar_shortcut.dart
Issue: https://github.com/linagora/twake-on-matrix/issues/1602
- Safari:
https://github.com/linagora/twake-on-matrix/assets/43041967/7b51f497-59ca-4427-88a5-8a3207163e27
- Chrome:
https://github.com/linagora/twake-on-matrix/assets/43041967/5f2b909b-44fe-4d46-8c59-07f6e160e891
- Firefox:
https://github.com/linagora/twake-on-matrix/assets/43041967/b4889a9b-83ac-4579-bf6b-30d8dff4f2e1
https://github.com/linagora/twake-on-matrix/assets/43041967/07d4df01-e235-4387-9d14-6ea81e781ec7
=> TW-1602: when typing shift ctrl, the cursor is dissappear

.gitignore, lib/presentation/mixins/contacts_view_controller_mixin.dart, test/mixin/contacts_view_controller_mixin_test.dart
-  #1825 
https://github.com/linagora/twake-on-matrix/assets/99852347/aa6abc07-d8f2-4566-baae-5c6a81e11351
https://github.com/linagora/twake-on-matrix/assets/99852347/d7c00ef5-a383-4236-b563-8470734d0bc9
=> TW-1825: Copy/paste not work in search screen

lib/domain/model/preview_file/supported_preview_file_types.dart, lib/presentation/extensions/send_file_extension.dart
Issue: https://github.com/linagora/twake-on-matrix/issues/1750
https://github.com/linagora/twake-on-matrix/assets/43041967/620a2495-c1e2-4dfd-8d29-041ac79c0c12
https://github.com/linagora/twake-on-matrix/assets/43041967/28f1f047-f95f-414c-ba0a-c1eba1b1dab4
https://github.com/linagora/twake-on-matrix/assets/43041967/7a72ee19-cddf-48b1-8d46-2622f34639aa
=> Tw 1750/improve when upload video

.github/workflows/build.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml, .gitlab-ci.yml, Dockerfile
Flutter make a hot fix to fix the problem in version 3.22.2
- [Flutter issue](https://github.com/flutter/flutter/issues/149178)
- [Release note 3.22.2](https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md#3222-june-06-2024)
https://github.com/linagora/twake-on-matrix/assets/43041967/7234e1ba-1af6-41b8-90a2-cefb8870d92e
=> TW-1869: can not open keyboard when tap on the textfield in IOS

lib/pages/chat/events/html_message.dart, lib/pages/chat/input_bar/input_bar.dart, lib/pages/chat_draft/draft_chat.dart, lib/pages/chat_draft/draft_chat_input_row.dart
- #1777 
- Case 1: Can't get `matrixId` or `matrixId` not available → Only show display name
https://github.com/linagora/twake-on-matrix/assets/99852347/0730a91b-ed3f-4680-94ab-829d8938671a
https://github.com/linagora/twake-on-matrix/assets/99852347/b263b900-9932-4f26-a057-79bbfbb8fa99
- Case 2: Can get `matrixId` or `matrixId` available → Only show display name including `tag`
https://github.com/linagora/twake-on-matrix/assets/99852347/14de00f2-18a8-4658-bde3-597afae91826
https://github.com/linagora/twake-on-matrix/assets/99852347/563a34c7-4b1a-4c5e-8fa3-074f827d0ad0
=>  TW-1777: Changing greeting message: include tag in greeting message

assets/l10n/intl_en.arb, lib/pages/new_private_chat/widget/no_contacts_found.dart
#1830 
https://github.com/linagora/twake-on-matrix/assets/160496984/af271683-1c91-4289-9fb1-2daa8b131f12
https://github.com/linagora/twake-on-matrix/assets/160496984/36ea547d-e7c3-406b-83b2-fe5135757b8c
=> TW-1830 changed text when user has no contacts

assets/l10n/intl_en.arb, lib/pages/bootstrap/tom_bootstrap_dialog.dart, lib/resource/assets_paths.dart, lib/resource/image_paths.dart, lib/utils/dialog/twake_dialog.dart, lib/widgets/matrix.dart, pubspec.lock, pubspec.yaml
- #1795 
- https://github.com/linagora/future-loading-dialog/pull/1
https://github.com/linagora/twake-on-matrix/assets/99852347/1e20e479-6a83-4378-a1cf-23b21c316cdd
https://github.com/linagora/twake-on-matrix/assets/99852347/4e9b3c34-fcce-4cbf-8dcc-2715b8cc7465
=> TW-1795: Change style loading dialog

lib/data/network/media/media_api.dart, lib/domain/usecase/room/upload_content_interactor.dart, lib/presentation/extensions/send_file_extension.dart
=> TW-1758: Create upload file on web use dio

lib/pages/chat/event_info_dialog.dart
- #1807 
- Web
https://github.com/linagora/twake-on-matrix/assets/80142234/c976257f-0c53-4cdf-98a8-d2b0c771aba6
- Android
https://github.com/linagora/twake-on-matrix/assets/80142234/08a188e6-32fc-41e6-9d49-ac8623e0b628
=> TW-1807: Change message info dialog close button

lib/pages/chat_draft/draft_chat.dart, pubspec.lock, pubspec.yaml
[#fix-memory-leak](https://pub.dev/packages/file_picker/changelog#805)
=> hot-fix: fix memory leak in file picker

lib/utils/stream_list_int_extension.dart, test/stream_list_in_extension_test.dart, test/utils/stream_list_int_extension_test.dart
=> TW-1759: Improve func convert stream to bytes

lib/pages/chat/send_file_dialog/send_file_dialog.dart, lib/pages/chat_draft/draft_chat.dart, lib/presentation/enum/chat/send_media_with_caption_status_enum.dart, lib/presentation/mixins/paste_image_mixin.dart, lib/presentation/mixins/send_files_with_caption_web_mixin.dart
- #1899 
https://github.com/linagora/twake-on-matrix/assets/80142234/9171397e-aae8-43dd-8e19-af65d2ee13ee
=> TW-1899: Chat created after cancel sending file inside draft chat on web

lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/contacts_tab/contacts_tab_view_style.dart
- #1735 
https://github.com/linagora/twake-on-matrix/assets/80142234/c1764e2b-800e-440f-9709-0015ffe2cc7d
=> TW-1735: Can open chat when search exact Matrix ID

.github/pull_request_template.md
- #1924 
https://github.com/hieutbui/test
https://github.com/linagora/twake-on-matrix/assets/80142234/bcccea4b-0487-49f0-ba01-024d702ca684
=> TW-1924: Create PR template

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
- #1917 
https://github.com/hieutbui/test
https://github.com/linagora/twake-on-matrix/assets/80142234/6a64c90d-dd13-4e6b-aa22-a809ad02dd35
=> TW-1917: Create issue templates

assets/l10n/intl_en.arb, lib/pages/add_story/add_story_view.dart, lib/pages/archive/archive_view.dart, lib/pages/chat/chat_app_bar_title.dart, lib/pages/chat/chat_app_bar_title_style.dart, lib/pages/chat/chat_pinned_events/pinned_messages_screen.dart, lib/pages/chat/chat_view.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_draft/draft_chat_view.dart, lib/pages/chat_profile_info/chat_profile_info_view.dart, lib/pages/chat_search/chat_search_view.dart, lib/pages/dialer/dialer.dart, lib/pages/error_page/error_page.dart, lib/pages/homeserver_picker/homeserver_app_bar.dart, lib/pages/homeserver_picker/homeserver_picker_view.dart, lib/pages/image_viewer/media_viewer_app_bar_view.dart, lib/pages/image_viewer/media_viewer_app_bar_web.dart, lib/pages/new_group/new_group_chat_info_view.dart, lib/pages/new_private_chat/widget/contact_status_widget.dart, lib/pages/profile_info/profile_info_view.dart, lib/pages/search/search_view.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view.dart, lib/pages/twake_welcome/twake_welcome_view.dart, lib/utils/room_status_extension.dart, lib/widgets/app_bars/searchable_app_bar.dart, test/utils/get_localize_status_test.dart, test/widget/app_bars/searchable_app_bar_test.dart
#1827 
https://www.figma.com/design/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=25784-144000&t=wVc6M5FhcRkM6BLY-4
https://github.com/linagora/twake-on-matrix/assets/43041967/2552d1ee-bcfc-400b-83c9-063858c2b41f
https://github.com/linagora/twake-on-matrix/assets/43041967/d81a88b5-8ac6-429e-b9ae-70d31802b7be
=> Tw 1827/update online status based on design

lib/pages/bootstrap/bootstrap_dialog.dart, lib/pages/bootstrap/tom_bootstrap_dialog.dart, lib/pages/bootstrap/tom_bootstrap_dialog_mobile_style.dart, lib/pages/bootstrap/tom_bootstrap_dialog_mobile_view.dart, lib/pages/bootstrap/tom_bootstrap_dialog_style.dart, lib/pages/bootstrap/tom_bootstrap_dialog_web_view.dart, lib/pages/chat_blank/chat_blank.dart, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_body_view.dart, lib/pages/chat_list/chat_list_header.dart, lib/pages/chat_list/chat_list_header_style.dart, lib/pages/chat_list/chat_list_skeletonizer_style.dart, lib/pages/chat_list/chat_list_skeletonizer_widget.dart, lib/widgets/matrix.dart
- #1904 
- Web:
https://github.com/linagora/twake-on-matrix/assets/99852347/d198713b-eb07-4eac-b21a-0cfcbf700d26
- Mobile
https://github.com/linagora/twake-on-matrix/assets/99852347/08f00eb4-22c8-4f28-ae76-2cd27284768b
- Responsive
https://github.com/linagora/twake-on-matrix/assets/99852347/e52814d3-4bd8-46ba-a93f-1dc3d560b287
=> TW-1904: Improve style for backup dialog

lib/utils/background_push.dart, lib/widgets/local_notifications_extension.dart, web/script.js
- #1907 
- Web:
https://github.com/user-attachments/assets/23694d8f-8178-4985-8b39-2ccda9095435
https://github.com/user-attachments/assets/ba99733e-ca5b-4aac-9f35-0c5d2af38425
- Android:
https://github.com/user-attachments/assets/74d0c697-219a-4344-bf97-e307f4aa67dd
- IOS:
https://github.com/user-attachments/assets/5f5601ae-97c8-448a-8539-faac782c29d5
=> TW-1907: Fix jump exactly to message in the notification on Mobile

android/app/src/main/AndroidManifest.xml, lib/pages/chat_list/receive_sharing_intent_mixin.dart
- https://github.com/linagora/twake-workplace-private/issues/7
- Android:
https://github.com/user-attachments/assets/82926d36-357b-40d8-9799-0ca048e29995
- IOS:
https://github.com/user-attachments/assets/e4f13811-4387-4df7-bd38-8d66cf7a66ba
=> Integration dynamic link on android mobile

assets/l10n/intl_en.arb, assets/l10n/intl_fr.arb, lib/domain/contact_manager/contacts_manager.dart, lib/pages/chat_details/chat_details_edit.dart, lib/pages/contacts_tab/contacts_tab.dart, lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/new_group/contacts_selection.dart, lib/pages/new_group/contacts_selection_view.dart, lib/pages/new_group/new_group_chat_info.dart, lib/pages/new_private_chat/new_private_chat.dart, lib/pages/new_private_chat/new_private_chat_style.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/new_private_chat/widget/expansion_list.dart, lib/pages/settings_dashboard/settings_profile/settings_profile.dart, lib/presentation/mixins/common_media_picker_mixin.dart, lib/presentation/mixins/contacts_view_controller_mixin.dart, lib/presentation/mixins/media_picker_mixin.dart, lib/utils/permission_dialog.dart, lib/utils/permission_service.dart, test/mixin/contacts_view_controller_mixin_test.dart
#1955 
Evolution of Google Privacy policies need dialog before asking contact and image permission
- Android:
https://github.com/user-attachments/assets/12e2caa7-3def-4bf3-8bb1-bd1f8fde6b7d
https://github.com/user-attachments/assets/6d41d3a4-bbcb-4eb6-aba6-496fdefb682b
- IOS:
https://github.com/user-attachments/assets/0b40c790-4b6b-42e1-8264-5b33a7df0c39
https://github.com/user-attachments/assets/5db61025-517a-41c9-bbac-19c16c9e663d
https://github.com/user-attachments/assets/ecfe01d0-8f9c-4219-9254-1e032b1a6b35
=> TW-1955: Create permission dialogs for contacts and images

assets/l10n/intl_en.arb, assets/l10n/intl_fr.arb
=> Spelling errors

android/app/build.gradle, assets/l10n/intl_en.arb, assets/l10n/intl_fr.arb, lib/presentation/mixins/media_picker_mixin.dart, lib/utils/permission_service.dart, pubspec.lock, pubspec.yaml
Prominent disclosure updated to be closer to Google requirements. 
More informations: https://support.google.com/googleplay/android-developer/answer/10144311?visit_id=638573089252378170-2363916442&rd=1#
TLDR: 
> To meet policy requirements, it’s recommended that you reference the following example format for Prominent Disclosure when it’s required:
> 
> “[This app] collects/transmits/syncs/stores [type of data] to enable ["feature"], [in what scenario]."
> Example: “Fitness Funds collects location data to enable fitness tracking even when the app is closed or not in use and is also used to support advertising.”
> Example: “Call buddy collects read and write call log data to enable contact organization even when the app is not in use.” …
=> Hotfix: Proeminent disclosure update

lib/pages/chat_draft/draft_chat.dart
#1906 
- Web:
https://github.com/user-attachments/assets/d2bdd1e9-96b5-4958-bbba-6e09d3543180
=> TW-1906: [Web] Support send multiple files in draft chat

lib/pages/chat/chat.dart
#1808 
Change from go to push
- Web:
https://github.com/user-attachments/assets/1e09f1f0-3331-4144-8380-d515b0cf9437
- Android:
https://github.com/user-attachments/assets/88d3f9c3-4747-4ee0-a149-6eb2fa56fd52
- IOS:
https://github.com/user-attachments/assets/e007fdf0-d35b-4579-b861-8dc369f98ccd
=> TW-1808: fix navigatation problem in forward pages

assets/l10n/intl_en.arb
https://github.com/linagora/twake-on-matrix/issues/1918
- Web:
- Android:
- IOS:
=> TW-1918: Fixed typo error in externalContactMessage

lib/pages/chat/chat_pinned_events/pinned_events_view.dart, lib/pages/chat/events/reply_content.dart, lib/presentation/mixins/chat_list_item_mixin.dart
- #1813 
- Web:
https://github.com/user-attachments/assets/9abba022-e1cf-4bd2-92da-05440b84302d
- Android:
https://github.com/user-attachments/assets/86ad284f-6d5d-4832-8561-f4756fb5e951
- IOS:
https://github.com/user-attachments/assets/b35044e6-7831-43be-86e3-19e913fc75a4
=> TW-1813: Change event description for pinned files

lib/config/themes.dart, lib/pages/chat_list/chat_list_header.dart, lib/pages/chat_list/chat_list_header_style.dart, lib/utils/responsive/responsive_utils.dart, lib/widgets/avatar/bottom_navigation_avatar.dart, lib/widgets/avatar/bottom_navigation_avatar_style.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation_style.dart, lib/widgets/layouts/adaptive_layout/adaptive_scaffold_primary_navigation_view.dart, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body.dart, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body_view.dart, lib/widgets/layouts/adaptive_layout/app_adaptive_scaffold_body_view_style.dart, lib/widgets/layouts/enum/adaptive_destinations_enum.dart, lib/widgets/twake_components/twake_header.dart, lib/widgets/twake_components/twake_header_style.dart, lib/widgets/twake_components/twake_navigation_icon/twake_navigation_icon.dart, lib/widgets/unread_rooms_badge.dart
#1886 
Figma design : [Figma](https://www.figma.com/design/uLw3iWnOEGaRlJnfPz4Pv0/Twake-[Matrix]?node-id=25783-37873&t=n6R8XpD6p1Tskyo3-0)
Test on all platform with different screen sizes
- Responsive Web:
https://github.com/user-attachments/assets/0c69a919-542d-4eb1-8e7c-0108e56c365d
- Android
-multi account and changing avatar demo:
[multiAccountDemo.webm](https://github.com/user-attachments/assets/50dfd56f-5c21-45a1-8dc1-ded73933976e)
DOD:
=> TW-1886 update chatlist UI part1

docs/adr/0024-cancel-upload-file-with-caption.md, lib/pages/chat/events/images_builder/sending_image_info_widget.dart, lib/pages/chat/events/message_upload_content.dart, lib/pages/chat/events/message_video_upload_content.dart, lib/pages/chat/events/sending_video_widget.dart, lib/utils/manager/upload_manager/models/upload_file_info.dart, lib/utils/manager/upload_manager/upload_manager.dart
#1972 
- Web:
https://github.com/user-attachments/assets/b62d869e-b71a-4f4f-9181-5827500311ca
- IOS:
https://github.com/user-attachments/assets/0101b213-e54c-4d6c-b21f-c6b1f09c00a5
=> TW-1972: Update logic for cancel upload files with captions

lib/config/themes.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/chat_pinned_events/pinned_events_view.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message/message_style.dart
#1542 
https://github.com/user-attachments/assets/0c1046e1-e394-4189-ac91-c8bd24fc7862
=> TW-1542: make message highlight brighter

android/app/src/main/AndroidManifest.xml, pubspec.lock, pubspec.yaml
- Cherry pick PRs #2006 from main to maintenance branch
=> Fix google console reject

lib/pages/chat_list/chat_list_header.dart
https://github.com/user-attachments/assets/d4746018-df63-4dda-850b-730dbb8d82f1
=> Update style for search widget in chat list

lib/pages/settings_dashboard/settings/settings_item_builder.dart, lib/pages/settings_dashboard/settings/settings_view.dart, lib/pages/settings_dashboard/settings/settings_view_style.dart, lib/presentation/enum/settings/settings_enum.dart
#2026
Settings screen UI updated
- Web:
- Android:
-
- IOS:
=> Tw 2026 update settings UI

README.md
— #2036 
— Need to merge the PR first #2067 2067
https://github.com/user-attachments/assets/a5aebd09-99c6-450e-a1b0-5a92d6599541
https://github.com/user-attachments/assets/64614ff1-d570-4daa-aa97-b22a747199f5
https://github.com/user-attachments/assets/7be5480b-79e3-499d-b3a0-bac5fa6d6def
=> TW-2036: Update readme with customized homeserver

assets/l10n/intl_en.arb, assets/l10n/intl_fr.arb, assets/l10n/intl_ru.arb, assets/l10n/intl_vi.arb, lib/pages/chat/group_chat_empty_view.dart
=> TW-2089 removed multithreaded text in empty group view

lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_details/chat_details_view_style.dart
- #2122 
- Impact from PR: #2101 
https://github.com/user-attachments/assets/c2e94862-dafd-40f8-9580-42e0313451cf
=> TW-2122: Fix group information disappeared

lib/pages/chat/chat.dart
- #2068 
- Error case:
https://github.com/user-attachments/assets/01d5baa8-4a55-459e-b3b7-fc5084937d5d
- Mobile:
https://github.com/user-attachments/assets/f2f2632a-52d0-47a9-9f4b-4b45c3956bd2
=> TW-2068: Fix can't see message after accept invitation

CHANGELOG.md, config.sample.json, lib/config/app_config.dart, lib/pages/bootstrap/tom_bootstrap_dialog.dart, lib/pages/chat_blank/chat_blank.dart, pubspec.lock, pubspec.yaml
- https://github.com/linagora/future-loading-dialog/pull/3
=> Update background color for dialog

lib/pages/chat_list/chat_list_header.dart
- #1927 
- Android:
https://github.com/user-attachments/assets/068dfe85-f51a-46fb-9986-7ff0a8f60d35
- IOS:
https://github.com/user-attachments/assets/19df7873-a5a2-4a8a-b9d7-30ff9d14fd8b
=> TW-1927: Change animation for Search screen for mobile

lib/pages/twake_welcome/twake_welcome.dart, lib/utils/dialog/twake_dialog.dart
- https://github.com/linagora/twake-workplace-private/issues/147
- Mobile:
https://github.com/user-attachments/assets/fb0e8e73-dd1a-45b6-8d88-6ec753256ec9
https://github.com/user-attachments/assets/d3f1e3bd-9c48-4fa5-ad43-bdf43c5b80e2
=> TW-147: Add loading when using registration on TWP

lib/pages/forward/forward_view_style.dart, lib/utils/permission_dialog.dart, lib/widgets/contacts_warning_banner/contacts_warning_banner_style.dart, lib/widgets/contacts_warning_banner/contacts_warning_banner_view.dart, lib/widgets/twake_components/twake_text_button.dart, lib/widgets/twake_components/twake_text_button_style.dart
=> Fix Store reject by inappropriate words on buttons

pubspec.lock, pubspec.yaml
- #2145 
https://github.com/linagora/matrix-dart-sdk/pull/67
https://github.com/linagora/matrix-dart-sdk/blob/3ef4652df09a1ca99c88b80d994e4f6772fe36ab/doc/adr/003-improve-get-event-content-from-message-text.md
- Web:
https://github.com/user-attachments/assets/e2b5b341-ee29-4037-b897-7aef5f42d29d
- Android:
- IOS:
=> TW-2145: Fix HTML rendering make message bubble break

lib/presentation/mixins/connect_page_mixin.dart
- #2166 
https://github.com/user-attachments/assets/d98103b7-3d7c-47a3-a876-a870eb9f12b9
=> TW-2166: Change default to `post_login_redirect_url` in web app

assets/l10n/intl_en.arb, lib/pages/settings_dashboard/settings/settings.dart, lib/pages/settings_dashboard/settings/settings_item_builder.dart, lib/pages/settings_dashboard/settings/settings_view.dart, lib/pages/settings_dashboard/settings/settings_view_style.dart, lib/presentation/enum/settings/settings_enum.dart, lib/utils/dialog/twake_dialog.dart, lib/utils/permission_dialog.dart
- #2181 
- Android:
https://github.com/user-attachments/assets/4937244a-315d-4303-bd0f-11d822be091e
- IOS:
https://github.com/user-attachments/assets/241ce75f-b9ce-44ea-a829-d0337bde94f6
- Delete account
https://github.com/user-attachments/assets/19aec857-7240-405f-8a0e-23e944632cf4
=> TW-2181: Fix apple reject 10 Dec

lib/domain/model/search/server_side_search_categories.dart, lib/pages/search/server_search_controller.dart, lib/utils/matrix_sdk_extensions/result_extension.dart, test/utils/search_result_extension_test.dart
- #2152 
- #2111
- Web:
- Android:
- IOS:
=> Server search - Bug fixes 11 Dec

lib/pages/chat_list/chat_list.dart, lib/widgets/mixins/twake_context_menu_mixin.dart
- #2098
- Web:
https://github.com/user-attachments/assets/69611b26-5388-4737-b299-5cd37f44abe0
=> TW-2098: Support enable/disable context menu Browser

assets/l10n/intl_en.arb, lib/presentation/mixins/linkify_mixin.dart
- #2151 
- Web:
https://github.com/user-attachments/assets/949891cc-01eb-4d52-be7f-57d640e83fad
- IOS:
https://github.com/user-attachments/assets/3a00dd3b-c09e-41aa-8392-6b111a674ce5
=> TW-2151: Add a toast message when copying a phone number

lib/pages/chat_search/chat_search_style.dart, lib/pages/chat_search/chat_search_view.dart, lib/pages/new_private_chat/widget/expansion_list.dart, lib/pages/search/server_search_view.dart, pubspec.lock, pubspec.yaml
- #2144 
Update search list item
- https://github.com/linagora/linagora-design-flutter/pull/54
- Web:
- Android:
- IOS:
=> TW-2144 Update search result list item

assets/l10n/intl_en.arb, lib/utils/matrix_sdk_extensions/event_extension.dart
- #1139 
- 
- Web:
https://github.com/user-attachments/assets/0b63b96b-95e3-48f0-8ea7-0ff00b9d697c
- IOS:
https://github.com/user-attachments/assets/2d8b1147-8ad4-4aba-8f47-5fb9c18ea736
=> TW-1139: Add toast message when copying message

lib/data/datasource/contact/hive_third_party_contact_datasource.dart, lib/data/datasource_impl/contact/hive_third_party_contact_datasource_impl.dart, lib/data/hive/dto/contact/contact_hive_obj.dart, lib/data/hive/dto/contact/third_party_contact_hive_obj.dart, lib/data/hive/extension/contact_hive_obj_extension.dart, lib/data/hive/hive_collection_tom_database.dart, lib/data/repository/contact/hive_third_party_contact_repository_impl.dart, lib/di/global/get_it_initializer.dart, lib/domain/model/extensions/contact/contact_extension.dart, lib/domain/repository/contact/hive_contact_repository.dart, test/hive/contact/hive_contact_test.dart, test/hive/fake_tom_collection_database.dart
=> Store db integration federation contact

docs/configurations/configure_push_gateway.md, lib/config/app_config.dart
=> Configurable push gateway with `PUSH_NOTIFICATIONS_GATEWAY_URL`

devtools_options.yaml, lib/data/datasource_impl/contact/phonebook_contact_datasource_impl.dart, lib/data/datasource_impl/contact/tom_contacts_datasource_impl.dart, lib/domain/model/extensions/contact/address_book_extension.dart, lib/domain/model/extensions/contact/contact_extension.dart, lib/domain/model/extensions/contact/tom_contact_extension.dart, lib/domain/usecase/contacts/get_address_book_interactor.dart, lib/pages/contacts_tab/contacts_invitation_view.dart, lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/contacts_tab/contacts_tab_view_style.dart, lib/pages/new_group/contacts_selection_view.dart, lib/pages/new_private_chat/new_private_chat.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart, lib/pages/new_private_chat/widget/expansion_list.dart, lib/pages/search/recent_item_widget.dart, lib/pages/search/search.dart, lib/pages/search/search_contacts_and_chats_controller.dart, lib/presentation/extensions/contact/presentation_contact_extension.dart, lib/presentation/mixins/contacts_view_controller_mixin.dart, lib/presentation/model/search/presentation_search.dart, lib/utils/extension/presentation_search_extension.dart, lib/utils/string_extension.dart, lib/widgets/phone_book_loading/phone_book_loading_style.dart, lib/widgets/phone_book_loading/phone_book_loading_view.dart, test/data/datasource_impl/contact/phonebook_contact_datasource_impl_test.dart, test/domain/model/address_book_test.dart
=> TW-1873: support search by phone and email

lib/pages/new_private_chat/widget/expansion_list.dart
=> Hot fix contact v2

CHANGELOG.md, pubspec.yaml
- Add default value for Sygnal
- Configurable push gateway with `PUSH_NOTIFICATIONS_GATEWAY_URL`
- Synchronize contact v2
- Integration Vault contact
=> Bump version to v2.7.0

lib/domain/contact_manager/contacts_manager.dart, lib/event/twake_event_messages.dart, lib/event/twake_event_types.dart, lib/pages/contacts_tab/contacts_tab.dart, lib/pages/new_group/contacts_selection.dart, lib/pages/new_private_chat/new_private_chat.dart, lib/presentation/mixins/address_book_mixin.dart, lib/presentation/mixins/contacts_view_controller_mixin.dart, lib/widgets/matrix.dart, test/domain/contacts/contacts_manager_test.dart
https://github.com/user-attachments/assets/2d857452-8084-4de6-bc43-f38dab6e61f8
https://github.com/user-attachments/assets/8b3a3681-1cc9-47e5-ac3b-c6b65260d7c1
https://github.com/user-attachments/assets/bceb3f01-efa4-4f67-a6bc-6f8905475890
=> Auto refresh address book

lib/data/model/federation_server/federation_server_information.dart, lib/domain/contact_manager/contacts_manager.dart, lib/widgets/matrix.dart
https://github.com/user-attachments/assets/1fc734bf-a681-4396-83dc-9e4b51e2af6b
=> Try to get federation configuration

lib/domain/contact_manager/contacts_manager.dart
=> Hot fix auto refresh address book

lib/domain/contact_manager/contacts_manager.dart, lib/pages/multiple_accounts/multiple_accounts_picker.dart, lib/widgets/matrix.dart, test/domain/contacts/contacts_manager_test.dart
https://github.com/user-attachments/assets/efedfbf7-b5a8-4106-91fc-5a28bad85eee
=> Handle synchronize contact for multiple account

lib/pages/key_verification/key_verification_dialog.dart, lib/pages/key_verification/key_verification_styles.dart, lib/widgets/matrix.dart
- fix problem to make key verification work
- fix dialog to prevent overflow
https://github.com/user-attachments/assets/b6b655a9-8130-4938-b548-088ac3588e90
https://github.com/user-attachments/assets/31070884-6d5d-4c99-b453-2d74ffaa6e91
=> Repair key verification

assets/l10n/intl_en.arb, lib/data/datasource/invitation/invitation_datasource.dart, lib/data/datasource_impl/invitation/invitation_datasource_impl.dart, lib/data/model/invitation/generate_invitation_link_response.dart, lib/data/model/invitation/invitation_request.dart, lib/data/model/invitation/send_invitation_response.dart, lib/data/network/invitation/invitation_api.dart, lib/data/network/tom_endpoint.dart, lib/data/repository/invitation/invitation_repository_impl.dart, lib/di/global/get_it_initializer.dart, lib/domain/app_state/invitation/send_invitation_state.dart, lib/domain/model/invitation/invitation_medium_enum.dart, lib/domain/repository/invitation/invitation_repository.dart, lib/domain/usecase/invitation/send_invitation_interactor.dart, lib/pages/contacts_tab/contacts_invitation.dart, lib/pages/contacts_tab/contacts_invitation_view.dart, lib/pages/contacts_tab/contacts_tab.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
=> TW-2270: Integration API in data layer

assets/l10n/intl_en.arb, lib/data/network/invitation/invitation_api.dart, lib/di/global/get_it_initializer.dart, lib/domain/app_state/invitation/generate_invitation_link_state.dart, lib/domain/usecase/invitation/generate_invitation_link_interactor.dart, lib/pages/contacts_tab/contacts_invitation.dart, lib/pages/contacts_tab/contacts_invitation_view.dart
- #2271 
- Web:
- Android:
- IOS:
=> TW-2271: Copy share invitation link

assets/l10n/intl_en.arb, lib/pages/bootstrap/bootstrap_dialog.dart, lib/utils/platform_infos.dart
https://github.com/user-attachments/assets/c954e69b-12bc-42df-8879-72ba26079ee0
=> improving Verification device

assets/l10n/intl_en.arb, lib/domain/contact_manager/contacts_manager.dart, lib/domain/model/extensions/contact/contact_extension.dart, lib/domain/usecase/contacts/federation_look_up_phonebook_contact_interactor.dart, lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/new_group/contacts_selection_view.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/search/search_contacts_and_chats_controller.dart, lib/presentation/mixins/contacts_view_controller_mixin.dart
- Has many request to FED API and then phonebook contact not display.
https://github.com/user-attachments/assets/95253644-78bc-4b1d-a83f-6ac5c12f42e8
=> Sync contact error handle link

lib/data/model/invitation/invitation_status_response.dart, lib/di/global/get_it_initializer.dart, lib/domain/app_state/contact/delete_third_party_contact_box_state.dart, lib/domain/app_state/invitation/hive_delete_invitation_status_state.dart, lib/domain/usecase/contacts/delete_third_party_contact_box_interactor.dart, lib/domain/usecase/invitation/hive_delete_invitation_status_interactor.dart, lib/pages/contacts_tab/contacts_tab.dart, lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart, lib/presentation/mixins/invitation_status_mixin.dart
https://github.com/user-attachments/assets/93bc3b3c-4cbc-4356-8434-e2f0a43e101b
- Step 1: Sent 2 invitations => icon invitation changed color (Blue to Green)
- Step 2: Wait for time expired, go to contact tab again
- Step 3: Icon invitation changed  color (Green to Blue) and can send invitation again
https://github.com/user-attachments/assets/933c0c66-24c9-439d-af20-78a3321ef62e
=> Tw 2272 handle accept invitation

assets/l10n/intl_en.arb, lib/pages/contacts_tab/contacts_invitation_view.dart
- Update text style (Color, size, select mode)
- Add new desc text when selected item
https://github.com/user-attachments/assets/01c53ea2-e8fb-4372-b167-79e7d6eff96c
=> Update UI style for invitation contact

lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
https://github.com/user-attachments/assets/71122ca7-d736-4d8e-a2f0-3fcaaa8ccfb0
=> Hotfix: Can't open chat with phone book contact has matrix Id

lib/utils/twake_snackbar.dart
https://github.com/user-attachments/assets/a6645772-2a0e-4747-92bd-fbe94ef23cbb
=> Add close icon in snack bar

lib/pages/contacts_tab/contacts_tab.dart, lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart, lib/presentation/mixins/wellknown_mixin.dart, test/presentation/mixins/wellknown_mixin_test.dart
https://github.com/user-attachments/assets/bad32cb5-f38f-436c-ac52-192d7fe7d421
https://github.com/user-attachments/assets/37e5b829-f859-4e58-a70d-a8e8eee6fd5f
=> TW-2323 Disable/Enable invitation base on well-known properties

lib/pages/chat/events/message/message_content_with_timestamp_builder.dart
=> Prevent rebuild when listen new event

lib/pages/chat/chat.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat/events/message_reactions.dart, lib/pages/chat/events/message_reactions_bottom_sheet.dart, lib/pages/chat/events/message_reactions_style.dart
- #2263
- Web:
https://github.com/user-attachments/assets/15ff4cc2-d0df-49ea-aa2e-6852553fe523
- Mobile:
https://github.com/user-attachments/assets/fb57ab0c-5e82-4b14-a890-3f71e3b2732c
=> TW-2263: Display emoji reaction for message

lib/pages/chat/chat.dart, lib/pages/chat/chat_context_menu_actions.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/chat_view_body.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat/events/message_reactions.dart, lib/pages/chat_draft/draft_chat.dart, lib/pages/chat_draft/draft_chat_input_row.dart, lib/pages/chat_draft/draft_chat_view.dart
- #2307
https://github.com/user-attachments/assets/5163f3ff-1f98-4b19-b0cd-fccc6b774ed8
=> TW-2307: Improve context menu in tablet

lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat/events/message/message_style.dart
- Display own message not correct position 
- Related #2338
- Web:
https://github.com/user-attachments/assets/1aeacb3d-72d6-4634-8e48-ee627d0b66f3
- IOS:
https://github.com/user-attachments/assets/e23c0a60-2134-4eaf-8d8e-9adf5e67b7d8
=> Hotfix: Display own message not correct position

lib/pages/chat/events/message/message_content_builder_mixin.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat/events/message_content.dart, lib/utils/matrix_sdk_extensions/event_extension.dart
- #2322
- Web:
https://github.com/user-attachments/assets/cce56520-d6b5-48fd-a562-290c52999006
- IOS:
https://github.com/user-attachments/assets/2054ae5b-87c3-4587-b8a4-bcc7e665ec59
=> TW-2322: Make emojies in chat bigger

lib/pages/profile_info/profile_info_body/profile_info_body.dart, lib/widgets/avatar/avatar.dart
- #2053 
- IOS:
https://github.com/user-attachments/assets/4e11f8cf-8c48-4c8a-be71-a7f0d8924b7c
- Web:
https://github.com/user-attachments/assets/80381165-d38a-4088-aecd-1842735b7a20
https://github.com/user-attachments/assets/7901ab08-8152-426c-88df-c5f170cf687a
=> TW-2053: Improve creating a DM with someone from a group chat

lib/data/network/media/media_api.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat/events/message/message_context_menu_action.dart
- #2356 
- Android:
https://github.com/user-attachments/assets/a7e97425-8788-4812-8fb5-62ec2480541f
=> TW-2356: Add download option for message with files or media

lib/data/model/invitation/invitation_status_response.dart, lib/pages/contacts_tab/contacts_invitation.dart
- #2314 
https://github.com/user-attachments/assets/eeb9add8-2d00-43a7-b9eb-a84b83b6fa22
=> TW-2314: Improve generate and share link invitation

lib/pages/homeserver_picker/homeserver_picker.dart
- #2342
https://github.com/user-attachments/assets/838527e4-1c34-4ef9-8dc7-4c3120d73d68
=> TW-2342: Fix added account is displayed as the first account

assets/l10n/intl_en.arb, lib/domain/model/room/room_extension.dart, lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/chat_pinned_events/pinned_messages.dart, lib/pages/chat/chat_pinned_events/pinned_messages_screen.dart, lib/pages/chat/chat_view_body.dart, lib/pages/chat/disabled_chat_input_row.dart, lib/pages/chat/disabled_chat_input_row_style.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat_details/chat_details_view.dart
https://github.com/user-attachments/assets/8cfe819a-5640-4d95-9b5d-2429d4a82846
=> Room permission system

lib/pages/chat/events/message/message_content_with_timestamp_builder.dart
=> TW-2374: Add blur behind reaction screen should darker

lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/image_viewer/media_viewer_app_bar_view.dart, lib/pages/settings_dashboard/settings_profile/settings_profile.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view_mobile.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view_web.dart, lib/widgets/context_menu/context_menu_action_item_widget.dart, lib/widgets/context_menu/twake_context_menu.dart, lib/widgets/mixins/popup_context_menu_action_mixin.dart, lib/widgets/mixins/popup_menu_widget_mixin.dart, lib/widgets/mixins/popup_menu_widget_style.dart, lib/widgets/mixins/twake_context_menu_style.dart
- #2353 
https://github.com/user-attachments/assets/ece2a185-7267-43ac-a5dd-088387f6d201
=> TW-2353: Unifying context menu

assets/l10n/intl_en.arb, lib/config/default_power_level_member.dart, lib/domain/model/room/room_extension.dart, lib/pages/chat_details/assign_roles/assign_roles.dart, lib/pages/chat_details/assign_roles/assign_roles_search_state.dart, lib/pages/chat_details/assign_roles/assign_roles_view.dart, lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_details/chat_details_edit_option.dart, lib/pages/chat_details/chat_details_edit_option_style.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/chat_details/chat_details_page_view/chat_details_members_page.dart, lib/pages/chat_details/participant_list_item/participant_list_item.dart, lib/utils/user_extension.dart
- #2367 
- Web:
https://github.com/user-attachments/assets/f1219203-20b6-4756-a89e-b46ea23ac34e
- IOS:
https://github.com/user-attachments/assets/06804ce9-3b18-4e7c-a55b-67a605e232b2
=> TW-2367: Add Adminstrator category with Assign role item

lib/pages/chat/chat_event_list.dart, lib/pages/chat/events/message/message.dart, lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/pages/chat/events/message/message_context_menu_action.dart
https://github.com/user-attachments/assets/6c60735f-caec-4375-ba99-3f435866b710
=> TW #2349 delete context menu in long press

lib/pages/chat/events/message_video_download_content.dart
- #2345
- Web:
- Android:
- IOS:
=> TW-2345: Fix could not share media from gallery by Twake

assets/l10n/intl_en.arb, lib/config/default_power_level_member.dart, lib/domain/model/room/room_extension.dart, lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/chat_details/exceptions/exceptions.dart, lib/pages/chat_details/exceptions/exceptions_search_state.dart, lib/pages/chat_details/exceptions/exceptions_view.dart, lib/utils/power_level_manager.dart, lib/utils/user_extension.dart, test/utils/power_level_manager_test.dart
- #2384
- Web:
- Android:
- IOS:
=> TW-2384: Impl Exceptions tab

lib/pages/contacts_tab/contacts_tab.dart, lib/pages/contacts_tab/contacts_tab_body_view.dart, lib/pages/new_private_chat/new_private_chat.dart, lib/pages/new_private_chat/widget/expansion_contact_list_tile.dart
https://github.com/user-attachments/assets/ffc43e4c-75d1-47ff-a1db-d27998ec3384
https://github.com/user-attachments/assets/128e134a-f586-45a9-93c5-16b5009e9c13
=> TW #2401 Handle click on internal contact

assets/l10n/intl_en.arb, lib/domain/model/room/room_extension.dart, lib/pages/chat_details/assign_roles/assign_roles_view.dart, lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_details/chat_details_edit_option.dart, lib/pages/chat_details/chat_details_edit_option_style.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_details/exceptions/exceptions_view.dart, lib/pages/chat_details/removed/removed.dart, lib/pages/chat_details/removed/removed_search_state.dart, lib/pages/chat_details/removed/removed_view.dart, lib/utils/user_extension.dart, lib/widgets/app_bars/twake_app_bar.dart, lib/widgets/app_bars/twake_app_bar_style.dart
- #2393
- Web:
https://github.com/user-attachments/assets/9d028d44-abb2-419d-98b7-cbf4f07ace30
- IOS:
https://github.com/user-attachments/assets/d781daa0-9474-4145-82f4-aa14b4b56ee1
=> TW-2393: removed list

CHANGELOG.md, pubspec.yaml
=> Bump version to v2.9.7

lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/chat_view_body.dart, lib/pages/chat/events/formatted_text_widget.dart, lib/widgets/mixins/drag_drog_file_mixin.dart, lib/widgets/twake_components/twake_preview_link/twake_link_view.dart, lib/widgets/twake_components/twake_preview_link/twake_link_view_style.dart
- Select text for single message bubble
=> Update selection text

assets/l10n/intl_en.arb, lib/pages/profile_info/copiable_profile_row/copiable_profile_row.dart, lib/pages/profile_info/copiable_profile_row/copiable_profile_row_style.dart, lib/pages/profile_info/copiable_profile_row/icon_copiable_profile_row.dart, lib/pages/profile_info/profile_info_body/profile_info_body.dart, lib/pages/profile_info/profile_info_body/profile_info_body_view.dart, lib/pages/profile_info/profile_info_body/profile_info_body_view_style.dart, lib/pages/profile_info/profile_info_body/profile_info_contact_rows.dart, lib/pages/profile_info/profile_info_body/profile_info_header.dart, lib/pages/profile_info/profile_info_view.dart, lib/presentation/enum/profile_info/profile_info_body_enum.dart, lib/presentation/mixins/chat_details_tab_mixin.dart, lib/utils/matrix_sdk_extensions/presence_extension.dart
- #2380 
- Web:
https://github.com/user-attachments/assets/72111e7d-9e23-4ed6-8200-2834a50806a8
- IOS:
https://github.com/user-attachments/assets/dfb97192-a9c9-4cd0-b051-ac00d5ff2f97
=> TW-2380: Add back the Remove member button in a group chat

assets/l10n/intl_en.arb, lib/di/global/get_it_initializer.dart, lib/domain/app_state/room/set_permission_level_state.dart, lib/domain/usecase/room/set_permission_level_interactor.dart, lib/pages/chat_details/assign_roles/assign_roles.dart, lib/pages/chat_details/assign_roles/assign_roles_view.dart, lib/pages/chat_details/assign_roles_member_picker/assign_roles_member_picker.dart, lib/pages/chat_details/assign_roles_member_picker/assign_roles_member_picker_view.dart, lib/pages/chat_details/assign_roles_role_picker/assign_roles_role_picker.dart, lib/pages/chat_details/assign_roles_role_picker/assign_roles_role_picker_view.dart, lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_permissions_settings/chat_permissions_settings.dart, lib/widgets/app_bars/twake_app_bar.dart, lib/widgets/app_bars/twake_app_bar_style.dart
- Web:
- Android:
- IOS:
https://github.com/user-attachments/assets/6d256917-f60b-4545-a6e3-919e9c58fa79
https://github.com/user-attachments/assets/56ff6790-dbf4-4af8-8038-99976c3cccfd
=> Add interactor for setting user permission levels and update role assignment logic

lib/domain/model/room/room_extension.dart, lib/pages/chat/chat_actions.dart, lib/pages/chat_details/assign_roles/assign_roles.dart, lib/pages/chat_details/assign_roles/assign_roles_view.dart
https://github.com/user-attachments/assets/247b3b7b-fec5-44cb-8da6-2e0c6f92371f
https://github.com/user-attachments/assets/1d7c9fab-678a-42b4-aac1-42f96f4f8229
=> [REVIEW PART I ] Implement quick role picker for user role assignment

lib/pages/chat_details/assign_roles_member_picker/assign_roles_member_picker_style.dart, lib/pages/chat_details/assign_roles_member_picker/assign_roles_member_picker_view.dart, lib/pages/chat_details/assign_roles_role_picker/assign_roles_role_picker_view.dart
https://github.com/user-attachments/assets/2325ffb2-fd37-4d53-8a57-322c2d984708
https://github.com/user-attachments/assets/d39076e0-a797-4bef-a6c9-6e27bef4cd3d
https://github.com/user-attachments/assets/f7695ebc-a061-4089-961d-780616bcafeb
=> Fix display name overflow in assign role picker

assets/l10n/intl_en.arb, lib/pages/settings_dashboard/settings/settings.dart, lib/presentation/mixins/delete_event_mixin.dart, lib/utils/dialog/twake_dialog.dart, pubspec.lock
https://www.notion.so/linagora/Delete-message-confirmation-modal-22262718bad180228dbcec8f1d59692f
- https://github.com/linagora/linagora-design-flutter/pull/60
- Web:
https://github.com/user-attachments/assets/d731a3aa-9e1d-45f5-99ad-e88d46d0d2c4
- Mobile:
https://github.com/user-attachments/assets/9ae41102-ea14-4fbd-8b7d-48890cf96ff5
=> Add confirmation dialog before delete message

assets/l10n/intl_en.arb, lib/domain/enums/selection_mode_enum.dart, lib/pages/chat_details/assign_roles_member_picker/selected_user_notifier.dart, lib/pages/chat_details/chat_details_page_view/chat_details_members_page.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_details/participant_list_item/participant_list_item.dart, lib/pages/profile_info/profile_info_body/profile_info_body.dart, lib/presentation/mixins/chat_details_tab_mixin.dart
https://www.notion.so/linagora/Mobile-Long-press-selects-members-to-be-removed-from-chat-22262718bad180e4ab48f991527ab7d8
- https://github.com/linagora/twake-on-matrix/pull/2443
https://github.com/user-attachments/assets/4a40c6ce-f9e1-4979-8138-e6dcff62dcec
=> Allow selecting users to remove by long pressing

lib/pages/chat_details/assign_roles_member_picker/assign_roles_member_picker_view.dart, lib/pages/chat_details/assign_roles_role_picker/assign_roles_role_picker_view.dart, lib/pages/chat_details/exceptions/exceptions_view.dart, lib/pages/chat_details/removed/removed_view.dart
https://github.com/user-attachments/assets/f38fe532-db4e-4783-9f5b-a8bee7ee4b1a
https://github.com/user-attachments/assets/8c2f6380-4c0f-47f2-955e-eb9b7bbbed4a
=> Fix display name overflow in exceptions, removed and role pickers

assets/l10n/intl_en.arb, lib/di/global/get_it_initializer.dart, lib/domain/app_state/room/ban_user_state.dart, lib/domain/model/room/room_extension.dart, lib/domain/usecase/room/ban_user_interactor.dart, lib/pages/chat_details/assign_roles/assign_roles.dart, lib/pages/chat_details/assign_roles/assign_roles_style.dart, lib/pages/chat_details/assign_roles/assign_roles_view.dart, lib/pages/chat_details/chat_details_edit.dart, lib/pages/chat_details/chat_details_edit_view.dart, lib/presentation/mixins/chat_details_tab_mixin.dart
https://github.com/user-attachments/assets/f018019c-cb14-44a7-be58-ef5e8be22b5a
https://github.com/user-attachments/assets/f6adaeb9-baa5-4fe0-8d6d-cba77946fa5e
=> [REVIEW PART III] Mobile swipe left to remove admin moderator from the group

android/app/build.gradle, android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/app/twake/android/chat/UnifiedPushService.kt, android/app/src/profile/AndroidManifest.xml, android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, android/settings.gradle, lib/utils/background_push.dart, pubspec.lock, pubspec.yaml
https://www.notion.so/linagora/Upgrade-Android-API-for-Twake-22462718bad18036a455f922a1894c46
=> Upgrade Android API 35

lib/domain/usecase/room/set_permission_level_interactor.dart, lib/pages/chat_details/assign_roles/assign_roles.dart, lib/pages/chat_details/assign_roles/assign_roles_view.dart, lib/pages/chat_details/assign_roles_member_picker/assign_roles_member_picker.dart, lib/pages/chat_details/assign_roles_role_picker/assign_roles_role_picker.dart, lib/pages/chat_details/exceptions/exceptions.dart, lib/pages/chat_details/exceptions/exceptions_view.dart, lib/pages/chat_details/participant_list_item/participant_list_item.dart, lib/pages/chat_details/removed/removed_view.dart, lib/pages/invitation_selection/invitation_selection.dart, lib/pages/profile_info/profile_info_body/profile_info_body.dart, lib/presentation/mixins/invite_external_contact_mixin.dart, lib/utils/user_extension.dart
https://github.com/user-attachments/assets/d5ae6b12-8335-4bec-91c5-b36779ac1955
https://github.com/user-attachments/assets/a190528e-6efd-4a9f-981f-d49ad703836d
https://github.com/user-attachments/assets/b6d51a75-2141-400b-8678-cfb87aaf9ce9
https://github.com/user-attachments/assets/263127ff-9327-4c3f-9c61-0d6443181273
=> TW-2457: Polishing UI relate to assign role

CHANGELOG.md, pubspec.yaml
- #2460 Features assign roles
- Display contact status
- #2384 Impl Exceptions tab
- #2454 Upgrade Android API 35
- #2060 Fix unable to select text in message bubble with mouse on web
=> Bump version to v2.10.0

assets/l10n/intl_en.arb, lib/di/global/get_it_initializer.dart, lib/domain/app_state/room/unban_user_state.dart, lib/domain/usecase/room/unban_user_interactor.dart, lib/pages/chat_details/removed/removed.dart, lib/pages/chat_details/removed/removed_view.dart
https://github.com/user-attachments/assets/1ec8e3bb-f716-4c29-a435-4114d5751bf9
https://github.com/user-attachments/assets/de500715-6966-4fbc-a8d5-65a057d63979
=> Add unban user functionality with interactor and UI integration

CHANGELOG.md, pubspec.yaml
- Add unban user functionality with interactor and UI integration
=> Bump version to v2.10.3

lib/pages/chat_list/chat_list_view_builder.dart, lib/pages/chat_list/slidable_chat_list_item.dart
- #2476 
https://github.com/user-attachments/assets/f54e7b0f-8de8-4736-9f5e-44da33394170
=> TW-2476: Fix chats with events as last messages blink

lib/pages/chat_details/chat_details_page_view/chat_details_members_page.dart, lib/pages/chat_details/participant_list_item/participant_list_item.dart, lib/pages/chat_details/participant_list_item/participant_list_item_style.dart, lib/presentation/mixins/chat_details_tab_mixin.dart, pubspec.lock
https://www.notion.so/linagora/Desktop-remove-member-button-on-member-list-21f62718bad180eb96c1e87531caee5e
- https://github.com/linagora/emoji_mart/pull/6
- https://github.com/linagora/linagora-design-flutter/pull/61
- Web:
https://github.com/user-attachments/assets/93924659-855a-4acd-b22e-73b68a6cade0
=> [Desktop] “remove member” button on member list

lib/config/go_routes/go_router.dart, lib/pages/chat/chat.dart
- #2421
https://github.com/user-attachments/assets/fee037a1-567d-4d8f-a09b-52af6f9ddfbb
https://github.com/user-attachments/assets/1c13a2bc-66e5-40e1-a0e0-72fdba6ca30e
https://github.com/user-attachments/assets/30b179e9-6f55-4b2f-ba17-a0d865be59f1
=> TW-2421: Improve the chat view screen flickers when switching the responsive web browser

lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/utils/matrix_sdk_extensions/event_extension.dart
- #2427 
- Web:
https://github.com/user-attachments/assets/3df7c5a1-f306-4c81-8244-88e13ae00f16
- IOS:
https://github.com/user-attachments/assets/f203067e-82b1-4736-b794-864bc5eab45c
=> TW-2427: Improve spaces between messages remain after deleting emojis

docs/configurations/config_web_app_for_public_platform.md
=> Add missing comma in config_web_app_for_public_platform.md

README.md, config.sample.json, docs/configurations/config_web_app_for_public_platform.md, lib/config/app_config.dart, lib/main.dart, pubspec.lock
- https://github.com/linagora/emoji_mart/pull/8
=> Apply dynamic cozy bridge version

lib/domain/app_state/contact/get_phonebook_contact_state.dart, lib/domain/contact_manager/contacts_manager.dart, lib/domain/model/extensions/contact/tom_contact_extension.dart, lib/domain/usecase/contacts/federation_look_up_phonebook_contact_interactor.dart, lib/pages/contacts_tab/contacts_tab.dart, lib/pages/search/search_contacts_and_chats_controller.dart, lib/presentation/mixins/contacts_view_controller_mixin.dart, test/domain/contacts/contacts_manager_test.dart, test/domain/usecase/contacts/federation_look_up_phonebook_contact_interactor_test.dart, test/mixin/contacts_view_controller_mixin_test.dart
- #2453
- #2470
https://github.com/user-attachments/assets/8cfcb89b-5638-48cd-936c-1352dafac42e
https://github.com/user-attachments/assets/6a4b63b5-11ad-4b87-a17a-d04f7b194fe7
Demo case NO FED available
https://github.com/user-attachments/assets/665fb1d1-5f68-434b-b884-ea24457e3795
=> TW-2453: Refactor contact sync stuck when no federation available

lib/widgets/local_notifications_extension.dart, lib/widgets/matrix.dart, pubspec.lock, pubspec.yaml
https://www.notion.so/linagora/Enable-notification-when-app-inside-cozy-app-bar-21d62718bad18021b3ead9db5d0668c4
- https://github.com/linagora/linagora-design-flutter/pull/62
Localhost is unable to login when inside locally hosted Cozy, wait for test deployment.
=> Support notification when inside Cozy dashboard

CHANGELOG.md, pubspec.yaml
- Translation for en, ru, fr, vi
- #2484 Upgrade flutter sdk to 3.27.4
- #2483 Improve the chat view screen flickers when switching the responsive web browser
- #2427 Improve spaces between messages remain after deleting emojis
- #2489 Refactor unban user flow to refresh removed members
- #2439 Add interactor for setting user permission levels and update role assignment logic
- #2505 Refactor contact sync stuck when no federation available
- #2474 Update confirmation dialog button label for message deletion
- #2469 Refactor avatar size handling to use `byte_converter` package for improved clarity
- #2476 Fix chats with events as last messages blink
- #2486 Change docker image to build web app
- #2491 Implement block and unblock user functionality
- #2496 Add Block list to Settings
- #2501 …
=> Bump version v2.11.0

lib/pages/chat/events/message/message_content_with_timestamp_builder.dart, lib/utils/matrix_sdk_extensions/event_extension.dart
- #2512 
https://github.com/user-attachments/assets/e8d37cad-831a-48c2-98ce-af5bb201a791
=> TW-2512: Fix context menu display logic for message bubbles

lib/pages/chat/chat_event_list.dart
https://github.com/linagora/twake-on-matrix/blob/3cb3bbc255f4ee80072e3dbccefa224349e1e076/lib/pages/chat/chat_event_list.dart#L136-L145
`controller.timeline!.events` was used to calculate index of current, next and previous event
https://github.com/linagora/twake-on-matrix/blob/3cb3bbc255f4ee80072e3dbccefa224349e1e076/lib/pages/chat/chat_event_list.dart#L151-L152
https://github.com/linagora/twake-on-matrix/blob/3cb3bbc255f4ee80072e3dbccefa224349e1e076/lib/pages/chat/chat_event_list.dart#L242
However, the view is filtering out every event that `event.isVisibleInGui == false`, which makes next and previous event interactions incorrect
=> HOTFIX Avatar sometimes not showing

lib/pages/chat_details/assign_roles/assign_roles.dart, lib/pages/chat_details/assign_roles/assign_roles_view.dart, lib/pages/chat_details/assign_roles_role_picker/quick_role_picker_mixin.dart, lib/pages/chat_details/exceptions/exceptions.dart, lib/pages/chat_details/exceptions/exceptions_view.dart
- #2533 
https://github.com/user-attachments/assets/b513782b-04a9-49c8-a792-e0664d5950fc
https://github.com/user-attachments/assets/acbfc46a-1257-4495-895a-fed5a7bbde32
=> TW-2533 Apply role picker for exception list

lib/data/datasource/capabilities/server_capabilities_datasource.dart, lib/data/datasource_impl/capabilities/server_capabilities_datasource_impl.dart, lib/data/model/capabilities/server_capabilities_response.dart, lib/data/network/capabilities/server_capabilities_api.dart, lib/data/network/homeserver_endpoint.dart, lib/data/repository/capabilities/server_capabilities_repository_impl.dart, lib/di/global/get_it_initializer.dart, lib/di/global/network_di.dart, lib/domain/app_state/capabilities/get_server_capabilities_state.dart, lib/domain/model/capabilities/capabilities_extension.dart, lib/domain/repository/capabilities/server_capabilities_repository.dart, lib/domain/usecase/capabilities/get_server_capabilities_interactor.dart, lib/pages/settings_dashboard/settings_profile/settings_profile.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_capability_check.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_item.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view_mobile.dart, lib/pages/settings_dashboard/settings_profile/settings_profile_view_web.dart
- #2541 
https://github.com/user-attachments/assets/6262c141-b543-4d0d-991f-c4a971f830e5
https://github.com/user-attachments/assets/a88996af-ab02-4cb5-b2a7-0b9822c908fb
=> TW-2541 Apply capabilities settings to profile page

lib/presentation/mixins/handle_clipboard_action_mixin.dart
- #2553
https://github.com/user-attachments/assets/25f9e65f-ce70-4a13-ad3f-985124140613
=> TW-2553: Prevent pasting when chat input is not focused or room is null

lib/pages/chat/chat_input_row.dart, lib/pages/chat_draft/draft_chat_input_row.dart
- #2570
https://github.com/user-attachments/assets/4a2aabcc-f2f4-4e2f-b5c0-fcc22bb874d8
=> TW-2570: Fix text in composer disappears if lose focus

integration_test/robots/home_robot.dart, integration_test/robots/setting/app_language_setting_robot.dart, integration_test/robots/setting/setting_robot.dart, integration_test/robots/setting_robot.dart, integration_test/tests/setting/language_test.dart
PR includes the changes for the script “verify action on App Language screen.”
**Attach video**
https://github.com/user-attachments/assets/aa534b40-265a-4fa9-89ce-17ae2f1c3451
=> Change applanguage

lib/pages/chat/chat_input_row.dart
https://github.com/user-attachments/assets/55f8a85a-dc67-4e86-928f-c56078cd8a5c
=> Hide audio playback when selection mode is active on mobile
